### PR TITLE
aspell: fix shared linking, disable pthreads, and add archlinux patches

### LINKED ISSUE #1143: commit b4decd3: incorrect linking with libaspell-15.dll
after b4decd3 on launch application EiskaltDC++ has error: https://github.com/mxe/mxe/pull/1127#issuecomment-169441880 file is missing libdl.dll.a
Build of EiskalDC++ with -DUSE_ASPELL=OFF is working fine.

### PR DESCRIPTION
**Pull request by tonytheodore**
fixes #1143

### CODE REVIEW

**Comment by pavelvat** [comment]
http://pastebin.com/8FxuPmYt

**Comment by tonytheodore** [comment]
Is this with a clean build or are other packages installed (`ls usr/i686-w64-mingw32.shared/installed/`)?

**Comment by pavelvat** [comment]
It is not a clean build:
```
$ ls usr/i686-w64-mingw32.shared/installed/
aspell       fontconfig          gnutls     libgnurx        lzo        pkgconf         qtenginio           qtsensors       qtwebengine    xz
binutils     freetds             harfbuzz   libgpg_error    mingw-w64  postgresql      qtgraphicaleffects  qtserialport    qtwebkit       zlib
boost        freetype            icu4c      libiconv        miniupnpc  qt3d            qtimageformats      qtservice       qtwebsockets
bzip2        freetype-bootstrap  jpeg       libidn          mxe-conf   qt5             qtlocation          qtsvg           qtwinextras
cairo        gcc                 jsoncpp    libmng          nettle     qtactiveqt      qtmultimedia        qtsystems       qtxlsxwriter
dbus         gettext             lcms       libmysqlclient  openssl    qtbase          qtquick1            qttools         qtxmlpatterns
dlfcn-win32  glib                libffi     libpng          pcre       qtconnectivity  qtquickcontrols     qttranslations  sqlite
expat        gmp                 libgcrypt  lua             pixman     qtdeclarative   qtscript            qtwebchannel    tiff
```
For clean build all fine, but ```copydlldeps.py``` says about ```libdl.dll.a``` again:
```
~/tmp/mxe$ cp ~/tmp/mxe/usr/i686-w64-mingw32.shared/bin/libaspell-15.dll ~/tmp/aspell/
~/tmp/mxe$ ./tools/copydlldeps.py ~/tmp/aspell/ -C ~/tmp/aspell/ -L ~/tmp/mxe/usr/i686-w64-mingw32.shared/bin/
Missing dll files: kernel32.dll, msvcrt.dll, libdl.dll.a, user32.dll

```

**Comment by tonytheodore** [comment]
Now I think I'm losing my mind, I can see the same `libdl.dll.a` issue again.

**Comment by tonytheodore** [comment]
Okay, I've [disabled `dlopen`](https://github.com/mxe/mxe/commit/17a58bdb2f0b5145332c6507472e27b0f50bf848) and now `aspell.exe` is working.

I'll see if I can replicate the ordering issue with other packages install.

**Comment by pavelvat** [comment]
@tonytheodore sorry, but in last time I forgot ```git checkout aspell``` after ```git fetch origin pull/1210/head:aspell``` for clean MXE build. After ```git checkout aspell``` I have the same error http://pastebin.com/8FxuPmYt about ```undefined reference to `libintl_dgettext'``` on clean MXE build. I fixed it by adding this lines:
```
    $(if $(BUILD_SHARED),\
        $(SED) -i 's#^postdeps="-#postdeps="-lintl -#g' '$(1)/libtool')
```
Now ```copydlldeps.py``` says:
```
~/tmp/mxe$ cp ~/tmp/mxe/usr/i686-w64-mingw32.shared/bin/libaspell-15.dll ~/tmp/aspell/
~/tmp/mxe$ ./tools/copydlldeps.py ~/tmp/aspell/ -C ~/tmp/aspell/ -L ~/tmp/mxe/usr/i686-w64-mingw32.shared/bin/
Missing dll files: advapi32.dll, kernel32.dll, msvcrt.dll, user32.dll
```

**Comment by tonytheodore** [comment]
> Missing dll files: advapi32.dll, kernel32.dll, msvcrt.dll, user32.dll

Those look reasonable as they are supplied by windows. Is `libdl.dll` copied to the `~/tmp/aspell/` directory? The log above is prior to disabling it and I'm not sure why it would succeed.

**Comment by pavelvat** [comment]
>Is libdl.dll copied to the ~/tmp/aspell/ directory?

No. I built commit https://github.com/tonytheodore/mxe/commit/17a58bdb2f0b5145332c6507472e27b0f50bf848 with disabled dlopen + my fix above for libintl.
```
~/tmp/aspell$ ls
libaspell-15.dll  libgcc_s_sjlj-1.dll  libiconv-2.dll  libintl-8.dll  libstdc++-6.dll
```
This http://pastebin.com/8FxuPmYt is old log from first message #1210 (comment). I attached old log because new log contained the same error about ```undefined reference to `libintl_dgettext'```.

**Comment by tonytheodore** [comment]
Okay, added libintl fix above: https://github.com/mxe/mxe/commit/50180c28d9ff09616dc39c73a033a5e75e8979db

**Comment by pavelvat** [comment]
Almost a month has passed ...
This PR fixed https://github.com/mxe/mxe/issues/1143, please merge it.

**Comment by starius** [comment]
+1 for this.
Tony, can you rebase and merge it, please?

**Comment by tonytheodore** [comment]
Rebased and merged - apologies. Apart from running out of time, I messed up my git config with proxy settings...grrrr

**Pull request merged**
