### PR TITLE
nsis: update to 3.01

### PR DESCRIPTION
**Pull request by starius**

### CODE REVIEW

**Comment by dl5rcw** [comment]
@starius - I recently started a 3.0 patch, but didn't even push without testing. It is now already outdated by yours, which is great! I will jump to yours, include in our beta-environment on Thursday, getting the results of all our builds by Monday.

**Comment by dl5rcw** [comment]
@starius First feedback: your update to 3.01 compiles fine. Our nsis script is rather hughe, taking advantage of many plugins. Besides some changes, which create warnings, 3.01 seems to have some severe issues left (at nsis side).
```
warning: "${LANG_ENGLISH}" is not a valid language id, using language id 1033! (nsis/nsis_main.nsi:152)
LicenseData: wchar_t conversion failed!

```
another issue is the System::Int64Op issue when using the /share/mxe/usr/bin/x86_64-w64-mingw32.shared-makensis version. This is probably due to the compiler option 
```
        $(if $(findstring x86_64-w64-mingw32,$(TARGET)),\
            SKIPPLUGINS='System') \

```
in nsis.mk

**Conclusion:** besides wchar_t conversion, which seems nsis related (quick google search, it seems to be known), our builds behaves just as the previous nsis.mk version (System plugin was not built either). Hope we get this working in 3.01 or 3.0[n]. I guess there will be a 3.02 and 3.03 following in shorter periods in 2017. Hence, **I propose to accept the pull request** of @starius to get us closer to the nsis project and experience improvements to the next iterations. **Good work, thanks starius!**
Any ideas on the System Plugin? GetSize is often used in nsis installers (e.g. writing size of application to the registry) and relies on System Plugin.

**Comment by pavelvat** [comment]
I have tested nsis 3.01 with eiskaltdcpp:
32-bit work correctly:
```
$ i686-w64-mingw32.shared-makensis EiskaltDC++.nsi 
Processing config: /home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/etc/nsisconf.nsh
Processing script file: "EiskaltDC++.nsi" (UTF8)

Processed 1 file, writing output (x86-ansi):

Output: "/home/pavel/builds/eiskaltdcpp/windows-release/64-bit/shared/EiskaltDC++-2.4.0-x86_64.exe"
Install: 5 pages (320 bytes), 2 sections (65584 bytes), 1538 instructions (43064 bytes), 2279 strings (96474 bytes), 21 language tables (6678 bytes).
Uninstall: 3 pages (256 bytes), 1 section (32792 bytes), 250 instructions (7000 bytes), 1133 strings (33271 bytes), 21 language tables (5922 bytes).
Datablock optimizer saved 316972 bytes (~0.4%).

Using lzma (compress whole) compression.

EXE header size:              176640 / 74752 bytes
Install code:                          (163408 bytes)
Install data:                          (68242174 bytes)
Uninstall code+data:                   (260423 bytes)
Compressed data:            17396207 / 68666005 bytes
CRC (0xE7C84FD1):                  4 / 4 bytes

Total size:                 17572851 / 68740761 bytes (25.5%)
```
64-bit still doesn't work:
```
$ x86_64-w64-mingw32.shared-makensis EiskaltDC++.nsi 
Processing config: /home/pavel/builds/mxe/usr/x86_64-w64-mingw32.shared/etc/nsisconf.nsh
Processing script file: "EiskaltDC++.nsi" (UTF8)
Plugin not found, cannot call nsDialogs::Create
Error in macro MUI_FUNCTION_WELCOMEPAGE on macroline 7
Error in macro MUI_PAGEDECLARATION_WELCOME on macroline 18
Error in macro MUI_PAGE_WELCOME on macroline 6
Error in script "EiskaltDC++.nsi" on line 54 -- aborting creation process
```
It is looking like old problem #1354 (with nsis 2.51) with processing 64-bit plugin-dlls from directory ```mxe/usr/x86_64-w64-mingw32.shared/share/nsis/Plugins/x86-ansi```

**Comment by dl5rcw** [comment]
@pavelvat is right. From my understanding, Version 3 gives a better chance to have that resolved than 2.xx 
Things obviously did not get worse - so for this case and regarding the ongoing development in 3.xx, I would still propose to pull the update of @starius. It seems smarter to stay close to the ongoing development branch.

**Pull request merged**
