### PR TITLE
nonetwork: print message from replaced functions

### PR DESCRIPTION
**Pull request by starius**
See https://github.com/mxe/mxe/issues/1269

### CODE REVIEW

**Comment by tonytheodore** [comment]
Nice!

**Comment by pavelvat** [comment]
http://pastebin.com/E4ekNsUR
```
  % Total    % ReceDon't use network from MXE build rules!
```

Maybe one more "\n"?:
```
static void print_message() {
    fprintf(stderr, "\nDon't use network from MXE build rules!\n");
}
```

**Comment by tonytheodore** [comment]
Indeed. Some asterisks would also help with parsing log output - I only checked this in an interactive session.

**Comment by starius** [comment]
I think, calls of `fflush` should be added as well:
```c
static void print_message() {
    fflush(stderr);
    fprintf(stderr, "\nDon't use network from MXE build rules!\n");
    fflush(stderr);
}

**Comment by pavelvat** [comment]
>I think, calls of fflush should be added as well

Ok: http://pastebin.com/Yn0ejyfv

**Pull request merged**
