### PR TITLE
Secure URLs

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vog** [comment]
Related issue: #1909

**Comment by vog** [comment]
This looks very good to me, but I'd prefer to have another person have a look at it, just to be sure.

**Comment by vszakats** [comment]
Sadly, the Lua code requires a new approach as the current one doesn't support security. Not a Lua expert here, so I'm not sure how to do this, especially on Windows.

Currently it falls back to HTTP automatically and results in this:
```
$ lua -e 'http = require "socket.http"; print(http.request("https://mxe.cc/"))'
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
	301	table: 0x7fac6ec06b40	HTTP/1.1 301 Moved Permanently
```

**Comment by vszakats** [comment]
..but, since the actual URL used there seems irrelevant (both are just examples), it can be fixed by using an HTTP example URL. I'll commit it.

**Comment by tonytheodore** [comment]
Looks good to me, thanks!

**Pull request merged**
