### PR TITLE
update mingw-w64 to 7.0.0

### PR DESCRIPTION
**Pull request by mabrand**
Results so far:

build type: static, x64
compiler: GCC 9.3.0
package builds tested:
    qt5 succeeds (all modules)
   gdb (updated to 9.1)

### CODE REVIEW

**Comment by tonytheodore** [comment]
Nice!

I've started a full build with this branch, takes about 40 hours.

**Comment by tonytheodore** [comment]
I've done a couple of fixes to master for current issues, the only expected package failures are ocaml* on all systems, and aubio/jack on darwin (issues with waf/python versions). 

Anything else is related to this update and I've started a local build which should finish in less than 20 hours.

**Comment by tonytheodore** [comment]
opus and libsodium have the same `-fstack-protector` issue as lzmq:
```diff
diff --git a/src/libsodium.mk b/src/libsodium.mk
index d38351fe..ffc97cc8 100644
--- a/src/libsodium.mk
+++ b/src/libsodium.mk
@@ -10,7 +10,8 @@ $(PKG)_DEPS     := cc

 define $(PKG)_BUILD
     cd '$(BUILD_DIR)' && '$(SOURCE_DIR)/configure' \
-        $(MXE_CONFIGURE_OPTS)
+        $(MXE_CONFIGURE_OPTS) \
+        CFLAGS='-fstack-protector'
     $(MAKE) -C '$(BUILD_DIR)' -j '$(JOBS)'
     $(MAKE) -C '$(BUILD_DIR)' -j 1 install
 endef
diff --git a/src/opus.mk b/src/opus.mk
index a16a6736..d08e5b85 100644
--- a/src/opus.mk
+++ b/src/opus.mk
@@ -22,7 +22,8 @@ endef

 define $(PKG)_BUILD
     cd '$(1)' && $(SHELL) ./configure \
-        $(MXE_CONFIGURE_OPTS)
+        $(MXE_CONFIGURE_OPTS) \
+        CFLAGS='-fstack-protector'
     $(MAKE) -C '$(1)' -j '$(JOBS)' SHELL=$(SHELL) $(MXE_DISABLE_CRUFT)
     $(MAKE) -C '$(1)' -j 1 install SHELL=$(SHELL) $(MXE_DISABLE_CRUFT)
     rm -f '$(PREFIX)/$(TARGET)'/share/man/man3/opus_*.3
```

**Comment by tonytheodore** [comment]
> the only expected package failures are ocaml* on all systems, and aubio/jack on darwin (issues with waf/python versions)

and luajit on some systems

**Comment by mabrand** [comment]
The "fix" for libzmq could use a second opinion. cppmq has the same issue. So does opus in combination with ffmpeg.

**Comment by tonytheodore** [comment]
> The "fix" for libzmq could use a second opinion

Enabling default stack protection in gcc looks promising:
```diif
diff --git a/src/gcc.mk b/src/gcc.mk
index f5888ddf..c490b820 100644
--- a/src/gcc.mk
+++ b/src/gcc.mk
@@ -41,6 +41,7 @@ define $(PKG)_CONFIGURE
         --disable-win32-registry \
         --enable-threads=$(MXE_GCC_THREADS) \
         $(MXE_GCC_EXCEPTION_OPTS) \
+        --enable-default-ssp \
         --enable-libgomp \
         --with-gmp='$(PREFIX)/$(BUILD)' \
         --with-isl='$(PREFIX)/$(BUILD)' \
```

**Comment by tonytheodore** [comment]
Oddly, default stack protection works for opus and libsodium, but not libzmq and cppzmq.

**Comment by tonytheodore** [comment]
There's a workaround for libsodium.pc file that makes the libzmq and cppzmq tests clearer, the build rules seem to be fixed with setting default windows versions and stack protector.

WIP here https://github.com/tonytheodore/mxe/commits/mabrand-mingw7

**Comment by tonytheodore** [comment]
Static builds seem to be mostly fixed by tweaking *.pc files, the shared builds seem to require more elaborate tweaking of configure/cmake invocation and detection.

I'm leaning towards adding `-lssp_nonshared -lssp`[1] to the standard libs in order to mimic glibc behaviour.


[1] from gcc's dumpspecs (same for both static and shared):
```
*link_ssp:
%{fstack-protector|fstack-protector-all|fstack-protector-strong|fstack-protector-explicit:-lssp_nonshared -lssp}
```

**Comment by mabrand** [comment]
Hi Tony, I have added your commits and rebased the branch on current master.  The static build succeeds using gcc9.

**Comment by tonytheodore** [comment]
Hi @mabrand, I can't see my previous commits in this rebase - however, I don't think those compatibility workarounds are necessary if we set the [gcc/cmake defaults](https://github.com/tonytheodore/mxe/commit/cc776c0907c55d01d6a7430c7c4dbc3ad97d1de0). 

[GCC spec files](https://gcc.gnu.org/onlinedocs/gcc/Spec-Files.html) are very quirky and only seem to work in two scenarios:
  - create default file and modify in place
  - use [wrapper](https://github.com/tonytheodore/mxe/commit/0960b9f8892d77fdb1b828b7183fb1b1982926ff#diff-d30e6bdb5660ed818ad8ed6aa4a177e3R159) and specify `-specs=`

My new WIP is https://github.com/tonytheodore/mxe/commits/mabrand-mingw7-rebase that takes the former approach and works with reverting the `*zmq` packages - I'm testing that now with static and shared builds (but native darwin is failing with glib - of course).

Modern versions of gcc may enable stack-protector by default, but I want gcc5 to be the last "default" version before [replacing the plugin](https://github.com/mxe/mxe/commit/422eab6f0a79172d0391baebe8b4cebd83f663b2#diff-a72b13f48ae94508d8b863f210a60122R28-R34) with proper target support.

**Comment by tonytheodore** [comment]
With some other unrelated fixes, testing i686 only, it looks like there's only a few packages directly affected by this update.

mingw-w64 v7 issues:
libdnet-i686-w64-mingw32.static
plibc-i686-w64-mingw32.shared
plibc-i686-w64-mingw32.static
wget-i686-w64-mingw32.shared

darwin issues:
aubio-i686-w64-mingw32.static
jack-i686-w64-mingw32.shared

freeglut update:
cegui-i686-w64-mingw32.static
opencsg-i686-w64-mingw32.static

unknown issues:
qt-i686-w64-mingw32.shared
qt-i686-w64-mingw32.static
qtwebkit-i686-w64-mingw32.shared
vtk-i686-w64-mingw32.shared
vtk-i686-w64-mingw32.static

I think it's probably close enough to merge.

**Comment by tonytheodore** [comment]
> freeglut update:
cegui-i686-w64-mingw32.static
opencsg-i686-w64-mingw32.static

Those are fixed using gcc9, but these fail:
agg-i686-w64-mingw32.static
db-i686-w64-mingw32.shared

The other issues remain. I've rebased and updated my [WIP to remove the *zmq compatibility changes](https://github.com/tonytheodore/mxe/commits/mabrand-mingw7-rebase).

**Comment by tonytheodore** [comment]
vtk fixed https://github.com/tonytheodore/mxe/commit/2d39fa69239faf99d7707524164b3b881c00f391

**Comment by tonytheodore** [comment]
libdnet and plibc [fixed for default win7](https://github.com/tonytheodore/mxe/commit/0f3aaf2048dc03076a1b6346da0c6908990688e2)

**Comment by tonytheodore** [comment]
qtwebkit is also failing on current master after the qt 5.15 update

**Comment by mabrand** [comment]
> qtwebkit is also failing on current master after the qt 5.15 update

Do you think this could be the solution?
https://github.com/mxe/mxe/pull/2507/commits/e87a8b636ea11708260d5f39df7a621f0ce84e99

**Comment by tonytheodore** [comment]
Yes, `fullscreenvideohandler` rings a bell.

Why can't I see that commit? It looks like it's in the mxe/mxe tree, but I don't have it locally nor can I see it in https://github.com/mxe/mxe/commits/master.

**Comment by tonytheodore** [comment]
Ignore that, it's here https://github.com/Vitozz/mxe/commits/master

This update is just about ready to merge, I'm doing some final tests with the win7 default removed (causes more problems than it solves).

**Comment by tonytheodore** [comment]
>> qtwebkit is also failing on current master after the qt 5.15 update

>Do you think this could be the solution?
e87a8b6

That did the trick! https://github.com/mxe/mxe/commit/6376e91ac46d03afb4e8c05989865e31ce20867d

**Comment by tonytheodore** [comment]
The [previous update](https://github.com/mxe/mxe/commit/8ed36bf81f40a37b4e7b5568a9c5c5b2cbf620ef) left the patch in a state where it was [applying the same changeset twice with an incorrect commit message](https://github.com/mxe/mxe/blob/8ed36bf81f40a37b4e7b5568a9c5c5b2cbf620ef/src/mingw-w64-1.patch).

Otherwise, this good to merge.

**Pull request merged**
