### PR TITLE
multiCall + case insensitivity

### PR DESCRIPTION
**Pull request by dl5rcw**
now there is just a single commit including multiCall function for the requested option and ifind for more case insensitivity.

### CODE REVIEW

**Comment by pavelvat** [comment]
???
@dl5rcw You removed my changes https://github.com/mxe/mxe/pull/1255

**Comment by dl5rcw** [comment]
@pavelvat I am not familiar with git (yet) and was asking for help how to merge. I finally lost my repo and had to recreate it from scratch. I was not even aware that there were changes. Be assured, this was not meant to be offensive. Can you add your changes (always like to see things improving). I would appreciate a guiding hand though for what I need to do then.

**Comment by pavelvat** [comment]
Work from ```root``` user is very bad practice. If you still want to work as ```root``` then set your user name and email address:
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity

>I am not familiar with git (yet)

Git have excellent documentation on official site:
https://git-scm.com/book/en/v2

>I finally lost my repo and had to recreate it from scratch.

If you replaced the file ./copydlldeps.sh by your reserve copy this mean that you removed my changes from commit 2db02c13183c002476c4d2eda92ae3e106f47d87.

After you did clone repo:
```
git clone https://github.com/dl5rcw/mxe.git
```
you need manually add your old changes from backup to file ```tools/copydlldeps.sh```.

**Comment by pavelvat** [comment]
>I would appreciate a guiding hand though for what I need to do then.

For example:
Currently:
```
git log --pretty=format:"%h - %an, %ar : %s"
704ebff - root, 22 hours ago : multiCall + case insensitivity
5366608 - MXEBot as Travis CI, 2 days ago : Update versions.json & build-matrix.html
f117a71 - Mark Brand, 2 days ago : vmime: update
40e481f - MXEBot as Travis CI, 3 days ago : Update versions.json & build-matrix.html
07b3cb0 - Mark Brand, 3 days ago : curl: update
3445107 - Tony Theodore, 5 days ago : Merge pull request #1270 from LuaAndC/nonetwork-print-message
726d6af - MXEBot as Travis CI, 5 days ago : Update versions.json & build-matrix.html
3055443 - mabrand, 5 days ago : Merge pull request #1268 from pavelvat/add-qtsparkle
dae6af8 - Pavel Vatagin, 5 days ago : add package qtsparkle
a295fae - Boris Nagaev, 6 days ago : Merge pull request #1255 from pavelvat/copydlldeps.sh-case-insensitive
2dd817b - Boris Nagaev, 6 days ago : nonetwork: print message from replaced functions
2db02c1 - Pavel Vatagin, 13 days ago : copydlldeps.sh: fix #1226 (case insensitive)
```


1)reset your git repo to original state (remove your last commit)
```
git reset --hard HEAD~1
```
after this:
```
git log --pretty=format:"%h - %an, %ar : %s"
5366608 - MXEBot as Travis CI, 2 days ago : Update versions.json & build-matrix.html
f117a71 - Mark Brand, 2 days ago : vmime: update
40e481f - MXEBot as Travis CI, 3 days ago : Update versions.json & build-matrix.html
07b3cb0 - Mark Brand, 3 days ago : curl: update
3445107 - Tony Theodore, 5 days ago : Merge pull request #1270 from LuaAndC/nonetwork-print-message
726d6af - MXEBot as Travis CI, 5 days ago : Update versions.json & build-matrix.html
3055443 - mabrand, 5 days ago : Merge pull request #1268 from pavelvat/add-qtsparkle
dae6af8 - Pavel Vatagin, 5 days ago : add package qtsparkle
a295fae - Boris Nagaev, 6 days ago : Merge pull request #1255 from pavelvat/copydlldeps.sh-case-insensitive
2dd817b - Boris Nagaev, 6 days ago : nonetwork: print message from replaced functions
2db02c1 - Pavel Vatagin, 13 days ago : copydlldeps.sh: fix #1226 (case insensitive)
```

2)manually add your old changes from backup to file ```copydlldeps.sh```
3)commit your changes:
```
git commit -a -m "multiCall + case insensitivity"
```
4)replace old state in origin:
```
git push origin master -f
```

**Comment by dl5rcw** [comment]
@pavelvat Thanks, your step-by-step was very helpful. I hope I did everything right. vimdiff was my friend here and I also added name and eMail. Thanks to that point.
Hope it is OK now, your part is included and I was running my projects last night, all worked fine. Can you confirm?
I just see that there are now two commits that appeared up there. Was that to be expected? What did I do wrong and how can I fix that without messing up again?

**Comment by pavelvat** [comment]
???
https://github.com/mxe/mxe/pull/1275/files my changes from 2db02c1 still removed.

> I hope I did everything right. 

Unfortunately no.

> I think there was an unnecessary git pull that created a mess. 

You do not have to do ```git pull```. 
Main idea:
1)reset last commit in local git repo: 
```git reset --hard HEAD~1```
2)make new commit in local git repo
```git commit -a -m "my changes"```
3)replace your remote git repo state (https://github.com/dl5rcw/mxe) by your local git repo state (option ```-f``` is necessary):
```git push origin master -f```

>Can you help me out a very last time to not mess up again, please? I think it is the squash thing that I was reading in the manual.

1)Your current state: ```git log --pretty=format:"%h - %an, %ar : %s"```:
```
d824f97 - Lars, 3 hours ago : Update copydlldeps.sh
58fe9b9 - Lars, 3 hours ago : multiCall + case insensitivity
631756c - Lars, 3 hours ago : multiCall + case insensitivity
704ebff - root, 3 days ago : multiCall + case insensitivity
5366608 - MXEBot as Travis CI, 4 days ago : Update versions.json & build-matrix.html
...
```
2)reset your git repo state to commit 5366608
```
git reset --hard 5366608
```
Your current state: ```git log --pretty=format:"%h - %an, %ar : %s"```:
```
5366608 - MXEBot as Travis CI, 4 days ago : Update versions.json & build-matrix.html
f117a71 - Mark Brand, 4 days ago : vmime: update
40e481f - MXEBot as Travis CI, 5 days ago : Update versions.json & build-matrix.html
07b3cb0 - Mark Brand, 5 days ago : curl: update
3445107 - Tony Theodore, 7 days ago : Merge pull request #1270 from LuaAndC/nonetwork-print-message
...
```
3)manually (taking into account my changes 2db02c1) add your old changes from backup to file ```copydlldeps.sh```
4)commit your changes:
```
git commit -a -m "multiCall + case insensitivity"
```
5)replace your remote git repo state (https://github.com/dl5rcw/mxe) by your local git repo state (option ```-f``` is necessary):
```git push origin master -f```

**Comment by dl5rcw** [comment]
@pavelvat  - I am pretty sure that this file now in my mxe fork contains all elements. Can you please have a look at https://github.com/dl5rcw/mxe/blob/master/tools/copydlldeps.sh and confirm that there is all that is needed? If you state okay, I will finally offer in a pull request, but not before :) 
I also updated the copydlldeps.md file
Thanks again for your help!

**Comment by pavelvat** [comment]
>and confirm that there is all that is needed

Everything is fine.

**Pull request closed without merging**
