### PR TITLE
upgrade qt5 modules to 5.8.0

### PR DESCRIPTION
**Pull request by mabrand**
All the qt5 modules build, both static and shared, except qtwebkit.

In qtbase-1-fixes.patch, Change-Id: I05b036366bd402e43309742412bcf8ca91fe125f for fontconfig might not be right. That's just a guess.

**qtwebkit**
Something is still wrong with qtwebkit. I haven't been able to build qtwebkit 5.8.0 or 5.7.1 using qt 5.8.0. Maybe some has an idea about this?

[qtwebkit_x86_64-w64-mingw32.shared.zip](https://github.com/mxe/mxe/files/737848/qtwebkit_x86_64-w64-mingw32.shared.zip)

### CODE REVIEW

**Comment by tonytheodore** [comment]
I can see the same issue with qtwebkit, it's strange as the first build always fails (at `make qmake_all`) but then continues successfully with a retry. I'm guessing it's some artefacts in the source directory as an out of source build works. Also no longer need the other tweaks and `qtquickcontrols` can be enabled as a dep.

```diff
diff --git a/src/qtwebkit.mk b/src/qtwebkit.mk
index ad2c8ff..f4bac41 100644
--- a/src/qtwebkit.mk
+++ b/src/qtwebkit.mk
@@ -9,16 +9,14 @@ $(PKG)_CHECKSUM := 79ae8660086bf92ffb0008b17566270e6477c8fa0daf9bb3ac29404fb5911
 $(PKG)_SUBDIR    = $(subst qtbase,qtwebkit,$(qtbase_SUBDIR))
 $(PKG)_FILE      = $(subst qtbase,qtwebkit,$(qtbase_FILE))
 $(PKG)_URL      := http://download.qt.io/community_releases/5.8/5.8.0-final/$($(PKG)_FILE)
-$(PKG)_DEPS     := gcc qtbase qtmultimedia sqlite
+$(PKG)_DEPS     := gcc qtbase qtmultimedia qtquickcontrols sqlite

 define $(PKG)_UPDATE
     echo $(qtbase_VERSION)
 endef

 define $(PKG)_BUILD_SHARED
-    # looks for build tools with .exe suffix and tries to use win_flex
-    $(SED) -i 's,\.exe,,' '$(1)/Tools/qmake/mkspecs/features/functions.prf'
-    cd '$(1)' && mkdir -p .git && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' FLEX=flex
-    $(MAKE) -C '$(1)' -j '$(JOBS)'
-    $(MAKE) -C '$(1)' -j 1 install
+    cd '$(BUILD_DIR)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' '$(SOURCE_DIR)'
+    $(MAKE) -C '$(BUILD_DIR)' -j '$(JOBS)'
+    $(MAKE) -C '$(BUILD_DIR)' -j 1 install
 endef
```

**Comment by tonytheodore** [comment]
qtofficeopenxml is broken on shared builds: https://gist.github.com/tonytheodore/d064487b0e97a0809d83bbe3de5499b1

**Comment by mabrand** [comment]
I also found that the qtwebkit build finished successfully on a second make, at least when I did it manually with: 
```
source tools/mxe-activate
cd tmp-qtwebkit/qtwebkit
make
```
Did that work for you from inside the qtwebkit.mk? If so, do you want to just add a second make call there?

**Comment by tonytheodore** [comment]
> If so, do you want to just add a second make call there?

The retry does work, both within qtwebkit.mk and manually; the out-of-source consistently works first time. I'd rather leave retries for inexplicable hardware resource issues (not #1462 #1474 #1608).

The other benefit of out-of-source builds (`$(BUILD_DIR)`,`$(SOURCE_DIR)`) is workflow:
```
make qtwebkit qtwebkit_SOURCE_TREE=gits/qtwebkit...
```

**Comment by mabrand** [comment]
Thanks Tony for the tips. qtwebkit and qtofficeopenxml build fine now.

**Comment by tonytheodore** [comment]
Thanks! Build succeeds on all four targets (+ i686-w64-mingw32.static.posix) and downstream packages.

I'm not sure how to check the fontconfig changes. If I build examples/widgets/painting/fontsampler/ and remove the `-lfontconfig`, the example builds and runs. The same happens with 5.7.1 so I think this is good to merge.

**Pull request merged**
