### PR TITLE
Clean cflags v3

### PR DESCRIPTION
**Pull request by mabrand**
Better approach to cleaning up cflags proposed by Tony.

### CODE REVIEW

**Comment by mabrand** [comment]
Qtbase builds successfully with these changes.

**Comment by tonytheodore** [comment]
All packages build with the exception of `gd`, which is somehow picking up a native lib path (most likely from `freetype` https://github.com/mxe/mxe/issues/1789#issuecomment-309369170).

Should `PKG_CONFIG_SYSROOT_DIR=/` be removed from `qtbase` and/or should `PKG_CONFIG_SYSROOT_DIR` be set correctly in the wrapper?

**Comment by mabrand** [comment]
We cannot easily remove PKG_CONFIG_SYSROOT_DIR=/ from qtbase.mk, because the Qt build system assumes that PKG_CONFIG_SYSROOT_DIR must be set for cross-compiling. However, when we run pkg-config, we don't want PKG_CONFIG_SYSROOT_DIR to be set because pkg-config prepends it to the SYSTEM_INCLUDE_PATH and SYSTEM_LIBRARY_PATH. The extra leading '/' in turn prevents these paths from being stripped from --cflags and -libs output.

**Comment by tonytheodore** [comment]
Okay, this looks good to me then - thanks!

**Pull request merged**
