### PR TITLE
gcc plugin: rename gcc52 to gcc5 and update 5.2.0 --> 5.3.0

### PR DESCRIPTION
**Pull request by tonytheodore**
See https://github.com/mxe/mxe/issues/964#issuecomment-170358288

A single 5 series package will be easier to maintain. If anyone wants to use a specific version, they can use this as a template and maintain it locally.

### CODE REVIEW

**Comment by starius** [comment]
See also https://github.com/mxe/mxe/issues/1166
I'll build `libical` from scratch to make sure that it is an ordering issue.

**Comment by starius** [comment]
`libical` was built successfully for `i686-w64-mingw32.static`.

**Comment by tonytheodore** [comment]
So is it `isl`, wheezy, or ordering?

**Comment by starius** [comment]
Let me built it again, without updating `isl`.

**Comment by starius** [comment]
`libical` was built successfully with old `isl` (0.14). It should be an ordering issue.

**Comment by tonytheodore** [comment]
Rebased and merged: https://github.com/mxe/mxe/commit/eae41ccbfd983312b99cbf1461d6217b701a57b0

**Pull request closed without merging**
