### PR TITLE
hyperscan: fix build where native SSSE3 detection fails

### LINKED ISSUE #1997: Hyperscan build is failing when making qt5base-dev
The hyperscan make fails in a recently installed MXE, for both Windows build targets.
I see that there is a recent patch for something in this area, but have no idea how to install it, or if it is relevant to this issue.

My underlying issue is the failure of Cmake to  understand qt5_wrap_ui, and I have the impression that installing qt5base-dev might be the solution to this.

### PR DESCRIPTION
**Pull request by tonytheodore**
closes #1997

### CODE REVIEW

**Comment by Cenkron** [comment]
It seems to have had no effect.  Let me verify I did the right thing for this test:
In my mxe root directory, I did a "git pull" followed by a "make", and retrieved the log which was properly dated, so I know it retried the build.

[hyperscan_i686-w64-mingw32.static.posix.txt](https://github.com/mxe/mxe/files/1535438/hyperscan_i686-w64-mingw32.static.posix.txt)

**Comment by tonytheodore** [comment]
It isn't merged yet so you need to do something like:
```
git checkout -b tonytheodore-hyperscan-arch master
git pull https://github.com/tonytheodore/mxe.git hyperscan-arch
```
and then `make` again. The commands above are usually copy-and-paste ready in the `command line instructions` on every PR.

**Comment by Cenkron** [comment]
I tried to do this, but it is asking for your username and password.

**Comment by Cenkron** [comment]
I was revisiting this, and I realize I have no idea where the command line instructions you mentioned are.

**Comment by tonytheodore** [comment]
Sorry, the instructions are near the merge button which is only visible to committers.

You haven't set up [any ssh keys](https://github.com/Cenkron.keys) so the login details are just your normal credentials you use for github.

You could try:
```
curl -L https://github.com/mxe/mxe/pull/2000.patch | git am
#or
curl -L https://github.com/mxe/mxe/pull/2000.diff | patch -p1
```
in your new branch.

**Comment by Cenkron** [comment]
I finally got back to where I could test your patch.  It was successful; hyperscan is now building properly.
Thanks.

**Pull request merged**
