### PR TITLE
allow non-default exception handling targets

### PR DESCRIPTION
**Pull request by tonytheodore**
See #1411 and #1559 allows variants like:
```
i686-w64-mingw32.static.posix.dw2
i686-w64-mingw32.static.dw2
x86_64-w64-mingw32.shared.win32.sjlj
etc.
```

### CODE REVIEW

**Comment by starius** [comment]
Can you add this to https://github.com/mxe/mxe/blob/master/README.md#supported-toolchains and index.html, please?

**Comment by starius** [comment]
The pull request fails to apply as a patch.
Can you rebase it, please?

**Comment by tonytheodore** [comment]
Added to docs, fixed typo in message, and rebased.

**Comment by starius** [comment]
Failure in apr_i686-w64-mingw32.static.posix.dw2:
https://gist.github.com/4a1b7b598aea32e84daedba8ef1e7639

**Comment by tonytheodore** [comment]
I see the same for apr with `i686-w64-mingw32.static.posix.dw2`, it's most likely related to *posix* as `i686-w64-mingw32.static.dw2` succeeds.

**Comment by tonytheodore** [comment]
[apr fixed](https://github.com/mxe/mxe/pull/1664/commits/1020d040db43dc10ee1f37a8377030c4a124beaf)

**Comment by tonytheodore** [comment]
[libmysqlclient fixed](https://github.com/mxe/mxe/pull/1664/commits/bf6a78224b8d6a4958e2221d3ccc97056d87feeb) - causes downstream breakage of gdal.

**Comment by starius** [comment]
For `i686-w64-mingw32.static.dw2` and `x86_64-w64-mingw32.shared.win32.sjlj` all packages including plugins `apps`, `luarocks` and `go` were built.

**Pull request merged**
