### PR TITLE
Upgrade GDAL to 3.6.2

### PR DESCRIPTION
**Pull request by brodieG**
# Background

This replaces #2943 because gdal recalled 3.6.0 due to [major bugs](https://github.com/OSGeo/gdal/blob/v3.6.1/NEWS.md).

At @mabrand's request I split as much of the original PR (#2918) into separate PRs as I could.  The following PRs must be applied before this one:

* #2935 
* #2941 
* ~~#2942~~ (seemingly obviated as of 4/2023) 
* #2945 
* #2946 

The remaining changes in this PR need to be a applied together as all the packages involved are very out of date.

# Testing

I tested building on all permutations of x86/i686 and static/shared.  Additionally I tested some of the x86 binaries (`gdalinfo.exe`, `gdaltranform.exe`) both static and shared on a windows machine (these are very basic tests that the binaries run).

I also tested builds of revdeps of the updated packages (see #2943, #2918 and other linked PRs for commentary).

# Comments on Patches

## GDAL

CMake is required to build >= 3.6.0.

Most of the patches are fixing the package auto-detection which does not work well for non-CMake packages, or for CMake packages that do not correctly EXPORT themselves. Most of the fixes involve hacking the detection code to use the pkgconfig files and generate the corresponding target_link_libraries directives.

Because the auto-detection does not work well generally, I explicitly enable packages that are wanted and tested, and do not let GDAL just auto-detect everything so GDAL does not fail for people with different untested mixes of GDAL optional dependencies.

I removed The autotools patches that are no longer needed, and some of them (openjpeg version and ogrct patches) were obviated by fixes upstream.

Minor tweaks are made to add the wmain interface to C applications in addition to C++ that already exist, as well as to those C++ applications that did not have it.

I removed a setting of MSVCRT_VERSION no longer needed.

## HDF5

We've taken the upgrade from [Octave][5], which among other things switches to cmake.  There are several changes from the current build, the most salient outlined next.

Most of the octave patch is the auto-generated H5init.c and H5lib_settings.c files which previously were in a separate patch file (`hdf5-2-platform-detection.patch`).  I've kept them in one file as that's how mxe-patch-tool does it, and to make any future transfers of patches from mxe-octave simpler.

Some revdeps not needed for GDAL fail, but that is the case on the MXE master branch too (see "GDAL Dependency Reverse Dependency Section").

## netcdf

There seems to be some confusion between CMake target and library name, which leads to the nc-config file using "-static"/"-shared" suffixes.  If I knew CMake better (I never dealt with it previously) maybe I could come up with a correct way to do this, but instead I just hack the nc-config file.  The problem seems to be `netcdf` is using target names instead of library names, but I don't know enough (or really almost any) CMake to confidently propose a patch upstream.

netcdf themselves also try to [fix this with a hack][12], but the hack does not work for our particular cross set-up because the target names are not namespaced.

# Other

Thanks for your work building and keeping MXE up and running.  Let me know if there is anything else I can do to make this merge easier.  I realize it's very large and a lot of work for you to review.  Unfortunately, the beastly nature of gdal and the very long time span since it was last updated make it a hard problem.

[1]: https://github.com/mxe/mxe/pull/2792
[2]: https://github.com/mxe/mxe/pull/2873
[3]: https://github.com/OSGeo/PROJ/issues/1767#issuecomment-561616040
[4]: https://github.com/mxe/mxe/pull/2768#issuecomment-1086887671
[5]: https://hg.octave.org/mxe-octave/file/tip/src/hdf5.mk
[6]: https://github.com/mxe/mxe/blob/47ec1dfb41d0fd40d7eb61e7759f33aec4a2aa59/src/hdf5.mk#L42
[7]: https://forum.hdfgroup.org/t/cross-compiling-for-windows/6735/20
[8]: https://forum.hdfgroup.org/t/cmake-parallel-hdf5-config-scripts-references-hdf-hdf-shared/4605/12
[9]: https://github.com/tbeu/matio/issues/78
[11]: https://github.com/pgbackrest/pgbackrest/issues/1323
[12]: https://github.com/Unidata/netcdf-c/commit/6b828cbae084a6acb1d6e51288d93f4a080f5664
[13]: https://github.com/mxe/mxe/pull/2873#issuecomment-1228288915
[14]: https://github.com/gwaldron/osgearth/issues/1455
[15]: https://gdal.org/download.html#build-requirements
[16]: https://proj.org/install.html#build-requirements

### CODE REVIEW

**Comment by brodieG** [comment]
@mabrand anything else I can do to facilitate the review of this PR?

**Comment by brodieG** [comment]
@mabrand @tonytheodore ping?  I realize this creates no obligation for you whatsoever, but it was quite the task to get from the 5 year old version currently at MXE (2.2.4) to this one, particularly for something as dependency laden as GDAL.  It would really be a shame to have all this go to waste.  I know both of you have shown some interest in this in the past, and I thank you for the review and merging of several of the component PRs you have done already.

**Comment by kalibera** [comment]
I would be grateful if this could be incorporated. We are using the changes in Rtools43 (for the upcoming release of R 4.3) and for us smaller the differences from upstream MXE the better, that makes the maintenance easier. I believe the benefit also works the other way: MXE (the subset used by R) gets additional testing via R packages and the R community. Particularly the geospatial packages are challenging to maintain, as they have frequent releases and frequent changes, they are also the biggest source of differences between Rtools and upstream MXE. Thanks!

**Comment by mabrand** [comment]
Would like to merge this very soon. Just a few prerequisites remaining such as https://github.com/mxe/mxe/pull/2935.

**Comment by brodieG** [comment]
Thanks for looking at this again.  Note #2942 does not appear to be needed anymore.

**Comment by mabrand** [comment]
The other commits are merged, but now this one has a merge conflict. Could you take a look at this?

**Comment by brodieG** [comment]
Ah yes when I tweaked the src/gdal.mk in #2935 I missed that I introduced a merge conflict.  Looks like this is good to go now.  I tested the build on x64 shared/static and it built.

**Pull request merged**
