### PR TITLE
ffmpeg: update to 3.0

### PR DESCRIPTION
**Pull request by avih**

### CODE REVIEW

**Comment by starius** [comment]
Please add "disable libvo-aacenc" to the commit message.

**Comment by avih** [comment]
> Please add "disable libvo-aacenc" to the commit message.

Already did in a force-push. Refresh your page.

**Comment by TimothyGu** [comment]
You should also remove the libvo-aacenc dependency.

**Comment by avih** [comment]
> You should also remove the libvo-aacenc dependency.

Already did in the original commit, and added also to the commit message a minute later.

**Comment by TimothyGu** [comment]
No, I meant the dependency in the DEPS list, not just in te configure line.

**Comment by avih** [comment]
Removed vo-aacend from the DEPS as well, and tested that it builds.

Note that I didn't clean before testing as this would take annoyingly long time. We can revisit the patch if someone reports that it fails.

**Comment by starius** [comment]
> Note that I didn't clean before testing as this would take annoyingly long time.

You can manually "remove" vo-aacenc by removing the following files:

```
usr/i686-w64-mingw32.static/include/vo-aacenc/cmnMemory.h
usr/i686-w64-mingw32.static/include/vo-aacenc/voAAC.h
usr/i686-w64-mingw32.static/include/vo-aacenc/voAMRWB.h
usr/i686-w64-mingw32.static/include/vo-aacenc/voAudio.h
usr/i686-w64-mingw32.static/include/vo-aacenc/voIndex.h
usr/i686-w64-mingw32.static/include/vo-aacenc/voMem.h
usr/i686-w64-mingw32.static/include/vo-aacenc/voType.h
usr/i686-w64-mingw32.static/installed/vo-aacenc
usr/i686-w64-mingw32.static/lib/libvo-aacenc.a
usr/i686-w64-mingw32.static/lib/libvo-aacenc.la
usr/i686-w64-mingw32.static/lib/pkgconfig/vo-aacenc.pc
```

You can find files of a package in [MXE binary distribution](http://pkg.mxe.cc/repos/list/mxe-i686-w64-mingw32.static/).

Note that this data may be out-dated, because it is based on commit 8aa5ccc123b429c59b453b7be2fce9ef3bea678a

**Comment by avih** [comment]
Looks OK.
```
$ rm -rf usr/i686-w64-mingw32.static/include/vo-aacenc
$ rm usr/i686-w64-mingw32.static/lib/libvo-aacenc.*
$ rm usr/i686-w64-mingw32.static/lib/pkgconfig/vo-aacenc.pc
$ rm usr/i686-w64-mingw32.static/installed/vo-aacenc
$ rm usr/i686-w64-mingw32.static/installed/ffmpeg
$ rm pkg/ffmpeg-3.0.tar.bz2

$ make ffmpeg
[download]  ffmpeg
[build]     ffmpeg     i686-w64-mingw32.static
[done]      ffmpeg     i686-w64-mingw32.static       370224 KiB     2m58.058s

$ wine usr/i686-w64-mingw32.static/bin/ffmpeg.exe
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.3 (GCC)
  configuration: --cross-prefix=i686-w64-mingw32.static- --enable-cross-compile
  --arch=i686--target-os=mingw32 --prefix=/home/user/dev/mxe/usr/i686-w64-mingw32.static
  --enable-static--disable-shared --yasmexe=i686-w64-mingw32.static-yasm --disable-debug
  --enable-memalign-hack --disable-pthreads --enable-w32threads --disable-doc
  --enable-avresample --enable-gpl --enable-version3 --extra-libs=-mconsole
  --enable-avisynth --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b
  --enable-libcaca --enable-libmp3lame --enable-libopencore-amrnb
  --enable-libopencore-amrwb --enable-libopus --enable-libspeex --enable-libtheora
  --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
  --enable-libx264 --enable-libxvid
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'```

**Comment by TimothyGu** [comment]
I'm sure libvo-aacenc removal won't cause any problems (after I'm the person who committed that change in FFmpeg).

**Pull request merged**
