### PR TITLE
Update libgpg_error to 1.32, add libassuan, gpgme

### PR DESCRIPTION
**Pull request by yshurik**
With this libgpg_error update and by adding libassuan now it is possible to build and use gpgme mxe based packages.

### CODE REVIEW

**Comment by yshurik** [comment]
> Could you please squash [d88becc](https://github.com/mxe/mxe/commit/d88becc3fbd2a17d9b8e113b93455bddb0b8942f).

Done

**Comment by mabrand** [comment]
I meant to ask if you could squash it into 6c9c2c3d0cd9c73d3c59b980a2fbf4287eabc7aa, the commit that changes JOBS to 32.

**Comment by mabrand** [comment]
I think the best thing would be to organize this into 2 commits. This first should just contain the libgpg_error update, since it's logically separable. Everything thing else should be squashed into the second commit.

**Comment by yshurik** [comment]
Ok, I try to reorganize

**Comment by mabrand** [comment]
I just did it.. Thanks.

**Comment by mabrand** [comment]
Merged in 96a42362fc1f9902d01bb4bfb37aff81a2cf6f2b.

**Pull request closed without merging**
