### PR TITLE
copydlldeps.sh: fix #1226 (case insensitive)

### LINKED ISSUE #1226: problems with copydlldeps.sh
https://github.com/mxe/mxe/pull/1215
1)Case sensitivity:
```
I will now search for $alldeps
debugOut: ADVAPI32.dll
debugOut: CRYPT32.dll
debugOut: DNSAPI.dll
debugOut: GDI32.dll
debugOut: IPHLPAPI.DLL
debugOut: KERNEL32.dll
debugOut: libaspell-15.dll
debugOut: libboost_system-mt.dll
debugOut: libbz2.dll
debugOut: LIBEAY32.dll
debugOut: libfreetype-6.dll
debugOut: libgcc_s_seh-1.dll
debugOut: libglib-2.0-0.dll
debugOut: libharfbuzz-0.dll
debugOut: libiconv-2.dll
debugOut: libidn-11.dll
debugOut: libintl-8.dll
debugOut: libjsoncpp.dll
debugOut: liblua5.3.dll
debugOut: libminiupnpc.dll
debugOut: libpcre16-0.dll
debugOut: libpcre-1.dll
debugOut: libpcrecpp-0.dll
debugOut: libpng16-16.dll
debugOut: libstdc++-6.dll
debugOut: MPR.dll
debugOut: msvcrt.dll
debugOut: ole32.dll
debugOut: OPENGL32.dll
debugOut: Qt5Concurrent.dll
debugOut: Qt5Core.dll
debugOut: Qt5Declarative.dll
debugOut: Qt5Gui.dll
debugOut: Qt5Multimedia.dll
debugOut: Qt5Network.dll
debugOut: Qt5Script.dll
debugOut: Qt5Sql.dll
debugOut: Qt5Widgets.dll
debugOut: Qt5Xml.dll
debugOut: Qt5XmlPatterns.dll
debugOut: SHELL32.dll
debugOut: SSLEAY32.dll
debugOut: USER32.dll
debugOut: WINMM.dll
debugOut: WS2_32.dll
debugOut: zlib1.dll
Warning: "ADVAPI32.dll"  not found. $counter=0.
Warning: "CRYPT32.dll"  not found. $counter=0.
Warning: "DNSAPI.dll"  not found. $counter=0.
Warning: "GDI32.dll"  not found. $counter=0.
Warning: "IPHLPAPI.DLL"  not found. $counter=0.
Warning: "KERNEL32.dll"  not found. $counter=0.
Warning: "LIBEAY32.dll"  not found. $counter=0.
Warning: "MPR.dll"  not found. $counter=0.
Warning: "msvcrt.dll"  not found. $counter=0.
Warning: "ole32.dll"  not found. $counter=0.
Warning: "OPENGL32.dll"  not found. $counter=0.
Warning: "SHELL32.dll"  not found. $counter=0.
Warning: "SSLEAY32.dll"  not found. $counter=0.
Warning: "USER32.dll"  not found. $counter=0.
Warning: "WINMM.dll"  not found. $counter=0.
Warning: "WS2_32.dll"  not found. $counter=0.
```
thus openssl libs (```LIBEAY32.dll```, ```SSLEAY32.dll```) are not copied.
2)Option ```--enforce```: It does not work for more than one argument (for example,  \<path_to_mxe>/mxe/usr/\<compiler>/qt5/plugins/platforms/  \<path_to_mxe>/mxe/usr/\<compiler>/qt5/plugins/audio/  \<path_to_mxe>/mxe/usr/\<compiler>/qt5/plugins/sqldrivers/).

### PR DESCRIPTION
**Pull request by pavelvat**
Fix #1226
multiCall was added in https://github.com/mxe/mxe/pull/1227

### CODE REVIEW

**Comment by pavelvat** [comment]
This PR enabled this behavior (for example for SSLEAY32.dll): 
```
check exist files /path/to/some/dir_1/SSLEAY32.dll or /path/to/some/dir_1/ssleay32.dll
check exist files /path/to/some/dir_2/SSLEAY32.dll or /path/to/some/dir_2/ssleay32.dll
...
check exist files /path/to/some/dir_N/SSLEAY32.dll or /path/to/some/dir_N/ssleay32.dll
```
on N-step exist the file /path/to/some/dir_N/ssleay32.dll then after step-N will be searching only ssleay32.dll without searching original file name SSLEAY32.dll:
```
check exist files /path/to/some/dir_(N+1)/ssleay32.dll or /path/to/some/dir_(N+1)/ssleay32.dll
check exist files /path/to/some/dir_(N+2)/ssleay32.dll or /path/to/some/dir_(N+2)/ssleay32.dll
...
check exist files /path/to/some/dir_(N_end)/ssleay32.dll or /path/to/some/dir_(N_end)/ssleay32.dll
```
Maybe need something like this?:
```
		if [ -e "${curFolder}/${dll}" ] || [ -e "${curFolder}/`echo $dll | tr [:upper:] [:lower:]`" ]; then
			counter=$(expr $counter + 1)
			if [ -e "${curFolder}/`echo $dll | tr [:upper:] [:lower:]`" ]; then
				lower=1
				tmp_dll=$dll
				dll=`echo $dll | tr [:upper:] [:lower:]`
			fi
			if [ $opmode == "copy" ]; then
				cp -dpRxv "${curFolder}/${dll}" "$destdir"
			elif [ $opmode == "print" ]; then
				echo "found $dll in: ${curFolder}/${dll}"
			else
				echo "unknown opmode=$opmode"
			fi
			if [ lower == 1 ]; then
				tmp_dll=$dll
				dll=$tmp_dll
			fi
		fi
```

**Comment by pavelvat** [comment]
Apply behavior from https://github.com/mxe/mxe/pull/1255#issuecomment-196295854 (always check of existence ```original_name.dll``` and ```lower_name.dll```)

**Comment by starius** [comment]
Move 
```
dll=`echo $dll | tr [:upper:] [:lower:]`
```
before first `if` and rename `dll` to `lower_dll` and use `lower_dll` instead of this expression in code below. Prevent repeating the same expression in code.

One more thing. Use `tr '[:upper:]' '[:lower:]'` because plain `[` looks like [a glob pattern](https://en.wikipedia.org/wiki/Glob_%28programming%29).

**Comment by pavelvat** [comment]
Done.

**Comment by starius** [comment]
```shell
        if [ -e "${curFolder}/${dll}" ]; then
            counter=$(expr $counter + 1)
            if [ $opmode == "copy" ]; then
                cp -dpRxv "${curFolder}/${dll}" "$destdir"
            elif [ $opmode == "print" ]; then
                echo "found $dll in: ${curFolder}/${dll}"
            else
                echo "unknown opmode=$opmode"
            fi
        fi
        if [ $lower_dll != $dll ] && [ -e "${curFolder}/${lower_dll}" ]; then
            counter=$(expr $counter + 1)
            if [ $opmode == "copy" ]; then
                cp -dpRxv "${curFolder}/${lower_dll}" "$destdir"
            elif [ $opmode == "print" ]; then
                echo "found $dll in: ${curFolder}/${lower_dll}"
            else
                echo "unknown opmode=$opmode"
            fi
        fi
```

Can you avoid this repeat, please? For example, use cycle: `for the_dll in ${dll} $lower_dll; do ...`

**Comment by pavelvat** [comment]
Done.

**Comment by starius** [comment]
Thanks!

**Pull request merged**
