### PR TITLE
Update openblas to 0.3.6

### PR DESCRIPTION
**Pull request by damienrg**

### CODE REVIEW

**Comment by damienrg** [comment]
Please do not merge until #2341 is resolved and that I removed the revert commit.

**Comment by tonytheodore** [comment]
#2341 is fixed now.

What targets have you tested the openblas update on and have you tested the direct downstream pkgs (`armadillo itpp levmar opencv suitesparse`):
```
$ make show-deps-openblas
openblas upstream dependencies:
 mxe-conf ccache flex bison binutils gmp isl mingw-w64 mpfr mpc gcc patch libtool pkgconf cc cmake cmake-conf pthreads

openblas direct downstream dependents:
 armadillo itpp levmar opencv suitesparse
```

**Comment by damienrg** [comment]
I have compiled `armadillo`, `itpp`, `levmar`, and `suitesparse` with `x86_64-w64-mingw.static` target and I am currently building with `x86_64-w64-mingw.shared`.
Tell me if I need to compile with other targets and with `opencv` package.

**Comment by tonytheodore** [comment]
Perfect - shared and static targets with most downstream deps,

Thanks!

**Pull request merged**
