### PR TITLE
add package qtsparkle

### PR DESCRIPTION
**Pull request by pavelvat**
This is the last required dependency for build of Clementine.

### CODE REVIEW

**Comment by mabrand** [comment]
Wouldn't it be better to build this with Qt 5?

**Comment by pavelvat** [comment]
No. [Clementine](https://github.com/clementine-player/Clementine) still uses Qt4.

**Comment by mabrand** [comment]
It would probably be good to follow the project naming convention seen in qtserialport_qt4.

**Comment by pavelvat** [comment]
Done.

**Pull request merged**
