### PR TITLE
openblas: fix building on single-core machine

### LINKED ISSUE #2005: OpenBlas is failing to build within MXE
And just as I thought all issues were behind me, this one popped up.  For some reason, there is no log file.  Here is the error message from make:

[build]     openblas               i686-w64-mingw32.static.posix

Failed to build package openblas for target i686-w64-mingw32.static.posix!
------------------------------------------------------------
make[2]: Entering directory '/home/brian/mxe-git/tmp-openblas-i686-w64-mingw32.static.posix/OpenBLAS-0.2.20'
Makefile.system:412: *** OpenBLAS: Cannot set both USE_OPENMP=1 and USE_THREAD=0. The USE_THREAD=0 is only for building single thread version..  Stop.
make[2]: Leaving directory '/home/brian/mxe-git/tmp-openblas-i686-w64-mingw32.static.posix/OpenBLAS-0.2.20'
Makefile:687: recipe for target 'build-only-openblas_i686-w64-mingw32.static.posix' failed
make[1]: *** [build-only-openblas_i686-w64-mingw32.static.posix] Error 2
make[1]: Leaving directory '/home/brian/mxe-git'
real	0m5.993s
user	0m4.524s
sys	0m0.588s
------------------------------------------------------------
[log]      /home/brian/mxe-git/log/openblas_i686-w64-mingw32.static.posix

Makefile:687: recipe for target '/home/brian/mxe-git/usr/i686-w64-mingw32.static.posix/installed/openblas' failed
make: *** [/home/brian/mxe-git/usr/i686-w64-mingw32.static.posix/installed/openblas] Error 1

### PR DESCRIPTION
**Pull request by tonytheodore**
fixes #2005

### CODE REVIEW

**Comment by Cenkron** [comment]
Curl returned (23) Failed writing body

**Comment by Cenkron** [comment]
I am a little puzzled here.  My make that builds openblas is not related to any particular code;  it just started with a script used to fetch the needed packages into MXE and build them, to prepare MXE for my projects.,  and openblas is apparently a sub package of something else.  As far as I know I don't even need it, but I don't know for sure.
In any case, I am just running make to the MXE  git directory makefile to complete building whatever it has decided I need based on my original initializing script, as shown here:

```make MXE_TARGETS='i686-w64-mingw32.static.posix x86_64-w64-mingw32.static.posix'  MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze fftw cmake libtool mingw-w64 gcc glib libzip pcre2 libusb1 libftdi1 glibmm qtbase qtimageformats qtsvg qt5 boost check qtbase_CONFIGURE_OPTS='-no-sql-mysql'```

**Comment by Cenkron** [comment]
In any case, I am now sitting where I tried to install 2006.patch, and Curl returned the error (23) Failed writing body.  I don't know what the error means, so that seems to still be pending.  There was also a bit of personal confusion on the correct patch number between 2005 and 2006, but the last email said 2006.

**Comment by Cenkron** [comment]
Also, you mentioned a single core machine.  This is a four core machine, but I suppose VirtualBox might look like a single code machine to the guest OS.

**Comment by Cenkron** [comment]
I was able to fix my MXE git repository, and I successfully applied your patch 2006.
The rebuild of openblas is under way.

**Comment by Cenkron** [comment]
Completion of building openblas with patch 2006 is confirmed.

**Comment by tonytheodore** [comment]
Thanks, good to hear it's working.

**Pull request merged**
