### PR TITLE
Update ffmpeg and its dependencies

### PR DESCRIPTION
**Pull request by TimothyGu**
@starius, I'd love it if you could test these packages on your machine as it seems to be a LOT faster than mine :)

### CODE REVIEW

**Comment by starius** [comment]
I'm building d7581adde9a0ed40cafe2d13a4c031094ea68730 on Debian Jessie machine.

**Comment by TimothyGu** [comment]
Seems like ffmpeg builds fine here on static targets, but there are some funkiness related to libass being compiled as a static library in shared targets.

**Comment by starius** [comment]
For d7581adde9a0ed40cafe2d13a4c031094ea68730:

```
$ grep broken ~/build-17Dec2015-ffmpeg.txt                                                                        
[build-pkg]     Item is broken: x86_64-w64-mingw32.shared~libaacs
[build-pkg]     Item is broken: i686-w64-mingw32.shared~libaacs
[build-pkg]     Item is broken: x86_64-w64-mingw32.static~libaacs
[build-pkg]     Item is broken: i686-w64-mingw32.static~libaacs
[build-pkg]     Item is broken: x86_64-w64-mingw32.shared~ffmpeg
[build-pkg]     Item is broken: i686-w64-mingw32.shared~ffmpeg
```

Logs: https://gist.github.com/starius/176073771103864a7ca9

By the way, the following tool can be used to upload gists from command line: https://github.com/defunkt/gist

**Comment by TimothyGu** [comment]
Huh, didn't see that coming…

**Comment by tonytheodore** [comment]
> libass being compiled as a static library in shared targets.

It's very strange, none of the libtool workarounds work. Regenerating the configury with:
```
cd '$(1)' && $(LIBTOOLIZE) && autoreconf -fi
```
fixes both `libass` dll creation and the `ffmpeg` build, but I don't understand what changed in a minor version update. It may be best to ask the project if they changed their release process.

I didn't look at `libaacs` (patches failing to apply?) but it isn't listed in `ffmpeg` deps.

**Comment by tonytheodore** [comment]
> It may be best to ask the project if they changed their release process.

See https://github.com/libass/libass/issues/209

**Comment by tonytheodore** [comment]
`ffmpeg` is now at 2.8.4

**Comment by TimothyGu** [comment]
Rebased, libass and libaacs fixed, ffmpeg updated again.

**Comment by tonytheodore** [comment]
Thanks! Building on all four targets. [Rebased and merged] along with a note about removing `autoreconf` in next `libass` update.

**Pull request closed without merging**
