### PR TITLE
freeglut: update patch: fix pkgconfig file

### PR DESCRIPTION
**Pull request by tehnick**

### CODE REVIEW

**Comment by tehnick** [comment]
I will open PR in FreeGLUT repo once this PR will be merged.

**Comment by tonytheodore** [comment]
Great, thanks! `cegui` is still broken but that appears to be more from using outdated APIs that I imagine have been removed in this update.

**Comment by tehnick** [comment]
@tonytheodore 
I have just tested `cegui` and all is built fine for `gcc6 + x86_64-w64-mingw32.static`, `gcc6 + x86_64-w64-mingw32.shared` and `gcc-4.9 + i686-w64-mingw32.shared`.

**Comment by tonytheodore** [comment]
? It's disabled on those targets.

**Comment by tehnick** [comment]
I haven't noticed `[no-build]` tags for this package in a long build log. Sorry for misinformation.

**Comment by starius** [comment]
Seems to cause problems in https://github.com/mxe/mxe/issues/1433

**Pull request merged**
