### PR TITLE
new package berkeleydb

### PR DESCRIPTION
**Pull request by mezzovide**
tested. im not sure with build process, but i can use it.

### CODE REVIEW

**Comment by TimothyGu** [comment]
I'd use `db` as the package name rather than `berkeleydb`

**Comment by mezzovide** [comment]
done.

**Comment by starius** [comment]
Timothy, why `db`?
It is usually called `Berkeley DB` or `BDB`, but not `db`.
`db` is too common name to delegate it to this particular database.

**Comment by TimothyGu** [comment]
@starius said:
> `db` is too common name to delegate it to this particular database.

It's called `db` in Debian and in its tarball.

**Pull request merged**
