### PR TITLE
new package: unrtf

### PR DESCRIPTION
**Pull request by mabrand**
This is a tool for converting RTF (rich text format) to several usable formats. As far as I know, there is no portable library that does this, so unrtf is useful for applications that need this functionality.

### CODE REVIEW

**Comment by starius** [comment]
These two unrelated changes (empty line addition and deletion) undo each other. IMHO they should be removed from the patch.

**Comment by starius** [comment]
This package installs `usr/<target>/bin/unrtf.exe` and a directory `usr/<target>/share/unrtf/`. The directory has the following files in it:
  * html.conf  
  * latex.conf  
  * rtf.conf  
  * SYMBOL.charmap  
  * text.conf  
  * troff_mm.conf  
  * vt.conf

Does `unrtf` use them if it is compiled in MXE?

**Comment by starius** [comment]
IMHO, in light of #881 this package is a candidate for `mxe-exe`, because it provides a tool, not a library, and this tool is not a part of build-chain.

**Comment by mabrand** [comment]
Thanks for the reviw. I cleaned up the patch.
unrtf needs the config files to run. It has switch -P to specify configuration directory.

**Comment by tonytheodore** [comment]
@starius This would still be an edge case even with #881 as it's not really a handy or end user tool, more something a developer would bundle with their app to get the functionality that can't be provided in another way. Probably better to think in terms of use case of developers vs users rather than the implementation artefacts, but I'll try and clarify it further.

**Pull request merged**
