### PR TITLE
qtbase: fix log corruption with many zero bytes

### PR DESCRIPTION
**Pull request by starius**
see #938

### CODE REVIEW

**Comment by mabrand** [comment]
I was just wondering if there is problem has been solved upstream in the meantime? Have you checked already? Could you propose this patch there?

**Comment by mabrand** [comment]
merged

**Comment by starius** [comment]
I'll try to submit the patch. I wish them accepted a github pull request instead of all this:
https://wiki.qt.io/Qt_Contribution_Guidelines

**Comment by starius** [comment]
The patch was proposed to Qt team: https://codereview.qt-project.org/138224

**Pull request closed without merging**
