### PR TITLE
Make Travis CI build build-matrix.html

### PR DESCRIPTION
**Pull request by TimothyGu**
Untested, but probably works. Also we should consider dynamically generate HTML through JSON or something like that.

### CODE REVIEW

**Comment by starius** [comment]
It commits changes with `git commit -a -m 'Update versions.json' || true`.
We should update the commit message. Maybe "Update generated files"?

**Comment by TimothyGu** [comment]
Fixed.

**Comment by starius** [comment]
+1 for this.
Rebase & Merge.

**Comment by tonytheodore** [comment]
> Also we should consider dynamically generate HTML through JSON or something like that.

Agreed, we also should move the package list back to `src/*.mk` and generate that also.

Thanks! [Rebased and merged](https://github.com/mxe/mxe/compare/cd70bd2...abda011).

**Pull request closed without merging**
