### PR TITLE
Fix aubio for python 3

### PR DESCRIPTION
**Pull request by starius**
see #1108

### CODE REVIEW

**Comment by tonytheodore** [comment]
Works with python 2.7.1 but strange errors with 3.5.1 https://gist.github.com/tonytheodore/50d78962897f792f64da

**Comment by starius** [comment]
I think, it worth upgrading whole waf. There is a problem with [how aubio upgrades waf](https://github.com/aubio/aubio/blob/master/Makefile) and [waf itself](https://github.com/waf-project/waf/issues/1677).

**Comment by tonytheodore** [comment]
> I think, it worth upgrading whole waf

Can we put it in `$(BUILD)/bin` and use that instead of `./waf`?

**Comment by starius** [comment]
I think, we should add waf as a package.

**Comment by starius** [comment]
See https://github.com/waf-project/waf/issues/1677#issuecomment-168491796
> The waf file does unpack a content that is dependent on the python version in order to support Python 2.5.

We should use binary "waf" file rather than "waflib".

**Comment by starius** [comment]
The problem was reported to aubio project: https://github.com/aubio/aubio/issues/41

**Comment by starius** [comment]
Replaced with https://github.com/mxe/mxe/pull/1128 and package waf (not yet published).

**Pull request closed without merging**
