### PR TITLE
Itk shared

### PR DESCRIPTION
**Pull request by bugbrains**
update itk to 4.7.2
enable shared

### CODE REVIEW

**Comment by tonytheodore** [comment]
Could you squash this into a single commit and ensure there are no random whitespace issues or changes to unrelated files? 

Also, try to prefix your commit messages with the package name. Something like
```
itk: update to 4.7.2, enable shared, and use system libs if possible
```
would be appropriate.

**Comment by tonytheodore** [comment]
GCC has been downgraded to 4.9.3 (#965) and I've updated [ITK to 4.8.2](https://github.com/mxe/mxe/commit/a542fd9d940a00b262ffc8cd5bd00b469985496d).

I've switched to a [common `TryRunResults.cmake`] (https://github.com/mxe/mxe/commit/768c11246eb7f8a5d64c3f27069dc0898f6c2fee) though I'm with @TimothyGu about the result variables, they should be the exit code - "0" for success. If you can find some definitive references about this it would be great - I'm mostly going by running the executables on a windows machine. The best solution would be to run with `wine` to see how `cmake` interprets the settings.

The shared builds are broken, though it gets most of the way there - if you can take a look at the new version it would be much appreciated.

**Comment by bugbrains** [comment]
With cmake 3.4. there are ways to configure wine.

CMAKE_CROSSCOMPILING:BOOL=ON

CMAKE_CROSSCOMPILING_EMULATOR:STRING='/usr/bin/wine'


With this setting i can run try_run() from MXE environment and it
works pretty well.


On 12/1/15, Tony Theodore <notifications@github.com> wrote:
> GCC has been downgraded to 4.9.3 (#965) and I've updated [ITK to
> 4.8.2](https://github.com/mxe/mxe/commit/a542fd9d940a00b262ffc8cd5bd00b469985496d).
>
> I've switched to a [common `TryRunResults.cmake`]
> (https://github.com/mxe/mxe/commit/768c11246eb7f8a5d64c3f27069dc0898f6c2fee)
> though I'm with @TimothyGu about the result variables, they should be the
> exit code - "0" for success. If you can find some definitive references
> about this it would be great - I'm mostly going by running the executables
> on a windows machine. The best solution would be to run with `wine` to see
> how `cmake` interprets the settings.
>
> The shared builds are broken, though it gets most of the way there - if you
> can take a look at the new version it would be much appreciated.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mxe/mxe/pull/702#issuecomment-160912970


-- 
Take care

**Comment by tonytheodore** [comment]
> CMAKE_CROSSCOMPILING_EMULATOR:STRING='/usr/bin/wine'

We explicitly disable `wine` during builds as it generally hides issues and we wouldn't want it to be part of the requirements.

**Comment by bugbrains** [comment]
Sorry I wasn't clear. I didn't asked to add wine to mxe build. But
this is an easy for to update the values of try_run instead of copying
into windows and running it.

This is task for packagers. In this case, I can provide you the
results of try_run( ) if that is okay.


On 12/1/15, Tony Theodore <notifications@github.com> wrote:
>> CMAKE_CROSSCOMPILING_EMULATOR:STRING='/usr/bin/wine'
>
> We explicitly disable `wine` during builds as it generally hides issues and
> we wouldn't want it to be part of the requirements.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mxe/mxe/pull/702#issuecomment-160938808


-- 
Take care

**Comment by tonytheodore** [comment]
> In this case, I can provide you the results of try_run( ) if that is okay.

Yes, that would be great - thanks!

Could you do the same for vtk and vtk6? They use the same `KWSYS_*` variables and it would be interesting to see if there's any difference.

**Comment by rkanavath** [comment]
during cmake configure i have this
```
-- Performing Try-Run Test VCL_HAS_TEMPLATE_SYMBOLS - Test Compilation Failed

```
And CMakeCache.txt have the following values for tryrun
```
C_CHAR_SIGNED__TRYRUN_OUTPUT:STRING=
DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS__TRYRUN_OUTPUT:STRING=89255.0/1e22 = 8.9255e-018
H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT:STRING=
H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT:STRING=
H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT:STRING=
H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT:STRING=
H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT:STRING=
H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT:STRING=
H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT:STRING=
H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT:STRING=
H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT:STRING=
H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT:STRING=
H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT:STRING=
HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT:STRING=PRINTF_LL_WIDTH=[I64]
KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT:STRING=
KWSYS_LFS_WORKS__TRYRUN_OUTPUT:STRING=
QNANHIBIT_VALUE__TRYRUN_OUTPUT:STRING=-DTEEM_QNANHIBIT=1
VCL_CHAR_IS_SIGNED__TRYRUN_OUTPUT:STRING=
VCL_COMPLEX_POW_WORKS__TRYRUN_OUTPUT:STRING=
VCL_HAS_LFS__TRYRUN_OUTPUT:STRING=
VCL_HAS_SLICED_DESTRUCTOR_BUG__TRYRUN_OUTPUT:STRING=
VCL_HAS_WORKING_STRINGSTREAM__TRYRUN_OUTPUT:STRING=
VCL_NUMERIC_LIMITS_HAS_INFINITY__TRYRUN_OUTPUT:STRING=
VCL_PROCESSOR_HAS_INFINITY__TRYRUN_OUTPUT:STRING=
VXL_HAS_SSE2_HARDWARE_SUPPORT__TRYRUN_OUTPUT:STRING=
VXL_SSE2_HARDWARE_SUPPORT_POSSIBLE__TRYRUN_OUTPUT:STRING=
```

**Comment by tonytheodore** [comment]
```
DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS__TRYRUN_OUTPUT:STRING=89255.0/1e22 = 8.9255e-018
```
This is the same result I got here: 
https://github.com/mxe/mxe/blob/master/src/cmake/modules/TryRunResults.cmake#L77

What is the value of `DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS`? It should be "1" meaning a failure.

Don't spend too much time on this, we'll have to do arch specific variants and will need to come up with a semi-automated way to do that - along the lines of taking the the idea of [hdf5](https://github.com/mxe/mxe/blob/master/src/hdf5.mk#L39) further.

Thanks for getting it started!

**Comment by rkanavath** [comment]
yes.
DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS:STRING=1

**Comment by rkanavath** [comment]
i have a build error with sharedlibs.

here is the pr. https://github.com/mxe/mxe/pull/1026

**Pull request closed without merging**
