### PR TITLE
openssl: update

### PR DESCRIPTION
**Pull request by mabrand**
Please read http://mxe.cc/#creating-packages

In particular, make sure that your build rules:
- install .pc file,
- install bin/test-pkg.exe compiled with flags by pkg-config,
- install .dll to bin/ and .a, .dll.a to lib/,
- use $(TARGET)-cmake instead of cmake,
- build in `$(BUILD_DIR)` instead of `$(SOURCE_DIR)`,
- do not run target executables with Wine,
- do not download anything while building,
- do not install documentation,
- do not install .exe files except test and build systems,

and .patch files are generated by tools/patch-tool-mxe.

If you add a package, you can use tool tools/skeleton.py.

Thanks!

### CODE REVIEW

**Comment by mabrand** [comment]
WORK IN PROGRESS. Please don't merge yet.
qtbase does not build with openssl 1.1 yet.

**Comment by tonytheodore** [comment]
Fix for shared builds (I can't seem to do a PR for it):

```diff
diff --git a/src/openssl.mk b/src/openssl.mk
index 0ab40ca..28b1cfe 100644
--- a/src/openssl.mk
+++ b/src/openssl.mk
@@ -29,12 +29,8 @@ define $(PKG)_BUILD
         CC='$(TARGET)-gcc' \
         RANLIB='$(TARGET)-ranlib' \
         AR='$(TARGET)-ar rcu' \
-        CROSS_COMPILE='$(TARGET)-'
-
-    # no way to configure engines subdir install
-    $(if $(BUILD_SHARED),
-        rm -rf '$(PREFIX)/$(TARGET)/bin/engines' && \
-        mv -vf '$(PREFIX)/$(TARGET)/lib/engines' '$(PREFIX)/$(TARGET)/bin/')
+        CROSS_COMPILE='$(TARGET)-' \
+        $(if $(BUILD_SHARED), ENGINESDIR='$(PREFIX)/$(TARGET)/bin/engines')
 endef

 $(PKG)_BUILD_i686-w64-mingw32   = $(subst @openssl-target@,mingw,$($(PKG)_BUILD))
```

**Comment by tonytheodore** [comment]
I think `libgcrypt` can be removed from the deps, it isn't referenced anywhere in the log, source, or [commit history](https://github.com/openssl/openssl/search?q=libgcrypt&type=Code)

**Comment by starius** [comment]
@tonytheodore 
cygcrypto from your link is related to libcrypto, which is installed by openssl. It seems unrelated to libgrypt and does not prevent libgrypt from being removed from openssl's deps.

**Comment by starius** [comment]
blocked on: https://github.com/mxe/mxe/pull/1549

**Comment by mabrand** [comment]
Included Tony's fix for shared build of openssl and suggestion to use openssl in freetds to avoid symbol conflicts between gnutls and openssl which would otherwise both be used in qtbase.

qtbase now builds successfully. Upgraded libevent does too.
Not sure if qt (Qt 4) is fixable. Upstream it's dead. Debian seems to have a patch for openssl 1.1 compatibility with Qt 4, but it hasn't worked for me yet.

There are still some other packages in MXE that don't build with openssl 1.1.
Known build problems: gsoap liboauth libshout libtorrent-rasterbar neon poco sqlcipher subversion wt.

At some point, maybe we should consider moving packages depending on openssl 1.0 to plugins.

**Comment by mabrand** [comment]
the updated gsoap builds successfully with openssl 1.1

**Comment by tonytheodore** [comment]
> Not sure if qt (Qt 4) is fixable. Upstream it's dead. Debian seems to have a patch for openssl 1.1 compatibility with Qt 4, but it hasn't worked for me yet.

May be a good time to move it to `plugins/qt4` and switch any remaining packages to Qt5 - I'll have a look at it.

**Comment by tonytheodore** [comment]
New PR #2057 which includes this and boost updates/qt4 plugin in tandem.

**Comment by tonytheodore** [comment]
Merged in #2057

**Pull request closed without merging**
