### PR TITLE
build-pkg: do not omit gitignored files in usr

### PR DESCRIPTION
**Pull request by starius**
See https://github.com/mxe/mxe/pull/1443#issuecomment-233181951

### CODE REVIEW

**Comment by tonytheodore** [comment]
Can you change commit message to "force inclusion of" rather than "do not omit"?

**Comment by starius** [comment]
I have changed the commit message. Now it doesn't fit in [50 characters](http://chris.beams.io/posts/git-commit/#limit-50).

> So shoot for 50 characters, but consider 69 the hard limit.

**Comment by tonytheodore** [comment]
I see, hadn't thought about 50 characters before but shorter can be clearer. How about "build-pkg: track all files"?

**Comment by starius** [comment]
Chenged to `build-pkg: track all files including gitignored`.

**Comment by tonytheodore** [comment]
Thanks!

**Comment by tonytheodore** [comment]
What do you think of a [commit template](http://codeinthehole.com/writing/a-useful-template-for-commit-messages/)? Apparently, we can set [custom `prepare-commit-msg
` hooks](https://www.kernel.org/pub/software/scm/git/docs/githooks.html) for a repo-specific template.

**Comment by starius** [comment]
It is a good idea (as well as [issue template](https://github.com/mxe/mxe/issues/1235)).
Can we add the hook project-wide?

**Pull request merged**
