### PR TITLE
add native plugin for wheezy requirements

### PR DESCRIPTION
**Pull request by tonytheodore**
A simple workaround for https://github.com/mxe/mxe/issues/1177#issuecomment-173752040, symlink the required packages in a new plugin directory.

Add to `settings.mk`:
```
MXE_PLUGIN_DIRS=plugins/native/wheezy
```
Check:
```sh
$ make print-deps-for-build-pkg | grep "for-build-pkg `./ext/config.guess`"
for-build-pkg x86_64-apple-darwin14.5.0~autoconf 2.69 x86_64-apple-darwin14.5.0~m4 x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~automake 1.15 x86_64-apple-darwin14.5.0~autoconf x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~cloog 0.18.1 x86_64-apple-darwin14.5.0~gmp x86_64-apple-darwin14.5.0~isl x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~cmake 3.0.2  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~geoip-database 20150317-1  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~gettext 0.19.7 x86_64-apple-darwin14.5.0~libiconv x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~gmp 6.1.0  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~isl 0.12.2 x86_64-apple-darwin14.5.0~gmp x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~libiconv 1.14  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~libtool 2.4.4 x86_64-apple-darwin14.5.0~autoconf x86_64-apple-darwin14.5.0~automake x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~lzma 920  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~m4 1.4.17  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~mpc 1.0.2 x86_64-apple-darwin14.5.0~gmp x86_64-apple-darwin14.5.0~mpfr x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~mpfr 3.1.3 x86_64-apple-darwin14.5.0~gmp x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~mxe-conf 1
for-build-pkg x86_64-apple-darwin14.5.0~patch 2.7.5  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~pkgconf da179fd  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~ucl 1.03  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~upx 3.91 x86_64-apple-darwin14.5.0~ucl x86_64-apple-darwin14.5.0~zlib x86_64-apple-darwin14.5.0~lzma x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~waf 1.8.17  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~yasm 1.3.0  x86_64-apple-darwin14.5.0~mxe-conf
for-build-pkg x86_64-apple-darwin14.5.0~zlib 1.2.8  x86_64-apple-darwin14.5.0~mxe-conf
```

### CODE REVIEW

**Comment by starius** [comment]
It seems to work:
```
$ MXE_PLUGIN_DIRS=plugins/native/wheezy make print-deps-for-build-pkg | grep "for-build-pkg `./ext/config.guess`"                                                                   
for-build-pkg x86_64-unknown-linux-gnu~autoconf 2.69 x86_64-unknown-linux-gnu~m4 x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~automake 1.15 x86_64-unknown-linux-gnu~autoconf x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~cloog 0.18.1 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~isl x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~cmake 3.0.2  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~geoip-database 20150317-1  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~gettext 0.19.7 x86_64-unknown-linux-gnu~libiconv x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~gmp 6.1.0  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~isl 0.12.2 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~libiconv 1.14  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~libtool 2.4.4 x86_64-unknown-linux-gnu~autoconf x86_64-unknown-linux-gnu~automake x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~lzma 920  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~m4 1.4.17  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~mpc 1.0.2 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~mpfr x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~mpfr 3.1.3 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~mxe-conf 1   
for-build-pkg x86_64-unknown-linux-gnu~patch 2.7.5  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~pkgconf da179fd  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~ucl 1.03  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~upx 3.91 x86_64-unknown-linux-gnu~ucl x86_64-unknown-linux-gnu~zlib x86_64-unknown-linux-gnu~lzma x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~waf 1.8.17  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~yasm 1.3.0  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~zlib 1.2.8  x86_64-unknown-linux-gnu~mxe-conf
```
I'm building all packages on Wheezy, commit 9f6c0efceb84fba75916270aef73943d2f709879.

**Comment by starius** [comment]
Can we enable this plugin by default on Wheezy? Wheezy can be detected by `lsb_release`:

```
$ lsb_release -sc
wheezy
```

**Comment by starius** [comment]
Built with `build-pkg` on Wheezy without broken packages.
https://gist.github.com/21fb6474c162b4a2633b
Commit 9f6c0efceb84fba75916270aef73943d2f709879

**Comment by tonytheodore** [comment]
> Can we enable this plugin by default on Wheezy?

Done https://github.com/mxe/mxe/commit/a2e79fec92b09dbac440de062195df710e83d7f1. We'll probably want to add `darwin` down the track also.

**Comment by starius** [comment]
> Done a2e79fe.

It works:

```
$ make print-deps-for-build-pkg | grep "for-build-pkg `./ext/config.guess`"
for-build-pkg x86_64-unknown-linux-gnu~autoconf 2.69 x86_64-unknown-linux-gnu~m4 x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~automake 1.15 x86_64-unknown-linux-gnu~autoconf x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~cloog 0.18.1 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~isl x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~cmake 3.0.2  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~geoip-database 20150317-1  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~gettext 0.19.7 x86_64-unknown-linux-gnu~libiconv x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~gmp 6.1.0  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~isl 0.12.2 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~libiconv 1.14  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~libtool 2.4.4 x86_64-unknown-linux-gnu~autoconf x86_64-unknown-linux-gnu~automake x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~lzma 920  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~m4 1.4.17  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~mpc 1.0.2 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~mpfr x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~mpfr 3.1.3 x86_64-unknown-linux-gnu~gmp x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~mxe-conf 1   
for-build-pkg x86_64-unknown-linux-gnu~patch 2.7.5  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~pkgconf da179fd  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~ucl 1.03  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~upx 3.91 x86_64-unknown-linux-gnu~ucl x86_64-unknown-linux-gnu~zlib x86_64-unknown-linux-gnu~lzma x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~waf 1.8.17  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~yasm 1.3.0  x86_64-unknown-linux-gnu~mxe-conf 
for-build-pkg x86_64-unknown-linux-gnu~zlib 1.2.8  x86_64-unknown-linux-gnu~mxe-conf
```

**Pull request merged**
