### PR TITLE
add package xmlsec

### PR DESCRIPTION
**Pull request by aquiles2k**
A small lib implementing XML signing based on W3C Standard: XMLDSIG using libxml2 and changeable encyrption backends. We needed it for one of our projects and i thought it might be a good addition to mxe for others to use.

See:
-https://www.aleksey.com/xmlsec/
-https://www.w3.org/TR/xmldsig-core/
-https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-xmlsec/PKGBUILD

### CODE REVIEW

**Comment by aquiles2k** [comment]
Should i care for the deploy preview?

**Comment by aquiles2k** [comment]
@tonytheodore Do you know whats that with deploy/netlify?

**Comment by tonytheodore** [comment]
I wouldn't worry about the deploy preview, it seems to still happen if I retry, but will probably fix itself.

A couple of points:
  - static builds are failing
  - please use $(SOURCE_DIR) and $(BUILD_DIR)
  - add a link test using one of the installed *.pc files - this may need patching to ensure [XMLSEC_STATIC](https://github.com/lsh123/xmlsec/blob/master/include/xmlsec/exports.h#L25) is defined.
  - disable apps

**Comment by aquiles2k** [comment]
doh the rebase didnt work, ill close this pr and reopen a new one

**Pull request closed without merging**
