### PR TITLE
gdal: 2.0.1 -> 2.0.2

### PR DESCRIPTION
**Pull request by tehnick**

### CODE REVIEW

**Comment by starius** [comment]
I'm building `gdal` and `openscenegraph` to make sure that everything is Ok.

**Comment by starius** [comment]
`gdal` and `openscenegraph` for target `i686-w64-mingw32.shared` built successfully.
(Static target can't build because of https://github.com/mxe/mxe/issues/1232 .)

**Comment by starius** [comment]
Thanks!

**Comment by tehnick** [comment]
Just for a note: with my configuration options [1][2] openscenegraph is built fine for x86_64-w64-mingw32.static and i686-w64-mingw32.static.

[1] https://github.com/tehnick/mxe/blob/tehnick/v2.0/src/openscenegraph.mk
[2] https://github.com/tehnick/mxe/blob/tehnick/v2.0/Makefile#L89

**Pull request merged**
