### PR TITLE
Add libotr

### PR DESCRIPTION
**Pull request by tehnick**

### CODE REVIEW

**Comment by starius** [comment]
I sent my fixes to https://github.com/sibuserv/mxe/pull/2

**Comment by starius** [comment]
Currently (https://github.com/mxe/mxe/pull/1714/commits/7be791d8a957a3e9c571db598ab4023b36766ee2) it builds for i686-w64-mingw32.static but [fails for i686-w64-mingw32.shared](https://gist.github.com/d49bf2415e98cae513cfffbfbd594665).

**Comment by tehnick** [comment]
```
boris@Tehnick:~/Opt/mxe__gcc5$ touch src/libotr.mk
boris@Tehnick:~/Opt/mxe__gcc5$ LC_ALL=C git status
On branch add-libotr
Your branch is up-to-date with 'origin/add-libotr'.
nothing to commit, working tree clean
boris@Tehnick:~/Opt/mxe__gcc5$ git log | head -n 1
commit 7be791d8a957a3e9c571db598ab4023b36766ee2
boris@Tehnick:~/Opt/mxe__gcc5$ make libotr
[build]     libotr                 i686-w64-mingw32.static
[done]      libotr                 i686-w64-mingw32.static                                6492 KiB       0m24,071s
[build]     libotr                 i686-w64-mingw32.shared
[done]      libotr                 i686-w64-mingw32.shared                                6596 KiB       0m23,160s
[build]     libotr                 x86_64-w64-mingw32.static
[done]      libotr                 x86_64-w64-mingw32.static                              6808 KiB       0m24,805s
[build]     libotr                 x86_64-w64-mingw32.shared
[done]      libotr                 x86_64-w64-mingw32.shared                              6880 KiB       0m23,886s
boris@Tehnick:~/Opt/mxe__gcc5$ lsb_release -d
Description:    Debian GNU/Linux 9.0 (stretch)
```

What is the difference?

**Comment by tonytheodore** [comment]
Strange, all targets also build successfully on Darwin 16.4.0. I'm guessing it's something to do with automake version.

@starius, can you try building with the native automake plugin?

**Comment by starius** [comment]
It fails on Debian Jessie and the command is:

```
i686-w64-mingw32.shared-gcc -shared  .libs/privkey.o .libs/context.o .libs/proto.o .libs/b64.o
.libs/dh.o .libs/mem.o .libs/message.o .libs/userstate.o .libs/tlv.o .libs/auth.o .libs/sm.o 
.libs/context_priv.o .libs/instag.o   -L/home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib 
/home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libgcrypt.dll.a
/home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libgpg-error.dll.a
/home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libintl.dll.a
/home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libiconv.dll.a
-O2   -o .libs/libotr-5.dll -Wl,--enable-auto-image-base -Xlinker
--out-implib -Xlinker .libs/libotr.dll.a
```

It builds on Debian Wheezy and the command is

```
i686-w64-mingw32.shared-gcc -shared  .libs/privkey.o .libs/context.o .libs/proto.o .libs/b64.o
.libs/dh.o .libs/mem.o .libs/message.o .libs/userstate.o .libs/tlv.o .libs/auth.o .libs/sm.o 
.libs/context_priv.o .libs/instag.o   -L/usr/lib/mxe/usr/i686-w64-mingw32.shared/lib
/usr/lib/mxe/usr/i686-w64-mingw32.shared/lib/libgcrypt.dll.a
/usr/lib/mxe/usr/i686-w64-mingw32.shared/lib/libgpg-error.dll.a
/usr/lib/mxe/usr/i686-w64-mingw32.shared/lib/libintl.dll.a
/usr/lib/mxe/usr/i686-w64-mingw32.shared/lib/libiconv.dll.a  -g
-O2 -fstack-protector-all   -o .libs/libotr-5.dll -Wl,--enable-auto-image-base -Xlinker
--out-implib -Xlinker .libs/libotr.dll.a
```

Debian Wheezy has two dditional flags: `-g` and `-fstack-protector-all`.

If I add `-fstack-protector-all` to Debian Jessie, it builds.

Enabling `automake` plugin (as well as its dependencies `autoconf` and `m4`) doesn't help.

**Comment by starius** [comment]
It is strange... Options `-fstack-protector-all` and `-g` are passed to `libtool` but not to the compiler:

```
/bin/bash ../libtool  --tag=CC   --mode=link i686-w64-mingw32.shared-gcc  -g -O2 -D_FORTIFY_SOURCE=2 -fstack-protector-all -Wstack-protector -fwrapv -
fno-strict-overflow -Wall -Wextra -Wno-unused-parameter -Wformat-security --param ssp-buffer-size=1 -version-info 6:1:1  -L/home/mxe/mxe-libotr/usr/i6
86-w64-mingw32.shared/lib -lgcrypt -lgpg-error -lintl -liconv -no-undefined -o libotr.la -rpath /home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib p
rivkey.lo context.lo proto.lo b64.lo dh.lo mem.lo message.lo userstate.lo tlv.lo auth.lo sm.lo context_priv.lo instag.lo  
libtool: link: i686-w64-mingw32.shared-gcc -shared  .libs/privkey.o .libs/context.o .libs/proto.o .libs/b64.o .libs/dh.o .libs/mem.o .libs/message.o .
libs/userstate.o .libs/tlv.o .libs/auth.o .libs/sm.o .libs/context_priv.o .libs/instag.o   -L/home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib /hom
e/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libgcrypt.dll.a /home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libgpg-error.dll.a /home/mxe/mxe
-libotr/usr/i686-w64-mingw32.shared/lib/libintl.dll.a /home/mxe/mxe-libotr/usr/i686-w64-mingw32.shared/lib/libiconv.dll.a  -O2   -o .libs/libotr-5.dll
 -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libotr.dll.a
```
(Jessie)

**Comment by starius** [comment]
From libtool script on Wheezy:

```
      # Flags to be passed through unchanged, with rationale:
      # -64, -mips[0-9]      enable 64-bit mode for the SGI compiler
      # -r[0-9][0-9]*        specify processor for the SGI compiler
      # -xarch=*, -xtarget=* enable 64-bit mode for the Sun compiler
      # +DA*, +DD*           enable 64-bit mode for the HP compiler
      # -q*                  compiler args for the IBM compiler
      # -m*, -t[45]*, -txscale* architecture-specific flags for GCC
      # -F/path              path to uninstalled frameworks, gcc on darwin
      # -p, -pg, --coverage, -fprofile-*  profiling flags for GCC
      # -fstack-protector*   stack protector flags for GCC
      # @file                GCC response files
      # -tp=*                Portland pgcc target processor selection
      # --sysroot=*          for sysroot support
      # -O*, -g*, -flto*, -fwhopr*, -fuse-linker-plugin GCC link-time optimization
      # -stdlib=*            select c++ std lib with clang
      -64|-mips[0-9]|-r[0-9][0-9]*|-xarch=*|-xtarget=*|+DA*|+DD*|-q*|-m*| \
      -t[45]*|-txscale*|-p|-pg|--coverage|-fprofile-*|-F*|@*|-tp=*|--sysroot=*| \
      -O*|-g*|-flto*|-fwhopr*|-fuse-linker-plugin|-fstack-protector*|-stdlib=*)
```

On Jessie:

```
      # Flags to be passed through unchanged, with rationale:
      # -64, -mips[0-9]      enable 64-bit mode for the SGI compiler
      # -r[0-9][0-9]*        specify processor for the SGI compiler
      # -xarch=*, -xtarget=* enable 64-bit mode for the Sun compiler
      # +DA*, +DD*           enable 64-bit mode for the HP compiler
      # -q*                  compiler args for the IBM compiler
      # -m*, -t[45]*, -txscale* architecture-specific flags for GCC
      # -F/path              path to uninstalled frameworks, gcc on darwin
      # -p, -pg, --coverage, -fprofile-*  profiling flags for GCC
      # @file                GCC response files
      # -tp=*                Portland pgcc target processor selection
      # --sysroot=*          for sysroot support
      # -O*, -flto*, -fwhopr*, -fuse-linker-plugin GCC link-time optimization
      -64|-mips[0-9]|-r[0-9][0-9]*|-xarch=*|-xtarget=*|+DA*|+DD*|-q*|-m*| \
      -t[45]*|-txscale*|-p|-pg|--coverage|-fprofile-*|-F*|@*|-tp=*|--sysroot=*| \
      -O*|-flto*|-fwhopr*|-fuse-linker-plugin)
```

`-fstack-protector*` is missing on Jessie.

**Comment by starius** [comment]
Enabling `libtool` plugin (in addition to `automake`, `autoconf` and `m4` that are `libtool`'s deps) helps.

**Comment by starius** [comment]
I sent PR https://github.com/mxe/mxe/pull/1718

**Comment by starius** [comment]
@tehnick 
Can you rebase the PR, please?
```
$ git pull --rebase https://github.com/mxe/mxe master
$ git push -f
```

**Comment by tehnick** [comment]
> Can you rebase the PR, please?

Done.

**Comment by starius** [comment]
Thanks!

**Pull request merged**
