### PR TITLE
Add gtk3

### PR DESCRIPTION
**Pull request by mgehre**
This updates glib, atk and pango to the minimal versions required by gtk3.
And adds the gtk3 package.

In librsvg, there was an error due to typedef redefinition caused by the glib update. I removed '-pedantic' from the librsvg test flags to work around that issue.

### CODE REVIEW

**Comment by starius** [comment]
Failed to build package gtk3 for target i686-w64-mingw32.static!

```
make[1]: Entering directory `/home/mxe/mxe-gtk3-795'
uname -a
Linux sd-68075 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
git show-branch --list --reflog=1
  [refs/heads/gtk3@{0}] (2 hours ago) clone: from https://github.com/mgehre/mxe/
lsb_release -a 2>/dev/null || sw_vers 2>/dev/null || true
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
rm -rf   '/home/mxe/mxe-gtk3-795/tmp-gtk3-i686-w64-mingw32.static'
mkdir -p '/home/mxe/mxe-gtk3-795/tmp-gtk3-i686-w64-mingw32.static'
cd '/home/mxe/mxe-gtk3-795/tmp-gtk3-i686-w64-mingw32.static' &&       xz -dc '/home/mxe/mxe-gtk3-795/pkg/gtk+-3.16.6.tar.xz' | tar xf -
cd '/home/mxe/mxe-gtk3-795/tmp-gtk3-i686-w64-mingw32.static/gtk+-3.16.6'
(cd '/home/mxe/mxe-gtk3-795/tmp-gtk3-i686-w64-mingw32.static/gtk+-3.16.6' && patch -p1 -u) < ./src/gtk3-1-remove-demos-and-tests.patch
patching file Makefile.in
cd '/home/mxe/mxe-gtk3-795/tmp-gtk3-i686-w64-mingw32.static/gtk+-3.16.6' && ./configure --host='i686-w64-mingw32.static' --build='x86_64-unknown-linux-gnu' --prefix='/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static'  --enable-static --disable-shared  --enable-explicit-deps --disable-glibtest --disable-cups --disable-test-print-backend --disable-gtk-doc --disable-man --with-included-immodules --without-x
configure: loading site script /home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/share/config.site
checking build system type... (cached) x86_64-unknown-linux-gnu
checking host system type... i686-w64-mingw32.static
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-w64-mingw32.static-strip... i686-w64-mingw32.static-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1008' is supported by ustar format... yes
checking whether GID '1008' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking for i686-w64-mingw32.static-gcc... i686-w64-mingw32.static-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-w64-mingw32.static-gcc accepts -g... yes
checking for i686-w64-mingw32.static-gcc option to accept ISO C89... none needed
checking whether i686-w64-mingw32.static-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of i686-w64-mingw32.static-gcc... gcc3
checking how to run the C preprocessor... i686-w64-mingw32.static-gcc -E
checking for gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking whether i686-w64-mingw32.static-gcc and cc understand -c and -o together... yes
checking whether make sets $(MAKE)... (cached) yes
checking for native Win32... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for i686-w64-mingw32.static-c++... i686-w64-mingw32.static-c++
checking whether we are using the GNU C++ compiler... yes
checking whether i686-w64-mingw32.static-c++ accepts -g... yes
checking dependency style of i686-w64-mingw32.static-c++... gcc3
configure: WARNING: Disabling static library build, must build as DLL on Windows.
configure: WARNING: Enabling shared library build, must build as DLL on Windows.
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by i686-w64-mingw32.static-gcc... /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld
checking if the linker (/home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-nm -B
checking the name lister (/home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking how to convert x86_64-unknown-linux-gnu file names to i686-w64-mingw32.static format... func_convert_file_nix_to_w32
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld option to reload object files... -r
checking for i686-w64-mingw32.static-objdump... i686-w64-mingw32.static-objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for i686-w64-mingw32.static-dlltool... i686-w64-mingw32.static-dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for i686-w64-mingw32.static-ar... i686-w64-mingw32.static-ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32.static-strip... (cached) i686-w64-mingw32.static-strip
checking for i686-w64-mingw32.static-ranlib... i686-w64-mingw32.static-ranlib
checking command to parse /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-nm -B output from i686-w64-mingw32.static-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for i686-w64-mingw32.static-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking for dlfcn.h... no
checking for i686-w64-mingw32.static-as... i686-w64-mingw32.static-as
checking for i686-w64-mingw32.static-dlltool... (cached) i686-w64-mingw32.static-dlltool
checking for i686-w64-mingw32.static-objdump... (cached) i686-w64-mingw32.static-objdump
checking for objdir... .libs
checking if i686-w64-mingw32.static-gcc supports -fno-rtti -fno-exceptions... no
checking for i686-w64-mingw32.static-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32.static-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32.static-gcc static flag -static works... yes
checking if i686-w64-mingw32.static-gcc supports -c -o file.o... yes
checking if i686-w64-mingw32.static-gcc supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32.static-gcc linker (/home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... i686-w64-mingw32.static-c++ -E
checking for ld used by i686-w64-mingw32.static-c++... /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld
checking if the linker (/home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld) is GNU ld... yes
checking whether the i686-w64-mingw32.static-c++ linker (/home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld) supports shared libraries... yes
checking for i686-w64-mingw32.static-c++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32.static-c++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32.static-c++ static flag -static works... yes
checking if i686-w64-mingw32.static-c++ supports -c -o file.o... yes
checking if i686-w64-mingw32.static-c++ supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32.static-c++ linker (/home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-ld) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
configure: creating ./config.lt
config.lt: creating libtool
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking dependency style of i686-w64-mingw32.static-gcc... gcc3
checking for i686-w64-mingw32.static-nm... /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-nm -B
checking for some Win32 platform... yes
checking for i686-w64-mingw32.static-windres... i686-w64-mingw32.static-windres
checking for lib.exe... no
checking for shm_open in -lrt... no
checking for posix_fallocate... no
checking for i686-w64-mingw32.static-pkg-config... /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether build environment is sane... yes
checking how to get MSVC-compatible struct packing... -mms-bitfields
checking for BASE_DEPENDENCIES... yes
checking for CAIRO_BACKEND... yes
checking for GMODULE... yes
checking whether to write dependencies into .pc files... yes
checking for perl5... no
checking for perl... /usr/bin/perl
checking for lstat... no
checking for mkstemp... yes
checking for localtime_r... no
checking for _NL_TIME_FIRST_WEEKDAY... no
checking for _NL_MEASUREMENT_MEASUREMENT... no
checking for _NL_PAPER_HEIGHT... no
checking for _NL_PAPER_WIDTH... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... no
checking for bindtextdomain in -lintl... no
checking if -liconv is needed to use gettext... 
checking for ngettext in -lintl... yes
checking for dcgettext in -lintl... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for catalogs to be installed...  af am an ang ar as ast az az_IR be be@latin bg bn bn_IN br bs ca ca@valencia crh cs cy da de dz el en en_CA en_GB en@shaw eo es et eu fa fi fr ga gd gl gu he hi hr hu hy ia id io is it ja ka kg kk km kn ko ku ky lg li lt lv mai mi mk ml mn mr ms my nb nds ne nl nn nso oc or pa pl ps pt pt_BR ro ru rw si sk sl sq sr sr@ije sr@latin sv ta te tg th tk tr tt ug uk ur uz uz@cyrillic vi wa xh yi zh_CN zh_HK zh_TW
checking whether xgettext supports ui files... yes
checking for extra flags to get ANSI library prototypes... none needed
checking for the BeOS... no
checking for HP-UX... no
checking for i686-w64-mingw32.static-pkg-config... (cached) /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.43.4... yes (version 2.43.92)
checking for pkg-config... /usr/bin/pkg-config
checking build system's pkg-config is at least version 0.16... yes
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gmodule-no-export-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-no-export-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gmodule-no-export-2.0' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gmodule-no-export-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-no-export-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gmodule-no-export-2.0' found
checking for bind_textdomain_codeset... (cached) yes
checking sys/mman.h usability... no
checking sys/mman.h presence... no
checking for sys/mman.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking ftw.h usability... yes
checking ftw.h presence... yes
checking for ftw.h... yes
checking for GNU ftw extensions... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... no
checking for mallinfo... no
checking for getresuid... no
checking for uid_t in sys/types.h... no
checking for round in -lm... yes
checking for round... yes
checking for rint... yes
checking for nearbyint... yes
checking for sincos... yes
checking whether isnan is declared... yes
checking whether isinf is declared... yes
checking crt_externs.h usability... no
checking crt_externs.h presence... no
checking for crt_externs.h... no
checking for _NSGetEnviron... no
checking whether to build dynamic modules... yes
checking whether dynamic modules work... yes
checking immodules to build... am-et,cedilla,cyrillic-translit,inuktitut,ipa,multipress,thai,ti-er,ti-et,viqr,ime
checking sys/systeminfo.h usability... no
checking sys/systeminfo.h presence... no
checking for sys/systeminfo.h... no
checking sys/sysinfo.h usability... no
checking sys/sysinfo.h presence... no
checking for sys/sysinfo.h... no
checking Pango flags... -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/harfbuzz -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/cairo -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/pixman-1  -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/libpng16 -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/freetype2 -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/pango-1.0 -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/include/glib-2.0 -I/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/lib/glib-2.0/include -mms-bitfields -DPCRE_STATIC   -lpangocairo-1.0 -lpangoft2-1.0 -lpangowin32-1.0 -lpango-1.0 -lm -lgmodule-2.0 -lharfbuzz -lcairo -lgobject-2.0 -lfontconfig -lusp10 -lmsimg32 -lgdi32 -lpixman-1 -lexpat -lfreetype -lbz2 -lpng16 -lz -lharfbuzz_too -lglib-2.0 -L/home/mxe/mxe-gtk3-795/usr/i686-w64-mingw32.static/lib/../lib -lffi -lws2_32 -lole32 -lwinmm -lshlwapi -lpcre -lintl -liconv   
checking for GDK_DEP... yes
checking for ATK... yes
checking for GTK_DEP... yes
checking for library containing gethostent... no
checking for library containing setsockopt... no
checking for library containing connect... no
checking for struct sockaddr_un.sun_len... no
checking libpapi... checking for papiServiceCreate in -lpapi... no
checking for REST... no
checking for JSON_GLIB... no
checking cairo-pdf.h usability... yes
checking cairo-pdf.h presence... yes
checking for cairo-pdf.h... yes
checking for IPrintDialogCallback... yes
checking for i686-w64-mingw32.static-pkg-config... (cached) /home/mxe/mxe-gtk3-795/usr/bin/i686-w64-mingw32.static-pkg-config
checking pkg-config is at least version 0.16... yes
checking for glib-compile-schemas... no
configure: error: glib-compile-schemas not found.
make[1]: *** [build-only-gtk3_i686-w64-mingw32.static] Error 1
make[1]: Leaving directory `/home/mxe/mxe-gtk3-795'

real	0m12.010s
user	0m9.177s
sys	0m1.020s
```

**Comment by mgehre** [comment]
Fixed the build failure. It was picking up my OS version of glib-compile-schemas, now it takes the one compiled by the glib pkg.

**Comment by starius** [comment]
It is still broken: https://gist.github.com/starius/98976ceab162e2000181
It seems you are using tools from host system.

There is [another proposal for gtk3 and gtkmm3](https://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-08/msg00036.html) which requires only one new host dependency: gdk-pixbuf. I think these two attempts of adding gtk3 should be combined, taking better parts from both.

**Comment by tonytheodore** [comment]
Note that without patching `configure` in gtk3 the build will be a shared build. @mgehre can you try building #850 and move the conversation there?

**Comment by tonytheodore** [comment]
@mgehre I've merged #850, it's an older version but the static builds are working with test programs. Some of the other deps have also subsequently been updated.

Thanks for submitting this, after years we get two at the same time!

**Pull request closed without merging**
