### PR TITLE
update gcc 4.9.3 --> 4.9.4

### PR DESCRIPTION
**Pull request by tonytheodore**
Tested on all four targets, list of changes:
https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=4.9.4

### CODE REVIEW

**Comment by starius** [comment]
I am building it with `build-pkg`.

**Comment by tonytheodore** [comment]
You may see an ordering bug fixed in https://github.com/mxe/mxe/pull/1477

**Comment by starius** [comment]
I built with `MXE_BUILD_PKG_NO_DEBS=1 MXE_BUILD_PKG_NO_SECOND_PASS=1`. Build log: https://gist.github.com/82074a49aaf9b2a134df465d9389d72b Everything seems to be Ok.

**Comment by starius** [comment]
Thanks!

**Pull request merged**
