### PR TITLE
Update pe-parse to latest release

### PR DESCRIPTION
**Pull request by danger89**
Update the Windows PE parser (pe-parse) package to latest version. Which also includes new **gcc 11** fixes.

(which also includes: https://github.com/trailofbits/pe-parse/pull/158 for the examples)

Build tested, works fine.

### CODE REVIEW

**Comment by danger89** [comment]
New release created on my request: https://github.com/trailofbits/pe-parse/commit/2a1aa79d0a8c59faa882a37605932348ef001331

Updated to this commit

**Comment by danger89** [comment]
@mabrand ping :)

**Comment by mabrand** [comment]
Any reason not to squash these into one commit?

**Comment by danger89** [comment]
You are free to select the Squash and merge button in the PR.

**Pull request merged**
