### PR TITLE
Add plugin for compiling mingw-w64 with secure APIs enabled.

### PR DESCRIPTION
**Pull request by saiarcot895**
This is based off of #897.

### CODE REVIEW

**Comment by tonytheodore** [comment]
A plugin is probably overkill for this case, you could just set the variable directly, i.e
```
make mingw-w64_SEC_API=1
# instead of
make MXE_PLUGIN_DIRS=...
```

I'd opt for something more general though, adding `$(mingw-w64-headers_CONFIGURE_OPTS)` to the `configure` invocation and calling with:

```
make mingw-w64-headers_CONFIGURE_OPTS=--enable-secure-api
```

**Comment by saiarcot895** [comment]
Updated implementation. This variable can then be set from settings.mk, right?

**Comment by tonytheodore** [comment]
> This variable can then be set from settings.mk, right?

Yes, from settings.mk or command line.

Looks good, can you rebase into a single commit?

**Comment by saiarcot895** [comment]
Done

**Comment by tonytheodore** [comment]
Thanks!

**Pull request merged**
