### PR TITLE
add "make shell" command

### PR DESCRIPTION
**Pull request by starius**
It provides interactive shell with the environment of MXE build.

### CODE REVIEW

**Comment by tonytheodore** [comment]
Nice! That's a great approach that has many possibilities - we could change build rules to shell variables instead of `make` variables to allow easy copy-pasting for tutorials/debugging...

A couple of little tweaks in https://github.com/LuaAndC/mxe/pull/4. It would be good to move the creation of `WINEPREFIX` out of `mxe-conf` and add it as dependency of `shell`, but that can be done separately.

**Comment by starius** [comment]
> It would be good to move the creation of WINEPREFIX out of mxe-conf and add it as dependency of shell, but that can be done separately.

See https://github.com/mxe/mxe/issues/1221#issuecomment-185110607
Removing MXE tree is complicated because of readonly directory.

**Comment by tonytheodore** [comment]
How would you like to handle these types of merges:
  1. use the merge button
  2. person merging rebases and pushes from local, manually closing pull request
  3. person proposing rebases and force-push to update request, then merge with button

I'm beginning to think that rebasing to reduce merges is a losing battle and the [new squash feature is even worse](https://github.com/blog/2141-squash-your-commits).

**Comment by tonytheodore** [comment]
4. Disable "squash" and use the merge button ;)

Thanks!

**Comment by starius** [comment]
I prefer option 3: person proposing rebases and force-push to update request, then merge with button.

> new squash feature is even worse.

Agreed. Squashing kills atomic nature of commits. I'd prefer to have "Rebase and merge" instead (without squash!).

> rebasing to reduce merges

A merge commit after a pull request to mxe:master is important, as it "closes" the pull request. It serves as a separator in the history. I think, that pull requests (followed by merge commits) should be the only source of new commits in `master`.

A merge commit after a cross- pull request (e.g., 8499a63d82e3a75578ec92bcfe4c837b9dbda082) are not so important and can be removed using `git rebase` after merging them with "Merge" button. Merge commits from `master` should be avoided and replaced with rebase, as they break a sequence of commits of the pull request with unrelated commits from `master`.

Turning to rebase-before-merge in mxe:master, it is useful not because it avoids a merge commit (see above why), but because it **groups the commits of the pull request**, simplifying the output of `git log --graph`. It is easy to read when commits from different pull requests do not intermix and the number of leading `| ` is low (ideally is equal to 1).

**Pull request merged**
