### PR TITLE
Add openthreads

### PR DESCRIPTION
**Pull request by rkanavath**
add openthreads using openscenegraph archive

### CODE REVIEW

**Comment by tonytheodore** [comment]
Good idea, it's currently building a lot of dependencies just for openthreads support. A couple of notes:

* Use variables for the common metadata, see [bfd](https://github.com/mxe/mxe/blob/master/src/bfd.mk) for an example.
* Needs corresponding disabling of openthreads in openscenegraph (unless they are installed in different locations)

**Comment by rkanavath** [comment]
done.

**Comment by tonytheodore** [comment]
Great! Squash the three openthreads commits into a single one and it's good to.

**Comment by rkanavath** [comment]
happy ?

**Comment by tonytheodore** [comment]
Now there are 6 commits?? Do you want me to do the rebasing?

**Comment by rkanavath** [comment]
yes please. I always mess up with rebase.

**Comment by tonytheodore** [comment]
Thanks! Merged https://github.com/mxe/mxe/compare/b24fe61...a854196

**Comment by rkanavath** [comment]
for next time. 
can you tell how you did squashing commits?

**Comment by tonytheodore** [comment]
In this case, `rebase` wouldn't even replay with no changes. I'm no `git` expert so I had to fall back to `git diff master` and `patch` to manually recommit the changes.

I think you did a `squash` in this commit https://github.com/bugbrains/mxe/commit/59047d11c0611270d1faac6537bfd34cb357375e, and then did some other "forcing" to make it merge.

In general though, `squash` doesn't do what I expect - I use `fixup` (even when I say "squash"). Try to merge and rebase frequently and always do a plain rebase before `rebase -i`.

**Pull request closed without merging**
