### PR TITLE
introducing copydlldeps.sh and copydlldeps.txt

### PR DESCRIPTION
**Pull request by dl5rcw**
In reference to #1180, I would like to contribute these filed. Thanks for your help!

### CODE REVIEW

**Comment by starius** [comment]
Can you replace `copydlldeps.txt` with `copydlldeps.md`, please?

**Comment by dl5rcw** [comment]
Renamed to .md

**Comment by TimothyGu** [comment]
> Please tell me, do I have to re-initiate anything for the pull request or is it automatically included?

No, you do not. However, it would help if for these amending commits you could `commit --amend` (or if you have already made a new commit, do an interactive rebase), so that the history is more linear.

**Comment by dl5rcw** [comment]
Done. Thanks for assistance!

**Comment by starius** [comment]
1. Can you fix MarkDown syntax in https://github.com/dl5rcw/mxe/blob/master/tools/copydlldeps.md, please?
  2. Squash two commits into one and rebase, please.

**Comment by dl5rcw** [comment]
I directly edited it in github, so I guess this is okay now? Let me know if something is still missing.

**Comment by starius** [comment]
I created [a pull request](https://github.com/dl5rcw/mxe/pull/1) to improve copydlldeps.md:
https://github.com/starius/mxe/blob/patch-1/tools/copydlldeps.md

**Comment by dl5rcw** [comment]
Thanks for editing!

**Comment by dl5rcw** [comment]
Anything that needs to be done for the pull request to be completed?

**Comment by starius** [comment]
Can you provide test/example (script, not text) for it or a link to one?

**Comment by dl5rcw** [comment]
Well, this is a script itself to grab the required dlls by the generated application used in a shared build.
The script and how to call it is explained in the .md file. @starius, you made great edits to it. 

The best way of testing is to use it. It is in productive environment here and works as spedified since I started the pull request. I call it on a *exe file created and it dumps the *dll files. That's it. If we add a sample application with shared library, we could see that it grabs all dlls that we are aware of, but I think that is 4 times the effort as the copydlldeps.sh itself and not getting to the point of error catching. It could even produce greater potential to cause failures in the test than the script itself :) 

Hence, I suggest to add it and release it. The *md is explaining how to call and use the script. You did great edits to it. Plus, the script itself has a -help option, too.

**Comment by starius** [comment]
Thanks! The test is coming soon.

**Comment by starius** [comment]
https://github.com/mxe/mxe/pull/1225

**Comment by starius** [comment]
@dl5rcw, please see #1225 and #1226

**Pull request merged**
