### PR TITLE
libical: disable parallel build

### PR DESCRIPTION
**Pull request by tonytheodore**
See:
https://github.com/libical/libical/issues/238
https://github.com/libical/libical/issues/233

### CODE REVIEW

**Comment by starius** [comment]
IMHO, build with `-j 1` and add a comment with reference to bug reports in upstream.

**Comment by tonytheodore** [comment]
Indeed, retrying masks some subtle issues - the libs are being built twice.

**Comment by tonytheodore** [comment]
Double-build is a known issue: https://github.com/libical/libical/issues/174

Rebased and changed to disable parallel build.

**Comment by starius** [comment]
Could you add a comment with link to https://github.com/libical/libical/issues/174 above `$(MAKE) -C '$(BUILD_DIR)' -j 1 VERBOSE=1`, please?

**Comment by tonytheodore** [comment]
> Could you add a comment with link to libical/libical#174

Done, it doesn't look like an easy fix.

**Pull request merged**
