### PR TITLE
[WIP] qt5: fix pkg-config files and enable debug variants

### PR DESCRIPTION
**Pull request by tonytheodore**
See #1316, build with:
```
make qt5 QT5_BUILD_TYPE=[-release | -debug-and-release | -debug]
```

### CODE REVIEW

**Comment by und3f** [comment]
I have an issue with the default MXE_TARGET
On the mxe:master it is detected as i686-w64-mingw32.static
tonytheodore:qt5-debug detects it as the x86_64-unknown-linux-gnu

**Comment by und3f** [comment]
I've built mxe

**Comment by und3f** [comment]
Everything works perfectly.

**Comment by aquiles2k** [comment]
can confirm it works, finally some more readable stacktraces on crashdumps :)

**Comment by starius** [comment]
Looks good to me. @tonytheodore, can you rebase and merge this pull request?

**Comment by tonytheodore** [comment]
Shall do, I'm not happy with introducing a special case `QT5_BUILD_TYPE=` but the `pkg-config` fix gets rid of ugly workarounds.

**Comment by tonytheodore** [comment]
Replaced with #1442, @und3f, @aquiles2k note the final usage:

```
make qt5 qtbase_CONFIGURE_OPTS=[-release | -debug-and-release | -debug]
```

**Comment by aquiles2k** [comment]
Is there a place we can document it, i always keep coming back to this pull request for the syntax :)

**Comment by tonytheodore** [comment]
The general form of [package overrides](https://github.com/mxe/mxe/wiki/Customisable-Packages#rule-examples) will be `pkg_CONFIGURE_OPTS` or `pkg_CMAKE_OPTS`. Ideally, this shouldn't need documenting, a declarative `MXE_TARGETS=i686-w64-mingw32.static.debug` would be better.

Until that's implemented, some notes here: https://github.com/mxe/mxe/wiki/Package-Specific-Notes#qt5-debug-builds

**Comment by tonytheodore** [comment]
@aquiles2k do you normally use `-debug-and-release` or just `-debug` on it's own?

**Comment by aquiles2k** [comment]
I, personally, prefer and use debug-and-release since i need both anyway for development, deployment and debugging crash reports.

**Pull request closed without merging**
