### PR TITLE
protobuf: use official release tarball instead of tarball from git tag

### PR DESCRIPTION
**Pull request by tehnick**

### CODE REVIEW

**Comment by starius** [comment]
Content of files differs.

```diff
Only in after/protobuf-2.6.1: aclocal.m4
Only in before/protobuf-2.6.1: benchmarks
Only in after/protobuf-2.6.1: compile
Only in after/protobuf-2.6.1: config.guess
Only in after/protobuf-2.6.1: config.h.in
Only in after/protobuf-2.6.1: config.sub
Only in after/protobuf-2.6.1: configure
Only in after/protobuf-2.6.1: depcomp
Only in after/protobuf-2.6.1: gtest
Only in after/protobuf-2.6.1: install-sh
Only in before/protobuf-2.6.1/java/src/test/java/com/google/protobuf: test_extra_interfaces.proto
Only in after/protobuf-2.6.1: ltmain.sh
Only in after/protobuf-2.6.1/m4: libtool.m4
Only in after/protobuf-2.6.1/m4: lt~obsolete.m4
Only in after/protobuf-2.6.1/m4: ltoptions.m4
Only in after/protobuf-2.6.1/m4: ltsugar.m4
Only in after/protobuf-2.6.1/m4: ltversion.m4
Only in after/protobuf-2.6.1: Makefile.in
Only in after/protobuf-2.6.1: missing
Only in before/protobuf-2.6.1: more_tests
Only in before/protobuf-2.6.1: post_process_dist.sh
Only in before/protobuf-2.6.1/src/google/protobuf: descriptor_pb2_test.py
Only in before/protobuf-2.6.1/src/google/protobuf: SEBS
diff -r before/protobuf-2.6.1/src/Makefile.am after/protobuf-2.6.1/src/Makefile.am
42d41
<   google/protobuf/stubs/atomicops_internals_arm_gcc.h           \
43a43
>   google/protobuf/stubs/atomicops_internals_arm_gcc.h           \
49a50
>   google/protobuf/stubs/atomicops_internals_solaris.h           \
Only in after/protobuf-2.6.1/src: Makefile.in
Only in after/protobuf-2.6.1: test-driver
diff -r before/protobuf-2.6.1/vsprojects/libprotobuf-lite.vcproj after/protobuf-2.6.1/vsprojects/libprotobuf-lite.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
diff -r before/protobuf-2.6.1/vsprojects/libprotobuf.vcproj after/protobuf-2.6.1/vsprojects/libprotobuf.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
diff -r before/protobuf-2.6.1/vsprojects/libprotoc.vcproj after/protobuf-2.6.1/vsprojects/libprotoc.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
diff -r before/protobuf-2.6.1/vsprojects/lite-test.vcproj after/protobuf-2.6.1/vsprojects/lite-test.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
diff -r before/protobuf-2.6.1/vsprojects/protobuf.sln after/protobuf-2.6.1/vsprojects/protobuf.sln
2,3c2,3
< Microsoft Visual Studio Solution File, Format Version 10.00
< # Visual Studio 2008
---
> Microsoft Visual Studio Solution File, Format Version 9.00
> # Visual Studio 2005
diff -r before/protobuf-2.6.1/vsprojects/protoc.vcproj after/protobuf-2.6.1/vsprojects/protoc.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
diff -r before/protobuf-2.6.1/vsprojects/test_plugin.vcproj after/protobuf-2.6.1/vsprojects/test_plugin.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
diff -r before/protobuf-2.6.1/vsprojects/tests.vcproj after/protobuf-2.6.1/vsprojects/tests.vcproj
4c4
< 	Version="9.00"
---
> 	Version="8.00"
```

New file is larger, mostly because of embedded gtest.

**Comment by tehnick** [comment]
> Content of files differs.

Yes, but this is an official tarball from developers [[1](https://github.com/google/protobuf/releases/tag/v2.6.1)], which is used almost everywhere (in GNU/Linux distros at least).

> New file is larger, mostly because of embedded gtest.

Yep, that is why it will not be downloaded each time when `./autogen.sh` is launched.

**Comment by tehnick** [comment]
Hmm, it looks I forgot to remove extra strings.

**Comment by tehnick** [comment]
Updated.

**Comment by tehnick** [comment]
Also have in mind that future versions of protobuf will be split on separate packages:
https://github.com/google/protobuf/releases/tag/v3.0.0-beta-3

**Comment by starius** [comment]
Looks good to me.

**Pull request merged**
