### PR TITLE
build-pkg: add env. var. MXE_DIR and MXE_NO_DEBS

### PR DESCRIPTION
**Pull request by starius**
See https://github.com/mxe/mxe/pull/836#issuecomment-139034608

### CODE REVIEW

**Comment by TimothyGu** [comment]
Isn't the whole point of build-pkg producing distributable formats of packages (i.e. tarballs or debs)?

**Comment by tonytheodore** [comment]
@TimothyGu Yes, that is it's main purpose. It also [detects various inconsistencies](https://gist.githubusercontent.com/starius/2a60589ae3fccc7a9306/raw/dc7efb5d78f42a6a7db4a5d4e98a0d8f6272d182/build-mxe-conf-cmake-09Sep2015.log) and is useful to run for that alone (say on OSX).

@starius would these be better as command line options or is that overkill at this stage?

**Comment by starius** [comment]
> would these be better as command line options or is that overkill at this stage?

Lua provides command line options only as an array of arguments (global variable `arg`), similar to C's `argc` and `argv`. To parse them properly, external Lua module is required (I prefer [argparse](https://github.com/mpeterv/argparse)). I think, requiring external Lua modules for `build-pkg` is overkill.

**Comment by starius** [comment]
> Isn't the whole point of build-pkg producing distributable formats of packages (i.e. tarballs or debs)?

Tarballs are produced even with option `MXE_NO_DEBS`. Useful on OSX, which doesn't have `dpkg-deb`.

**Comment by tonytheodore** [comment]
Thanks!

**Pull request merged**
