### PR TITLE
case insensitivity + rename option enforce + enforcedir can be called multiple times

### PR DESCRIPTION
**Pull request by dl5rcw**
Changed option find -name to find -iname to make search for *dll case insensitive
Changed option enforce to enforcedir to make it more precise for users (it is copying a directory, e.g. like platforms or audio, both plugins for Qt5)
Option enforcedir can be called multiple times now.

Tested with a sample application running on debian 8.3.0

### CODE REVIEW

**Comment by dl5rcw** [comment]
Running on two instances now, supporting seven projects. Reccommend merge as options improved and namens became more precise.
Added a script building an Qt example (cube) to proove and demonstrate functionality. Find it in my branch, as it is not part of the pull request.

**Comment by starius** [comment]
Can you rebase and squash commits, please?

**Comment by dl5rcw** [comment]
Hope I did everything right with rebase procedure. Still learning features of git, used svn for so many years. Happy to contribute again.

**Comment by pavelvat** [comment]
Merge it, please. I need multiCall for fix #1165.

**Pull request closed without merging**
