### PR TITLE
Add plib shared and 64-bit builds

### PR DESCRIPTION
**Pull request by saiarcot895**
Add the ability to build plib for the 64-bit configuration and a shared build configuration.

### CODE REVIEW

**Comment by starius** [comment]
Tested. Compiles for me for all 4 targets.
However file `test-plibc.exe` exists for `i686-w64-mingw32.static` only. Can you fix this?

**Comment by saiarcot895** [comment]
Is that supposed to be modified as well? In building Qt, the `plibc` package wasn't built.

**Comment by starius** [comment]
Sorry, wrong alert. File `test-plibc.exe` is a part of package `plibc`, not `plib`.

**Comment by tonytheodore** [comment]
Thanks! Building on all four targets and installing shared libs correctly.

**Pull request merged**
