### PR TITLE
URL updates

### PR DESCRIPTION
**Pull request by vszakats**
Mostly with the goal of securing the transport.

Also removed two exec attributes set for non-executable files.

### CODE REVIEW

**Comment by starius** [comment]
https://www.xvid.org/ doesn't work. Can you replace it with https://www.xvid.com/ ?

**Comment by starius** [comment]
https://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/ImageMagick-6.9.0-0.tar.xz doesn't work (as well as previous URL, http://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/ImageMagick-6.9.0-0.tar.xz). I think we can drop this backup URL.

**Comment by vszakats** [comment]
@starius Done, thanks a lot for noticing this!

**Comment by vszakats** [comment]
@starius `imagemagick` keeps only the latest revision there, so this is expected - but unrelated to the protocol upgrade itself. I think this is best to be addressed in a separate commit.

**Comment by starius** [comment]
https://www.cloog.org/ is empty.

**Comment by starius** [comment]
@vszakats 
Thanks for updates!

https://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/ is also 404. I think, the site stopped mirroring ImageMagick releases.

**Comment by vszakats** [comment]
I'm fixing `cloog` as well, thanks!
This is a known working URL for Imagemagick:
https://www.imagemagick.org/download/ImageMagick-7.0.5-0.tar.xz
From:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/imagemagick.rb

**Comment by starius** [comment]
I checked all changed URL. They look OK.

**Comment by vszakats** [comment]
Thank you! I may do some more upgrades later if you don't mind, these were just the more obvious ones. `cloog` restored to HTTP.

**Comment by starius** [comment]
Thanks!

**Pull request merged**
