### PR TITLE
[WIP] CMake: update and improve configuration

### PR DESCRIPTION
**Pull request by tonytheodore**

### CODE REVIEW

**Comment by starius** [comment]
```
build-only-$(1)_$(3): BUILD_DIR  = $(2)/$($(1)_SUBDIR).build_
```
Why `build_`, not `build`?

**Comment by starius** [comment]
I'm building it with `build-pkg` on Jessie.

**Comment by tonytheodore** [comment]
> Why `build_`, not `build`?

Workaround for packages that do `mkdir $(1).build` - it will change once they're all converted.

> I'm building it with build-pkg on Jessie.

Thanks, setting `cmake_policy(VERSION 3.0.2)` breaks a few packages, I've relaxed it with explicit policies: https://github.com/tonytheodore/mxe/commit/8fbec9e7d6985c6c69c0a877e2a64bd760723531

**Comment by tonytheodore** [comment]
Any thoughts about using the undocumented `-B` and `-H` options?:
```
'$(TARGET)-cmake' -B'$(BUILD_DIR)' -H'$(SOURCE_DIR)'
```

**Comment by starius** [comment]
The following packages are broken in commit 653830f5f672f294ccba73028c00b86c190eaeba:

  * portmidi: https://gist.github.com/05dcbf1a10047aa56a0d
  * luabind: https://gist.github.com/d5b3e422951813ab096c
  * libical: https://gist.github.com/06f4ad5e3d0f51ede213
  * teem: https://gist.github.com/ec3674237c7fafe096a7

The build has not been finished yet.

**Comment by starius** [comment]
> Any thoughts about using the undocumented -B and -H options?

I am disappointed in `-B` and `-H`. I have to look for the documentation every time I want to use them. Standard approach (`cd build && cmake source`) is simpler.

**Comment by starius** [comment]
Another broken package is `vigra`: https://gist.github.com/6ff870488b978b1bbb7b
Other packages are OK.

Log of `build-pkg`: https://gist.github.com/824d5253082bbb727e65

**Pull request closed without merging**
