### PR TITLE
Updated cgal to 4.10.

### PR DESCRIPTION
**Pull request by rmarsa**
Please read http://mxe.cc/#creating-packages

In particular, make sure that your build rules:

  * install .pc file,
  * install bin/test-pkg.exe compiled with flags by pkg-config,
  * install .dll to bin/ and .a, .dll.a to lib/,
  * use $(TARGET)-cmake instead of cmake,
  * build in `$(BUILD_DIR)` instead of `$(SOURCE_DIR)`,
  * do not run target executables with Wine,
  * do not download anything while building,
  * do not install documentation,
  * do not install .exe files except test and build systems,

and .patch files are generated by tools/patch-tool-mxe.

If you add a package, you can use tool tools/skeleton.py.

Thanks!

### CODE REVIEW

**Comment by tonytheodore** [comment]
It's missing a `TRY_RUN` entry:
```diff
diff --git a/src/cgal-TryRunResults.cmake b/src/cgal-TryRunResults.cmake
index 9e3acf4..1e9a6dd 100644
--- a/src/cgal-TryRunResults.cmake
+++ b/src/cgal-TryRunResults.cmake
@@ -231,3 +231,12 @@ SET( QT4_RUN_RES__TRYRUN_OUTPUT
      "version=4.8.6"
      CACHE STRING "Output from TRY_RUN" FORCE)

+set( CGAL_test_cpp_version_RUN_RES
+     "0"
+     CACHE STRING "Result from TRY_RUN" FORCE)
+
+set( CGAL_test_cpp_version_RUN_RES__TRYRUN_OUTPUT
+     "201103L"
+     CACHE STRING "Output from TRY_RUN" FORCE)
+
+
```
otherwise appears to build and install correctly, but the test program fails with boost references https://gist.github.com/tonytheodore/5ae4a30b801f3496326669c5009245fe.

**Comment by tonytheodore** [comment]
Removing the tests simply moves any issues with the build/config downstream - we need these to confirm the package is actually usable.

**Comment by rmarsa** [comment]
Yes.  So I know the package is useable because I am using it in production code.  The reason I removed those tests as part of the build is because for them to work, they need to link with boost_thread and boost_system.  This will involve changing CGAL since I would have to modify the build files for the CGAL examples.  As far as I can tell, these examples simply don't build correctly and I will have to submit a patch to CGAL to get them sorted.

The alternative is to make the mxe build patch them before building them and I can look into that.

**Comment by tonytheodore** [comment]
Thanks, [patching to restore the tests](https://github.com/tonytheodore/mxe/blob/52195ec78243d4dd38d384cca191df04478342ed/src/cgal-1-fixes.patch) was fairly straightforward and this is merged in #1859 (along with some style changes)

**Pull request closed without merging**
