### PR TITLE
Qt5 cmake rearrange targets

### PR DESCRIPTION
**Pull request by starius**
See https://github.com/mxe/mxe/issues/1185

### CODE REVIEW

**Comment by starius** [comment]
Currently the test doesn't work. I'm changing it to standard cmake && make approach.

**Comment by starius** [comment]
`i686-w64-mingw32.static` target tested.

**Comment by starius** [comment]
Tested on all 4 targets.

**Comment by UniqueFool** [comment]
thanks for working on this

**Comment by tonytheodore** [comment]
Thanks @starius!

@mabrand, the new patch targets (https://github.com/mxe/mxe/blob/master/patch.mk) normalise the format of patches to improve `git am` round-tripping (#983) and readability of updates. I don't think this will impact your existing workflow, just when it comes to exporting the patches (assuming a local repo):

```
make export-patch-qtbase GITS_DIR=/path/above/repo qtbase_SUBDIR=qtbase-5...
```

there will be variables for local repos in the future, but the logic is currently similar to the original `patch-tool-mxe`.

**Pull request merged**
