### PR TITLE
Add package libsignal-protocol-c + multiple style fixes

### PR DESCRIPTION
**Pull request by tehnick**
Build is tested for:
```
MXE_TARGETS :=  i686-w64-mingw32.static i686-w64-mingw32.shared \
                x86_64-w64-mingw32.static x86_64-w64-mingw32.shared
```

### CODE REVIEW

**Comment by tehnick** [comment]
Sorry for mixed commits for different packages. This time I do not have much time to make a separate PRs.

**Comment by tonytheodore** [comment]
Thanks! The [new libsignal-protocol-c](https://github.com/mxe/mxe/commit/477779a4c4c1d14e3d7f48081ef74c9b31307a64) and [freeglut style fixes](https://github.com/mxe/mxe/commit/cd7e036e63960b71288cb0742ba4168af5868836) look good.

OpenSceneGraph has a pending update #2044 that is held up on switching to odd numbered releases (which tags will do).

TinyXML is in #2082 (waiting for full build to complete)

**Comment by tonytheodore** [comment]
qtkeychain and qhttpengine are also in #2082.

**Comment by tehnick** [comment]
@tonytheodore I have dropped extra commits.

**Comment by tehnick** [comment]
As for #2044 I disagree with update to unstable version because all end-user software which I saw is built with stable version of library. (But I have not checked if they have changed API or not.)

**Comment by tonytheodore** [comment]
> I have dropped extra commits.

Thanks @tehnick, I already merged those manually (https://github.com/mxe/mxe/pull/2083#issuecomment-373387173).

**Pull request closed without merging**
