### PR TITLE
Introducing hamlib

### PR DESCRIPTION
**Pull request by dl5rcw**
adding hamlib to mxe, adjusted to the new style pushed by @starius, writing homepage and description into the *.mk file. hamlib-test.c included.

### CODE REVIEW

**Comment by starius** [comment]
After fixing some issues discussed in comments, it builds here and lists of installed files look good.

Why have you closed it?

**Comment by dl5rcw** [comment]
@starius - I have not seen your comments, which are excellent and help to improve, before I took action. Sorry for that.

I got a rather unpleasant notification that it failed from someone else. Being off my dev computers for the next days, I closed it to have time to fix that. I will reopen (now) and fix that once I get back. Thanks for your comments, they help to improve and fix it. Please excuse the inconveniences.

**Comment by dl5rcw** [comment]
@starius Thanks for your comments, they helped a lot! I committed and squashed into one. Please let me know if I missed out on something.
MXE_GET_GITHUB_TAGS worked. I checked and updated to 3.0.1. Nate recommended sourceforge, so this stays active. Others stay available in the *.mk file.

**Comment by starius** [comment]
Typo: `$(MAKE) -C '$(1)' -j 1`
(Should be `$(MAKE) -C '$(BUILD_DIR)' -j 1`)

Can you remove the section "grabbing version from github"? (The section "grabbing version from github via MXE" seems to do the same but with less code.)

**Comment by dl5rcw** [comment]
@starius done and squashed. Thanks for the hint!

**Comment by starius** [comment]
Thanks!

**Pull request merged**
