### PR TITLE
libwebsockets updated

### PR DESCRIPTION
**Pull request by newnon**

### CODE REVIEW

**Comment by starius** [comment]
Could you make a patch from `libwebsockets-1-fixes.patch`, please? Now it is only a diff without commit message and authorship. You can use `./tools/patch-tool-mxe` to make a patch.

**Comment by pavelvat** [comment]
It is deprecated:
```
      cd '$(1)' && cmake \
         -DCMAKE_TOOLCHAIN_FILE='$(CMAKE_TOOLCHAIN_FILE)'
```
See for example: https://github.com/mxe/mxe/blob/master/src/freeglut.mk#L20-26

**Comment by newnon** [comment]
if it possible add please add information what you need, i've just fixed some files and make a patch with some GUI tool it is not from any commit.

**Comment by starius** [comment]
@TimothyGu, you are the author of [original patch](https://github.com/mxe/mxe/blob/3caf14807e3c702dcae2ff25687426f3c22d9fda/src/libwebsockets-1-fixes.patch).
Can you review this change, please?

**Comment by TimothyGu** [comment]
Unassigning myself; I will no longer have time to work on this unfortunately.

**Comment by tonytheodore** [comment]
libwebsockets updated to 2.4.2 in https://github.com/mxe/mxe/commit/b3552f798ccdc03466f78b43fe9c1ab5df6eda18

**Pull request closed without merging**
