### PR TITLE
github.mk: fix tag prefix with single `v` and pkg name <> project name

### LINKED ISSUE #1728: Github subdir incorrect on certain tags
from https://github.com/mxe/mxe/pull/1727#issuecomment-287655994, tags with a single `v` prefix seem to strip this when downloading. `qca` #1709 will have the same issue.

### PR DESCRIPTION
**Pull request by tonytheodore**
fixes #1728

### CODE REVIEW

**Comment by pavelvat** [comment]
Maybe this variant:
```
cd '$(BUILD_DIR)' && $(TARGET)-cmake '$(SOURCE_DIR)' \
```
more unified than:
```
cd '$(BUILD_DIR)' && $(TARGET)-cmake \
... \
... \
... \
'$(SOURCE_DIR)'
```

**Comment by tonytheodore** [comment]
How do the [cmake rule examples](https://github.com/mxe/mxe/wiki/Customisable-Packages#rule-examples) look? We could add `$(MXE_CMAKE_OPTS)` and move options out of the toolchain/wrapper that [complicate downstream use](https://github.com/mxe/mxe/pull/1621#discussion_r106937505).

**Comment by tonytheodore** [comment]
I'll take those `BUILD_DIR` changes out of this PR.

**Comment by tonytheodore** [comment]
> I'll take those BUILD_DIR changes out of this PR.

Actually, I'll leave them in - there's no functional change and they're already tested.

This PR seems covers some more cases with GH_CONF, the odd single `v` prefix and projects with different package names. There's another api to investigate - `releases`, but it shouldn't hold this up.

**Pull request merged**
