### PR TITLE
Update boost

### PR DESCRIPTION
**Pull request by jonaski**

### CODE REVIEW

**Comment by fiesh** [comment]
I guess this would supersede #2302?

Any chance of this being merged?

**Comment by tonytheodore** [comment]
I'm happy to test this if you can confirm "direct" downstream dependencies for all targets build. 
```
% make show-direct-downstream-deps-boost
assimp cgal cpp-netlib hyperscan json_spirit libtorrent-rasterbar luabind openscenegraph pcl pe-util wt xmlwrapp
```

Something like:
```
make \
    $(make show-direct-downstream-deps-boost) \
    MXE_TARGETS="$(echo {i686,x86_64}-w64-mingw32.{static,shared})"
```
Then I'll test all the recursive downstream:
```
% make show-downstream-deps-boost
agg assimp aubio cegui cgal chromaprint cpp-netlib ffmpeg freetype ftgl gd ghostscript grantlee graphicsmagick gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gtk2 gtk3 gtkglarea gtkglext gtkglextmm gtkimageview gtkmm2 gtkmm3 gtksourceview gtksourceviewmm2 harfbuzz hyperscan icu4c imagemagick json_spirit libass libbluray libechonest libglade libical liblastfm librsvg libspectre libtorrent-rasterbar luabind ocaml-cairo ocaml-camlimages ocaml-lablgl ocaml-lablgtk2 oce opencsg opencv openscenegraph osgearth ossim pango pangomm pcl pe-util plotmm poppler qca qhttpengine qjson qscintilla2 qt3d qt5 qtactiveqt qtbase qtcharts qtconnectivity qtdatavis3d qtdeclarative qtgamepad qtgraphicaleffects qtifw qtimageformats qtkeychain qtlocation qtmultimedia qtnetworkauth qtofficeopenxml qtpurchasing qtquickcontrols qtquickcontrols2 qtremoteobjects qtscript qtscxml qtsensors qtserialbus qtserialport qtservice qtsparkle qtspeech qtsvg qtsystems qttools qttranslations qtvirtualkeyboard qtwebchannel qtwebkit qtwebsockets qtwebview qtwinextras qtxlsxwriter qtxmlpatterns quazip qwt qwtplot3d sdl2_ttf sdl_pango sdl_ttf sfml smtpclient-for-qt t4k_common vtk wt xmlwrapp
```

and will merge it if there's no errors.

**Comment by fiesh** [comment]
Ping @tonytheodore 

(Although by now this is a bit outdated as well, but still huge improvement over the ancient boost 1.60 from 2015.)

**Comment by fiesh** [comment]
(Also, after some thought, I think Boost should *not* be a module.  Boost is usually quite backwards-compatible, with the notable exception of boost fiber / coroutine, which just doesn't care about its users at all and probably should be avoided.  So I think there should only be one Boost version present.)

**Comment by fiesh** [comment]
Ah sorry I misread, I'll give the dependencies a try.

**Comment by fiesh** [comment]
Ok so it doesn't build.  After removing `boost-1-fixes.patch`, they still all fail.

@jonaski Do you intend to fix this PR?  Otherwise I guess it should be closed.

**Comment by jonaski** [comment]
This PR 1 year old. I use 1.73.0 in my own MXE repository.

**Pull request closed without merging**
