### PR TITLE
Fix aubio

### LINKED ISSUE #1108: Problems with Archlinux
# my configuration :
* an up to date Archlinux (`Linux archsuizokukan 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`)
* alure is installed (a `$pacman -Ss alure` returns `community/alure 1.2-4 [installed]`)
* a fresh installation of mxe : `git clone https://github.com/mxe/mxe`, `cd mxe`, then `make MXE_TARGETS='x86_64-w64-mingw32.static'`

# the error :
`make MXE_TARGETS='x86_64-w64-mingw32.static'` compiles a lot of stuff (mxe-conf, gcc... zlib, ...) and exits returning the following message :
> Failed to build package alure for target x86_64-w64-mingw32.static!

# the logs from log/alure_x86_64-w64-mingw32.static :
> [ 92%] Building CXX object CMakeFiles/ALURE32-static.dir/src/codec_mpg123.obj
> /home/suizokukan/mxe20151229/usr/bin/x86_64-w64-mingw32.static-g++   -DDYNLOAD=1 -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_WIN32 -DAL_LIBTYPE_STATIC -DALURE_STATIC_LIBRARY -O3 -DNDEBUG @CMakeFiles/ALURE32-static.dir/includes_CXX.rsp   -Wextra -Wall -funswitch-loops  -DALURE_STATIC_LIBRARY -o CMakeFiles/ALURE32-static.dir/src/codec_mpg123.obj -c /home/suizokukan/mxe20151229/tmp-alure-x86_64-w64-mingw32.static/alure-1.2/src/codec_mpg123.cpp
> /home/suizokukan/mxe20151229/tmp-alure-x86_64-w64-mingw32.static/alure-1.2/src/codec_mpg123.cpp:33:20: fatal error: mpg123.h: No such file or directory
> #include <mpg123.h>

Any help would be appreciated !

### PR DESCRIPTION
**Pull request by TimothyGu**
Should fix #1108 in conjunction with #1129.

### CODE REVIEW

**Comment by starius** [comment]
`aubio` depends on `jack`, so `aubio` is also disabled on static builds.

**Comment by TimothyGu** [comment]
No; jack is only an optional dependency of aubio. aubio still builds happily without it.

**Comment by starius** [comment]
Optional dependencies are also a source of problems (see https://github.com/mxe/mxe/issues/1111).

**Comment by TimothyGu** [comment]
@starius I just explicitly disabled jack for static builds. Hope that it's enough.

**Comment by starius** [comment]
`jack` is still in the list of `aubio` deps: https://github.com/TimothyGu/mxe/blob/a39897c2810cabac4bc0a35102f3633d2a8d5065/src/aubio.mk#L11

**Comment by TimothyGu** [comment]
Yes, but jack will be a noop for static targets:

```sh
TimothyGu@mxe:~/mxe$ rm usr/x86_64-w64-mingw32.static/installed/jack
TimothyGu@mxe:~/mxe$ make jack
[using autodetected 2 job(s)]
[no-build]  jack                   x86_64-w64-mingw32.static                                             
TimothyGu@mxe:~/mxe$ ls -l usr/x86_64-w64-mingw32.static/installed/jack 
-rw-r--r-- 1 TimothyGu mxe 0 Jan  7 22:08 usr/x86_64-w64-mingw32.static/installed/jack
```

**Pull request merged**
