### PR TITLE
librsvg: Enable module generation for shared build

### PR DESCRIPTION
**Pull request by janbrummer**

### CODE REVIEW

**Comment by Lord-Kamina** [comment]
I forgot to commit it but I have a fork somewhere to build the newer librsvgs requiring rust.

**Comment by kleisauke** [comment]
@Lord-Kamina I've also build the latest librsvg that requires Rust within MXE, see: https://github.com/mxe/mxe/issues/2499#issuecomment-633209023.

I could try to make a PR, but I'm not sure if there's enough interest in this.

As an aside, thanks for the fixes at OpenEXR!

**Comment by Lord-Kamina** [comment]
> @Lord-Kamina I've also build the latest librsvg that requires Rust within MXE, see: [#2499 (comment)](https://github.com/mxe/mxe/issues/2499#issuecomment-633209023).
> 
> I could try to make a PR, but I'm not sure if there's enough interest in this.
> 
> As an aside, thanks for the fixes at OpenEXR!

Thanks. That was borne as a side project from #2409 

I think your approach to rust as very similar to mine; however, mine has the merit of working on more platforms so we should probably combine them. I'll upload my branch later.

**Comment by kleisauke** [comment]
Let me know when you've uploaded it. Do you build Rust from scratch? 

I'm using the pre-built Rust libraries which has disadvantages in terms of compatibility. Only the [`x86_64-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-x86_64.mk) and [`i686-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-i686.mk) targets are supported. The [`aarch64-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-aarch64.mk) and [`armv7-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-armv7.mk) LLVM targets (see #2330) are currently unsupported. It may also cause problems when targeting UCRT since the pre-built Rust libraries are built using a MinGW-w64 compiled with `--with-default-msvcrt=msvcrt`.

**Comment by Lord-Kamina** [comment]
> Let me know when you've uploaded it. Do you build Rust from scratch?
> 
> I'm using the pre-built Rust libraries which has disadvantages in terms of compatibility. Only the [`x86_64-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-x86_64.mk) and [`i686-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-i686.mk) targets are supported. The [`aarch64-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-aarch64.mk) and [`armv7-w64-mingw32.*`](https://github.com/libvips/build-win64-mxe/blob/master/8.9/rust-std-armv7.mk) LLVM targets (see #2330) are currently unsupported. It may also cause problems when targeting UCRT since the pre-built Rust libraries are built using a MinGW-w64 compiled with `--with-default-msvcrt=msvcrt`.

No, I also use pre-built. Initially I attempted to build from scratch but besides taking hours, you couldn't mix-and-match due to rust not being abi-stable, so essentially you needed yo rebuild everything everytime and it was a mess.

**Comment by tonytheodore** [comment]
Thanks!

I'll try to look at rust in the next few weeks.

**Pull request merged**
