### PR TITLE
Added a qwt5_qt4 project that builds version 5 of qwt.

### PR DESCRIPTION
**Pull request by highperformancecoder**
Please read http://mxe.cc/#creating-packages

In particular, make sure that your build rules:

  * install .pc file,
  * install bin/test-pkg.exe compiled with flags by pkg-config,
  * install .dll to bin/ and .a, .dll.a to lib/,
  * use $(TARGET)-cmake instead of cmake,
  * build in `$(BUILD_DIR)` instead of `$(SOURCE_DIR)`,
  * do not run target executables with Wine,
  * do not download anything while building,
  * do not install documentation,
  * do not install .exe files except test and build systems,

and .patch files are generated by tools/patch-tool-mxe.

If you add a package, you can use tool tools/skeleton.py.

Thanks!

### CODE REVIEW

**Comment by tonytheodore** [comment]
See https://github.com/mxe/mxe/blob/master/plugins/qt4/qt4-overlay.mk

You can use that or just create a similar one in a local directory that also pins the version.

**Comment by tonytheodore** [comment]
See also https://github.com/mxe/mxe/tree/master/plugins/examples/qt5-freeze for a more involved example of freezing package versions.

**Comment by highperformancecoder** [comment]
Hi Tony, I'm not sure what you are suggesting I do with this.

Currently, for one of my projects, I need qwt5 and qt4 libraries. It is a long term goal to port the software to newer versions of the library, but that is likely to take years, if it ever happens.

I can continue with qwt5_qt4 in my own fork, of course, I just offered the package as one of potential use to others. This is PR currently the only difference between my fork's develop branch and MXE's head.

**Comment by tonytheodore** [comment]
Package `qwt_qt4` was removed in #1849 as we can't maintain many 
combinations of pinned versions. Plugins are a much better way for
people to do that locally, you could add this to the example plugins
as a way to both pin versions and alter the build slightly.

Something like (untested) `plugins/examples/qwt5_qt4/qwt_overlay.mk`:

```
PKG               := qwt
$(PKG)_VERSION    := 5.2.3
$(PKG)_CHECKSUM   := a23e583ae66a70f21bf2acb87624eb142a5c310088687f7fa51fa3fb8222b5e5
$(PKG)_DEPS       := gcc qt
$(PKG)_QT_DIR     := qt

define $(PKG)_BUILD
    $(SED) -i -e 's/target.path.*$$/target.path = $$$$PREFIX\/lib\/qwt5/' '$(SOURCE_DIR)/qwtconfig.pri'
    $(SED) -i -e 's/headers.path.*$$/headers.path = $$$$PREFIX\/include\/qwt5/' '$(SOURCE_DIR)/qwtconfig.pri'
    $(qwt_BUILD)
endef
```

**Comment by tonytheodore** [comment]
Note you probably don't need to re-define the build rule as users of this plugin won't need a side-by-side install (I'm guessing that's what it does).

**Pull request closed without merging**
