### PR TITLE
update jsoncpp.mk

### PR DESCRIPTION
**Pull request by pavelvat**
https://github.com/mxe/mxe/pull/1686
fix for detecting new version

### CODE REVIEW

**Comment by pavelvat** [comment]
For Debian unstable: https://gist.github.com/pavelvat/e9bd569bacb59f17e53cd85b84ace9ab
Can you test libsoup.mk?

**Comment by tonytheodore** [comment]
LZ4 in #1725 seems to have a subdir problem too.

**Comment by starius** [comment]
Apologies, I tested this pull request against outdated tree, without https://github.com/mxe/mxe/pull/1712

**Comment by starius** [comment]
Tested on all 4 targets.

**Comment by starius** [comment]
Thanks!

**Pull request merged**
