### PR TITLE
Add msmtp to plugins/apps

### PR DESCRIPTION
**Pull request by andrew-strong**
Add msmtp 1.6.5; as suggested by starius this is in plugins/apps:

https://github.com/mxe/mxe/issues/1567

### CODE REVIEW

**Comment by starius** [comment]
It fails on `x86_64-w64-mingw32` targets.
Logs: https://gist.github.com/831573c41949664c3920e01e0f87de78

If you can fix this, add a patch (use tools/patch-tool-mxe to manage patches).
Otherwise add `$(PKG)_BUILD_x86_64-w64-mingw32 =` to `.mk` file to disable `x86_64-w64-mingw32` targets.

**Comment by andrew-strong** [comment]
I contacted the developer of msmtp with the issue of the failed build:

https://sourceforge.net/p/msmtp/mailman/message/35490905/

And the issue has been addressed as well as a new version released, which I have added into the commit.

**Comment by andrew-strong** [comment]
Is the 'All checks have failed' notice an issue? On looking at the output the error seems to be referring to other downloads rather than msmtp?

**Comment by starius** [comment]
The 'All checks have failed' notice was unrelated to this pull request. I restarted the Travis build and it was gone.

I am testing it.

Can you rebase and squash two commits together, please?

**Comment by andrew-strong** [comment]
Hmmm... squash is fine, have I failed with rebase?

**Comment by starius** [comment]
Builds successfully. Can you also apply this patch to avoid installation of documentation, please:

```diff
diff --git a/plugins/apps/msmtp.mk b/plugins/apps/msmtp.mk
index 28805d5..1dcf368 100644
--- a/plugins/apps/msmtp.mk
+++ b/plugins/apps/msmtp.mk
@@ -19,11 +19,12 @@ endef
 define $(PKG)_BUILD
     cd '$(BUILD_DIR)' && '$(SOURCE_DIR)/configure' \
         $(MXE_CONFIGURE_OPTS) \
+        --infodir='$(BUILD_DIR)/sink' \
         --disable-nls \
         --without-libsecret \
         --without-macosx-keyring \
         --with-tls=gnutls \
         --with-libidn
     $(MAKE) -C $(BUILD_DIR) -j '$(JOBS)'
-    $(MAKE) -C $(BUILD_DIR) -j 1 install
+    $(MAKE) -C $(BUILD_DIR) -j 1 install $(MXE_DISABLE_DOCS)
 endef
```

To rebase, do the following:

```
git pull --rebase https://github.com/mxe/mxe master
```

**Comment by andrew-strong** [comment]
Thanks for the patch and the guide on git, all should be well now hopefully...

**Comment by starius** [comment]
Thanks!

**Pull request merged**
