### PR TITLE
Move package metadata from index.html to src/*.mk

### PR DESCRIPTION
**Pull request by starius**
Demo: http://redjohn.tk:2709/#packages

fix https://github.com/mxe/mxe/issues/1422

### CODE REVIEW

**Comment by starius** [comment]
Build log: https://gist.github.com/d368c53a35e376e759ca12a54088eace
No packages are broken.

**Comment by vog** [comment]
This looks very good. Thanks for your effort!

In commit 09a390afbf655d01ff0c1e15edc062b78453e563 I wonder why `$(PKG)_DESCR` is left off for some packages. Shouldn't we set it explicitly an empty string, to encourage people filling this out?

**Comment by starius** [comment]
> why $(PKG)_DESCR is left off for some packages

Empty description is interpreted [by Javascript](https://github.com/mxe/mxe/pull/1602/commits/193e4b6c3b78f19da0b9c37f7afb6cc39c42adeb#diff-eae600270579316beb8b8d9b9a5732d4R1155) as the description equal to the package name. More than half of packages have description (or official name, as it is called in index.html) equal to the package name. It worth reducing header size in mk files for such packages. This behavior also encourages using official package name as package name in MXE.

**Comment by starius** [comment]
Rebased.

**Comment by vog** [comment]
Okay, fine for me.

**Comment by tonytheodore** [comment]
Nice work, thanks!

**Pull request merged**
