### PR TITLE
add package clementine to mxe/plugins/apps

### PR DESCRIPTION
**Pull request by pavelvat**
required https://github.com/mxe/mxe/pull/1626 (qtsparkle is optional dependency. But required package qttools is listed only in qtsparkle.mk and is not listed in clementine.mk)

problems:
1)build is successful, but crash on launch. For order to workaround it you can copy of settings from clementine-qt4 directory (c:\users\USER_NAME\\.config\Clementine) to clementine-qt5 (c:\users\USER_NAME\\.config\Clementine-qt5). Other way: use patch from https://github.com/clementine-player/Clementine/issues/5297
2)clementine-qt5 currently doesn't play any music files and radio streams (gstreamer related errors).

### CODE REVIEW

**Comment by pavelvat** [comment]
>qtsparkle is optional dependency

this is mistake. qtsparkle is a necessary dependence:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
QTSPARKLE_LIBRARIES
    linked by target "clementine_lib" in directory /home/pavel/builds/mxe/tmp-clementine-i686-w64-mingw32.shared/Clementine-987aa20b9d8bb85006f135c4fa3ff2a3fdeb1643/src

-- Configuring incomplete, errors occurred!
```

**Comment by pavelvat** [comment]
I cannot run clementine under Windows XP after update to last commit in qt5-branch https://github.com/clementine-player/Clementine/tree/qt5 and build with Qt 5.8. I get next error message: entry point CancelIoEx could not be found in the KERNEL32.dll.

In the same time, clementine works fine under Windows 7. Moreover the problem 2) disappeared.

In the first message, this problem is not mentioned:
3)Clementine process has stayed in list of processes in task manager after exit from program.

**Comment by tonytheodore** [comment]
Does clementine_qt4 still run on XP after the [mingw-w64 update to v5.0.1](https://github.com/mxe/mxe/commit/95628fe6ec65b9efbe158710cab4415f9501e749)?

**Comment by pavelvat** [comment]
Yes, it does.

**Comment by tonytheodore** [comment]
Looks like the fallback for XP support was removed: https://codereview.qt-project.org/#/c/159370/2//ALL,unified.

**Comment by pavelvat** [comment]
Commit was updated:
* update to last commit in qt5-branch https://github.com/clementine-player/Clementine/tree/qt5
* fix build with qtsparkle (previously build was successful only if package qtsparkle_qt4 was installed)
* fix 1) by using the patch https://github.com/clementine-player/Clementine/pull/5669

So last unresolved problem is 3):
``` 3)Clementine process has stayed in list of processes in task manager after exit from program.```

**Comment by tonytheodore** [comment]
This looks good to me, I don't think the last issue is a reason to keep it in WIP.

Note you can [replace _SUBDIR, _FILE, _URL, and _UPDATE with _GH_CONF](http://mxe.cc/#creating-packages):
```diff
diff --git a/plugins/apps/clementine.mk b/plugins/apps/clementine.mk
index 70a8d6b..0269c70 100644
--- a/plugins/apps/clementine.mk
+++ b/plugins/apps/clementine.mk
@@ -2,21 +2,15 @@
 
 PKG             := clementine
 $(PKG)_IGNORE   :=
-$(PKG)_VERSION  := fbc2f78f8899ae174b094494ff42fb06d2157b1b
-$(PKG)_CHECKSUM := 44f89bdc539379baaa5a45ede5fa7bf842ecadd0dd232e6942e2b29636d8ff7a
-$(PKG)_SUBDIR   := Clementine-$($(PKG)_VERSION)
-$(PKG)_FILE     := clementine-$($(PKG)_VERSION).tar.gz
-$(PKG)_URL      := https://github.com/$(PKG)-player/$(PKG)/archive/$($(PKG)_VERSION).tar.gz
+$(PKG)_VERSION  := fbc2f78
+$(PKG)_CHECKSUM := ed26f77c41869cbb054a0ca33cc5bb98b5d8cf5ff248ca3ab188b896fb16cc7c
+$(PKG)_GH_CONF  := clementine-player/Clementine/qt5
 $(PKG)_WEBSITE  := https://www.clementine-player.org/
 $(PKG)_OWNER    := https://github.com/pavelvat
 $(PKG)_DEPS     := gcc boost chromaprint cryptopp fftw glew gst-libav gst-plugins-bad \
                    gst-plugins-good gst-plugins-ugly liblastfm \
                    libmpcdec protobuf qtsparkle sparsehash
 
-define $(PKG)_UPDATE
-    $(call MXE_GET_GITHUB_TAGS, clementine-player/clementine)
-endef
-
 define $(PKG)_BUILD
     cd '$(BUILD_DIR)' && $(TARGET)-cmake '$(SOURCE_DIR)' \
         -DCMAKE_INSTALL_PREFIX=$(PREFIX)/$(TARGET)/apps/$(PKG)
diff --git a/plugins/apps/clementine_qt4.mk b/plugins/apps/clementine_qt4.mk
index 721c105..21a418c 100644
--- a/plugins/apps/clementine_qt4.mk
+++ b/plugins/apps/clementine_qt4.mk
@@ -12,19 +12,13 @@ PKG             := clementine_qt4
 $(PKG)_IGNORE   :=
 $(PKG)_VERSION  := 1.3.1
 $(PKG)_CHECKSUM := f885931a9ab7c88607d07b50c64fcce46fc05f13dd2c0a04188c94eff938f37c
-$(PKG)_SUBDIR   := Clementine-$($(PKG)_VERSION)
-$(PKG)_FILE     := clementine-$($(PKG)_VERSION).tar.gz
-$(PKG)_URL      := https://github.com/clementine-player/clementine/archive/$($(PKG)_VERSION).tar.gz
+$(PKG)_GH_CONF  := clementine-player/Clementine
 $(PKG)_WEBSITE  := https://www.clementine-player.org/
 $(PKG)_OWNER    := https://github.com/pavelvat
 $(PKG)_DEPS     := gcc boost chromaprint cryptopp fftw glew gst-libav gst-plugins-bad \
                    gst-plugins-good gst-plugins-ugly libechonest liblastfm_qt4 \
                    libmpcdec protobuf qtsparkle_qt4 sparsehash
 
-define $(PKG)_UPDATE
-    $(call MXE_GET_GITHUB_TAGS, clementine-player/clementine)
-endef
-
 define $(PKG)_BUILD
     cd '$(BUILD_DIR)' && $(TARGET)-cmake '$(SOURCE_DIR)' \
         -DCMAKE_INSTALL_PREFIX=$(PREFIX)/$(TARGET)/apps/$(PKG)
```

**Comment by pavelvat** [comment]
>Note you can replace _SUBDIR, _FILE, _URL, and _UPDATE with _GH_CONF

Done.

**Comment by tonytheodore** [comment]
Thanks!

**Pull request merged**
