### PR TITLE
mxe-conf: create basic non-empty directory hierarchy

### PR DESCRIPTION
**Pull request by tonytheodore**
https://github.com/mxe/mxe/pull/1061/files#r49049496
https://github.com/mxe/mxe/issues/1111#issuecomment-169280181

### CODE REVIEW

**Comment by starius** [comment]
IMHO, `s/mxe-hier/.gitkeep/`

**Comment by starius** [comment]
Two methods of creating a directory are used in the same file:

  * `mkdir -p` (CMAKE_TOOLCHAIN_DIR and BUILD)
  * `install -d`

Can you use `mkdir -p` instead of `install -d`?

**Comment by starius** [comment]
Can you also include my commit 4fb55fe5a16c32a29a8b0353175691bfbd643b9a into this pull request?

**Comment by tonytheodore** [comment]
> IMHO, s/mxe-hier/.gitkeep/

Agreed, that's much clearer.

> Can you use mkdir -p instead of install -d?

Done, I didn't know `mkdir` had the `-m` option.

Added https://github.com/mxe/mxe/commit/4fb55fe5a16c32a29a8b0353175691bfbd643b9a and rebased.

**Comment by starius** [comment]
```
$ make mxe-conf MXE_TARGETS=x86_64-unknown-linux-gnu
$ find usr/ -empty -type d
usr/readonly

$ make mxe-conf
# in other terminal:
$ find usr/ -empty -type d
usr/readonly
usr/i686-w64-mingw32.static/installed
```

By the way, `find usr/ -empty -type d` is a good check for `build-pkg`.

**Comment by starius** [comment]
List of empty directories in built MXE:
https://gist.github.com/starius/2b1baa915a1b51e712e7

**Comment by starius** [comment]
`usr/x86_64-unknown-linux-gnu/bin/` has no `.gitkeep`

**Comment by tonytheodore** [comment]
I've added `usr/readonly`, but it requires a `chmod 0755` before `clean`. Not sure if there's a better way to handle it.

> usr/x86_64-unknown-linux-gnu/bin/ has no .gitkeep

It shouldn't need one as `wine` should always be present.

> usr/i686-w64-mingw32.static/installed

This shouldn't be empty after the first package is built so `git` will track it.

**Comment by starius** [comment]
> I've added usr/readonly, but it requires a chmod 0755 before clean. Not sure if there's a better way to handle it.

Remove a directory, not a file in it.

>>usr/i686-w64-mingw32.static/installed

>This shouldn't be empty after the first package is built so git will track it. 

It is empty while `x86_64-unknown-linux-gnu` packages are building. They are separate items in `build-pkg`.

**Comment by tonytheodore** [comment]
> Remove a directory, not a file in it.

I was a little surprised by this too, a directory needs both write and execute permissions to be deleted:
```
$ mkdir -p tmp/readonly
$ touch tmp/readonly/.gitkeep
$ chmod 0444 tmp/readonly
$ find tmp/
tmp/
tmp//readonly
find: tmp//readonly/.gitkeep: Permission denied
find: tmp//readonly: Permission denied

$ chmod 0555 tmp/readonly
$ find tmp/
tmp/
tmp//readonly
tmp//readonly/.gitkeep

$ rm -rf tmp/
rm: tmp//readonly/.gitkeep: Permission denied
rm: tmp//readonly: Directory not empty
rm: tmp/: Directory not empty

$ chmod 0755 tmp/readonly/
$ rm -rf tmp/
```

The errors with `0444` permissions are almost comical as they reveal the contents anyway.

> It is empty while x86_64-unknown-linux-gnu packages are building. They are separate items in build-pkg

Good point, I don't think this can be fixed in mxe-conf (at least not in a way that allows `make -t` to work).

**Comment by starius** [comment]
> at least not in a way that allows make -t to work

I think it is not critical for `build-pkg`, as this directory is created on each item, so `touch '$(PREFIX)/$(3)/installed/$(1)'` may not fail. But `build-pkg` will produce a message about empty directory.

BTW, `build-pkg` [uses](https://github.com/mxe/mxe/issues/1111#issuecomment-170243406) `touch` instead of `make -t`.

**Comment by tonytheodore** [comment]
Okay, the `*/installed` directories are now only created as order-only dependencies and won't be empty. The `.gitkeep` files in those are just to keep `make -t` happy having a file to work with instead of a directory - it's useful for debugging sometimes to see what `make` thinks it needs to do.

**Comment by starius** [comment]
Looks good!

```
$ make mxe-conf MXE_TARGETS=x86_64-unknown-linux-gnu
$ find usr/ -empty -type d
<nothing>
```

**Pull request merged**
