### PR TITLE
pe-util: Only build for the native host

### PR DESCRIPTION
**Pull request by ccawley2011**
This matches what the `pkgconf` package does, and avoids having to cross-compile Boost when it isn't needed.

### CODE REVIEW

**Comment by orgads** [comment]
ping

**Comment by mabrand** [comment]
This seems reasonable, but outside my experience. Any idea why someone once thought differently and commented:: '# install peldd.exe - handy utility (even for static)' ?

**Comment by danger89** [comment]
yea so this peldd.exe binary can be used to list shared object dependencies of a portable executable (PE). If maybe handy to see the shared objects of your exe under WIndows.

That being said if you build your app statically, the changes you really need this is slim. It make more sense with MXE (as a cross-platform tool) to build this tool native for Linux. So you can investigate your shared objects under Linux.

**Comment by danger89** [comment]
Looking at the issue. pe-util isn't well maintained anyway, git submodule of pe-parse is very out of date. And it's causing quite some issues with compilation.

**Comment by gsauthof** [comment]
> Looking at the issue. pe-util isn't well maintained anyway, git submodule of pe-parse is very out of date. And it's causing quite some issues with compilation.

pe-util is maintained well. You can't expect that it still compiles out-of-the-box after blindly updating the submodule, though.

I haven't updated the pe-parse submodule in the last years because I'm not aware of any concrete issues an update would fix.

**Comment by danger89** [comment]
> pe-util is maintained well. You can't expect that it still compiles out-of-the-box after blindly updating the submodule, though.
> 
> I haven't updated the pe-parse submodule in the last years because I'm not aware of any concrete issues an update would fix.

You are right. **I'm sorry. I will take my words back.** I discovered that MXE is not using your git submodule, instead MXE is using it's own `pe-parse` package for your dependency instead of relying on your git submodule version of `pe-parse`.

**Comment by mabrand** [comment]
@danger89, @ccawley2011 : Do you both feel this should be merged now?

**Comment by danger89** [comment]
If it still builds. I'm fine with that. Disclaimer: I was actually not using pe-util. I did need pe-parse though.

That being said, maybe @gsauthof (author of pe-util), want to update his package using the latest pe-parse. So it's inline with our repo.

**Comment by ccawley2011** [comment]
I've rebased this PR and updated it with the changes from gsauthof/pe-util#14, and it now builds and runs correctly.

**Pull request merged**
