### PR TITLE
gcc: don't install *.dlls to version specific directory

### PR DESCRIPTION
**Pull request by tonytheodore**
See https://github.com/mxe/mxe/pull/1017#issuecomment-161243848

* any future side-by-side installs will use targets as a higher level
  directory separation, we don't want to mix libs built with different
  versions of the compiler.
* add note about keeping `--enable-version-specific-runtime-libs`
* remove TODO, there's no sane way to configure the install

```
$ find usr -name libgcc_s_*.dll
usr/i686-w64-mingw32.shared/bin/libgcc_s_sjlj-1.dll
usr/i686-w64-mingw32.shared.posix/bin/libgcc_s_sjlj-1.dll
usr/x86_64-w64-mingw32.shared/bin/libgcc_s_seh-1.dll
usr/x86_64-w64-mingw32.shared.posix/bin/libgcc_s_seh-1.dll
```

### CODE REVIEW

**Comment by starius** [comment]
Can https://github.com/mxe/mxe/tree/gcc-dll be removed?

**Comment by tonytheodore** [comment]
Gone https://github.com/mxe/mxe/tree/gcc-dll

**Comment by starius** [comment]
#1017 is working now.

**Comment by tonytheodore** [comment]
Thanks, this has no build-time impact and is hopefully the last time we look at it (until 5.2 and `libcc1`).

**Pull request merged**
