### PR TITLE
binutils: update to 2.36.1

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
@mabrand ?

**Comment by orgads** [comment]
ping

**Comment by tonytheodore** [comment]
At the moment, these versions (along with #2576, #2577, #2579, and #2580) are tied to the default compiler. 

That will be changing soon, but in the mean time, newer versions should be in their respective plugins.

**Comment by orgads** [comment]
Why? I successfully built the older compilers with these versions.

**Pull request closed without merging**
