### PR TITLE
Add ccache and enable by default

### PR DESCRIPTION
**Pull request by tonytheodore**
See #2272

### CODE REVIEW

**Comment by tonytheodore** [comment]
[Building qt5 & qtwebkit from scratch](https://gist.github.com/tonytheodore/7104a1d14413a8f2c7cdfff5db39dfd9):

```
no cache: 126m13.904s
cache 00: 150m29.873s
cache 01: 45m3.009s
cache 02: 45m4.558s
```

less impressive than some individual packages, but there's a lot of non-compile steps going on. I think it's especially useful when incrementally working on a single package. cmake encodes full paths so it's easy to toggle outside the mxe build environment, other build systems need to set $PATH.

I think this is good to merge as a first step. @tehnick @mabrand can you think of any reasons we shouldn't enable it by default?

**Comment by tehnick** [comment]
> can you think of any reasons we shouldn't enable it by default?

I do not see such reasons.

**Comment by tehnick** [comment]
> I think it's especially useful when incrementally working on a single package.

So do I. More over I see this option as very useful for development of MXE itself.

For example, my build environments for hobby tasks look like this:
```
$ du -hs /opt/mxe*
0       /opt/mxe
3,0G    /opt/mxe-hobby__2019-01-10
4,1G    /opt/mxe-hobby__2019-02-04
3,2G    /opt/mxe-hobby__2019-02-25
3,2G    /opt/mxe-hobby__2019-03-01
4,2G    /opt/mxe-hobby__devel
1,7G    /opt/mxe-hobby-winxp__2018-03-03
1,9G    /opt/mxe-hobby-winxp__2018-03-21
7,0G    /opt/mxe-master
```
And for work tasks:
```
$ du -hs /opt/mxe*
0       /opt/mxe
4,8G    /opt/mxe__2018-12-21
5,4G    /opt/mxe__2019-01-11
5,4G    /opt/mxe__2019-02-12
1,2G    /opt/mxe__master
2,0G    /opt/mxe-winxp__2018-03-14
6,1G    /opt/mxe__work
```
Do not pay an attention to symlinks (`/opt/mxe`).

As you see I have constant directories for updating and testing of MXE:
```
/opt/mxe-hobby__devel
/opt/mxe-master
/opt/mxe__master
/opt/mxe__work
```
They are re-built quite often. For example, when I update packages myself and prepare PRs for upstream (using separate git branches, so almost all paths are the same). Previously I had more permanent directories, like:
```
/opt/mxe__gcc6
/opt/mxe__gcc8
etc.
```
But now I do not have time for such experiments. And since I have found a lot of problems with gcc8 I use gcc6 in all my working branches.

As for directories with dates in their names: they are used by my [simple build server](https://github.com/sibuserv) for hobby and at work (see [special git tags](https://github.com/sibuserv/mxe/releases) in my fork of MXE). And I completely do not care if they will be built a bit longer.

**Comment by tehnick** [comment]
Hope my example will be useful for understanding how different people use MXE.

**Comment by tonytheodore** [comment]
Interesting, there's a few different scenarios. I have some WIP that will make some of those scenarios a little easier to manage:
  - target specified gcc versions e.g. x86_64-w64-mingw32.shared.gcc6
  - content checksums to avoid rebuilds when changing branches

I haven't tested sharing the MXE_CCACHE_DIR across multiple mxe directories, it should work in principle.

**Comment by tonytheodore** [comment]
I've added an `MXE_CCACHE_BASE_DIR` variable which sounds like it will work [according to the docs](https://ccache.samba.org/manual/latest.html#_compiling_in_different_directories), but haven't tested it. In combination with `MXE_CCACHE_DIR` and the user config in `MXE_CCACHE_DIR/ccache.conf`, it should be possible to tweak this to handle multiple directories.

I think this is ready to go.

**Pull request merged**
