### PR TITLE
[WIP] jack: consolidate patches and fix build for python3.5

### PR DESCRIPTION
**Pull request by starius**

### CODE REVIEW

**Comment by tonytheodore** [comment]
Thanks! I was just trying to install a later `python` to investigate.

**Comment by starius** [comment]
`WIP` in the beginning of pull request name means "Work in progress". Do not merge such pull requests, please. On the other hand, this pull request seems to be correct.

**Comment by tonytheodore** [comment]
Apologies, it's building here with:

```
$ python --version
Python 3.5.1 :: Anaconda 2.4.1 (x86_64)
```

**Comment by tonytheodore** [comment]
And failing the same as #1108 without https://github.com/mxe/mxe/commit/3ecfb20f826ac6ac18d217c78c0d341b42567e55

**Comment by starius** [comment]
Thanks! Does [waf file from upstream](https://github.com/jackaudio/jack2/blob/master/waf) work for you?

**Comment by tonytheodore** [comment]
Not with a quick check. Firstly an issue with patch-tool:

```
sed: RE error: illegal byte sequence
```

fixed with: `gsed -i 's/sed /gsed /g' tools/patch-tool-mxe`

Then:

```
[build]     jack                   i686-w64-mingw32.static

Failed to build package jack for target i686-w64-mingw32.static!
------------------------------------------------------------
patching file wscript
patching file waf
patching file waf
cd '/Users/tonyt/dev/mxe/tmp-jack-i686-w64-mingw32.static/jack-1.9.10' && AR='i686-w64-mingw32.static-ar' CC='i686-w64-mingw32.static-gcc' CXX='i686-w64-mingw32.static-g++' PKGCONFIG='i686-w64-mingw32.static-pkg-config' ./waf configure build install -j '8' --prefix='/Users/tonyt/dev/mxe/usr/i686-w64-mingw32.static' --dist-target=mingw
Error: run waf-light from a folder containing waflib
make[1]: *** [build-only-jack_i686-w64-mingw32.static] Error 1
real	0m6.051s
user	0m5.563s
sys	0m0.433s
------------------------------------------------------------
[log]      /Users/tonyt/dev/mxe/log/jack_i686-w64-mingw32.static
```

It looks like we'd need to update all `waf` components, not just the top-level script.

**Comment by starius** [comment]
The error looks like you have removed binary part of waf file. Github doesn't show binary part of that file even in [raw view](https://raw.githubusercontent.com/jackaudio/jack2/master/waf). You should clone https://github.com/jackaudio/jack2 and copy waf file manually.

**Comment by tonytheodore** [comment]
> You should clone https://github.com/jackaudio/jack2 and copy waf file manually.

I tried that and get the same error. Copying the `waflib` directory leads to other errors so I probably need to do some reading about waf.

**Comment by starius** [comment]
Probably we should ask jack project to upgrade waf.

**Pull request merged**
