### PR TITLE
cmake wrapper: don't pass -DCMAKE_TOOLCHAIN_FILE to cmake when  with --build

### PR DESCRIPTION
**Pull request by starius**
see #932

### CODE REVIEW

**Comment by tonytheodore** [comment]
Looks good, just two points:
 - use `#!/usr/bin/env bash` for portability
 - the `-P` mode also doesn't use the toolchain file (and probably others)

**Comment by starius** [comment]
`-P` works with the toolchain file.
```
$ cat 111.cmake 
message("123")
$ cmake -P 111.cmake 
123
$ /mxe/usr/bin/i686-w64-mingw32.static-cmake -P 111.cmake 
123
```

I am checking [other options](https://cmake.org/cmake/help/v2.8.8/cmake.html#section_Options).

**Comment by starius** [comment]
Fixed.

**Comment by tonytheodore** [comment]
Thanks!

**Pull request merged**
