### PR TITLE
pkg-config files

### PR DESCRIPTION
**Pull request by darealshinji**
Install pc files for libiconv, libpaper and openjpeg. Update ghostscript's pc file entries.
Should fix some points from https://github.com/mxe/mxe/issues/1446

### CODE REVIEW

**Comment by starius** [comment]
Why does package `openjpeg` create both `openjp2.pc` and `openjpeg.pc`?

**Comment by starius** [comment]
For `libiconv` you create .pc file for native target (`$(PKG)_BUILD_$(BUILD)`) instead of cross-target (`$(PKG)_BUILD`). `ghostscript` fails to build because it can't find `libiconv.pc`.

Please create .pc file for cross-target of `libiconv`.

**Comment by darealshinji** [comment]
> Why does package openjpeg create both openjp2.pc and openjpeg.pc?

I wasn't sure if I should name the pc file `openjp2.pc` or `openjpeg.pc`.

**Comment by starius** [comment]
> I wasn't sure if I should name the pc file openjp2.pc or openjpeg.pc.

I [grepped github](https://github.com/search?l=cmake&q=openjpeg.pc&ref=searchresults&type=Code&utf8=%E2%9C%93) and discovered many variants, including `libopenjpeg.pc`. However it is confusing to have a package under different names in one installation. (At the moment, there is only one symlink in the library of packages: `libpng.pc -> libpng16.pc`.) IMHO, we should keep only one of them and `openjpeg.pc` seems the best candidate, because it matches with the package name in MXE.

**Comment by starius** [comment]
`libpaper` is not built for shared targets, so `libpaper.pc` is not created for shared libraries, so `ghostscript` fails.

By the way, why `ghostscript` didn't fail to build on shared libraries without libpaper? Is it an optional dependency?

**Comment by darealshinji** [comment]
Yes, I think it's optional. I think most of the non-optional dependencies are those that are included within the source package.
Should I remove the dependency on libpaper or should I add a conditional check like this?
``` sh
echo 'Requires: libiconv libidn $(if $(BUILD_STATIC),,libpaper) libtiff-4 libpng jpeg openjpeg lcms2 zlib'; \
```

**Comment by starius** [comment]
> echo 'Requires: libiconv libidn $(if $(BUILD_STATIC),,libpaper) libtiff-4 libpng jpeg openjpeg lcms2 zlib'; \

Looks good to me.

[In general](https://github.com/mxe/mxe/issues/1111), optional dependencies should be either:

  * explicitly disabled in cmake/configure options,
  * or treated as normal dependencies

to achieve predictable build artefacts not dependant on build order.

**Comment by Rinat84** [comment]
https://distfiles.dereferenced.org/pkgconf

**Comment by tonytheodore** [comment]
@Rinat84, that appears to be the source tarballs for `pkgconf` - I'm not sure what you intended to link to?

**Comment by tonytheodore** [comment]
These really should come from the upstream projects, we can add *.pc files where it's convenient for us, but not across the board.

**Pull request closed without merging**
