### PR TITLE
Add the Boost c++ network library

### PR DESCRIPTION
**Pull request by paralin**
This library is from http://cpp-netlib.org/

It's a proposed addition to Boost that adds high level networking.

### CODE REVIEW

**Comment by starius** [comment]
Thank you for the pull request!

There are some problems detected in this pull request.

1. It needs rebasing.
2. The list of packages in `index.html` should be sorted alphabetically.
3. Implement the package updater (`define $(PKG)_UPDATE`)
4. Update to version 0.11.2
5. MXE has switched to SHA1 checksums.
6. Static builds succeed, but it installs CMake modules to `i686-w64-mingw32.static/CMake/`. MXE CMake modules should be installed to `usr/share/cmake/modules/` or `usr/<target>/share/cmake/`.
7. Shared builds fail with linking errors. See [the log](https://gist.github.com/starius/ea2c9d4ea5f05371a4fb).

I have done (1), (2) and (5) in [this patch](https://gist.githubusercontent.com/starius/d9b08f3c7ae4c7188b6d/raw/6442b33281765216a05dc2ce5112b99a61fe017b/0001-Add-cpp-netlib.patch). Please fix other problems.

**Comment by nieknooijens** [comment]
any update on this yet?

**Comment by starius** [comment]
I have done all items except 6 and 7 here:
https://github.com/LuaAndC/mxe/tree/cpp-netlib

**Comment by tonytheodore** [comment]
> I have done all items except 6 and 7 here:

Thanks! 6 & 7 fixed: https://github.com/mxe/mxe/commit/cebe9e985075912e45bb385fbb6a1505838036da

All merged https://github.com/mxe/mxe/compare/79f424f...cebe9e9.

**Comment by nieknooijens** [comment]
Thanks! pulling it now!

**Pull request closed without merging**
