### PR TITLE
CI: Update to latest Ubuntu LTS

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
@tonytheodore Can you please update netlify?

**Comment by orgads** [comment]
ping

**Comment by mabrand** [comment]
No, it's in Tony's account.

**Comment by orgads** [comment]
What are the advantages of netlify over github actions?

**Comment by mabrand** [comment]
I'm not really the one to ask, since I haven't been involved in this aspect of the project.

**Comment by tonytheodore** [comment]
I've updated netlify, but [I'm not really sure if we need it](https://github.com/mxe/mxe/issues/1909#issuecomment-343732589).

**Pull request merged**
