### PR TITLE
Update qt5 freeze example

### PR DESCRIPTION
**Pull request by tehnick**
Old QtWebkit has known security issues. Also its JavaScript interpreter is very outdated and cannot execute scripts on many modern websites. So I propose update this package even for old version of Qt.

I have successfully tested not only the build of this version of QtWebkit library, but also its work in WinXP. But any additional tests are welcome!

### CODE REVIEW

**Comment by tehnick** [comment]
BTW, I have tested builds with GCC 5.x and GCC 6.x. But work -- only for GCC 6.x builds.

**Comment by tehnick** [comment]
> I have tested builds with GCC 5.x and GCC 6.x.

Sorry for misinformation. It appears that all builds were tested with:
```
MXE_PLUGIN_DIRS += plugins/gcc6
```

**Comment by tehnick** [comment]
Now I have explicitly checked that with GCC 5.x `qtwebkit` package is built fine. But I cannot check it in our real applications because they require GCC >= 6.x..

**Comment by tonytheodore** [comment]
Thanks!

**Pull request merged**
