### PR TITLE
update gstreamer

### PR DESCRIPTION
**Pull request by pavelvat**
GStreamer *.dll plugins are installed now into '$(PREFIX)/$(TARGET)/bin/gstreamer-1.0' instead '$(PREFIX)/$(TARGET)/bin/'

The patch gst-plugins-base-1-intrinsics.patch was removed (seems not needed).

mpg123 has been moved from gst-plugins-bad to gst-plugins-ugly in gstreamer-1.8 https://gstreamer.freedesktop.org/releases/1.8/

opus has been moved from gst-plugins-bad to gst-plugins-base in gstreamer-1.8 https://gstreamer.freedesktop.org/releases/1.8/

$(PKG)_UPDATE for gstreamer now contain ```.[02468]``` instead ```[02468]``` to conform versions 1.10, 1.12, 1.14, ...

I am not sure that 
```$(MAKE) -C '$(BUILD_DIR)' -j $(JOBS) CFLAGS='-DWAVE_FORMAT_DOLBY_AC3_SPDIF=0x0092'```
still needed.

The strings:
```
$(SED) -i 's,glib-mkenums,$(PREFIX)/$(TARGET)/bin/glib-mkenums,g'       '$(1)'/gst/Makefile.in
$(SED) -i 's,glib-genmarshal,$(PREFIX)/$(TARGET)/bin/glib-genmarshal,g' '$(1)'/gst/Makefile.in
```
were removed because glib-mkenums and glib-genmarshal are not presented in Makefile.in.
By the way, ELF binaries are not to be present in $(PREFIX)/$(TARGET)/bin. Right place for them is ```mxe/usr/x86_64-unknown-linux-gnu/bin``` or ```mxe/usr/bin```

The dependencies from https://github.com/mxe/mxe/issues/1624 will be added in this PR later.

### CODE REVIEW

**Comment by pavelvat** [comment]
>By the way, ELF binaries are not to be present in $(PREFIX)/$(TARGET)/bin. Right place for them is mxe/usr/x86_64-unknown-linux-gnu/bin or mxe/usr/bin

They are not ELF:
glib-mkenums is perl script.
glib-genmarshal is symbolic link to /usr/bin/glib-genmarshal
Nevertheless is the path $(PREFIX)/$(TARGET)/bin suitable for them?

Search ELF files:
```
~/builds/mxe/usr/i686-w64-mingw32.shared/bin$ find . -exec file {} \; | grep ELF
./pg_config: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5c953b620799df31e7f328642dfa22e8e7ccf745, not stripped
```

**Comment by pavelvat** [comment]
>The dependencies from #1624 will be added in this PR later.

Done.

**Comment by pavelvat** [comment]
GStreamer version was updated to 1.10.4 according to latest release https://gstreamer.freedesktop.org/news/

**Comment by pavelvat** [comment]
clementine_qt4 has been updated according to:
>GStreamer *.dll plugins are installed now into '$(PREFIX)/$(TARGET)/bin/gstreamer-1.0' instead '$(PREFIX)/$(TARGET)/bin/'

Also some of clementine_qt4 dependencies have been removed (they are not used currently).

**Comment by pavelvat** [comment]
clementine_qt4 with gstreamer-1.10.4 uses ~50% CPU for playing any music file, while clementine_qt4 with gstreamer-1.6.2 uses ~1% CPU. 

If replace directory with plugins for clementine_qt4 with gstreamer-1.10.4:
```clementine_qt4/bin/gstreamer-plugins```
on ones from clementine_qt4 with gstreamer-1.6.2 then CPU usage reduces to ~1%.

**Comment by pavelvat** [comment]
This PR was splitted on https://github.com/mxe/mxe/pull/1695 and https://github.com/mxe/mxe/pull/1696

**Comment by pavelvat** [comment]
I have tested gstreamer-1.8.3, in result the same problem with 50% CPU load.
Linux version of clementine (Debian unstable) uses gstreamer-1.10.4 and have not problem with high CPU load.

**Comment by pavelvat** [comment]
updated to new version 1.12.1

>clementine_qt4 with gstreamer-1.10.4 uses ~50% CPU for playing any music file

version 1.12.1 not contain this bug, so this PR is ready to merge.

**Comment by pavelvat** [comment]
commit was updated (removed libmad dependency from gst-plugins-ugly) according to:
https://gstreamer.freedesktop.org/releases/1.12/
>Plugin removals
The mad mp1/mp2/mp3 decoder plugin was removed from gst-plugins-ugly, as libmad is GPL licensed, has been unmaintained for a very long time, and there are better alternatives available. Use the mpg123audiodec element from the mpg123 plugin in gst-plugins-ugly instead, or avdec_mp3 from the gst-libav module which wraps the ffmpeg library. We expect that we will be able to move mp3 decoding to gst-plugins-good in the next cycle seeing that most patents around mp3 have expired recently or are about to expire.

**Comment by pavelvat** [comment]
problem with clementine_qt4:
```
Failed to build package clementine_qt4 for target i686-w64-mingw32.shared!
------------------------------------------------------------
install '/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/bin/libgstreplaygain.dll'        '/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/apps/clementine_qt4/bin/gstreamer-plugins'
install '/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/bin/libgstsouphttpsrc.dll'       '/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/apps/clementine_qt4/bin/gstreamer-plugins'
install: cannot stat '/home/pavel/builds/mxe/usr/i686-w64-mingw32.shared/bin/libgstsouphttpsrc.dll': No such file or directory
```

from log gst-plugins-good_i686-w64-mingw32.shared:
```
configure: *** checking feature: soup http client plugin (2.4) ***
configure: *** for plug-ins: souphttpsrc ***
checking for SOUP... yes
configure: *** These plugins will be built: souphttpsrc
```
But in fact the file libgstsouphttpsrc.dll is missing.

**Comment by pavelvat** [comment]
commit updated to gstreamer release 1.12.2

>But in fact the file libgstsouphttpsrc.dll is missing.

This bug was fixed in gstreamer release 1.12.2:
https://bugzilla.gnome.org/show_bug.cgi?id=783778
Also libgstsouphttpsrc.dll was renamed to libgstsoup.dll

**Comment by pavelvat** [comment]
PR ready to merge.
any comments?

**Comment by tonytheodore** [comment]
Looks good and builds on all targets. `--{mandir,docdir,with-html-dir}='$(BUILD_DIR)/sink'` can be added to `$(MXE_DISABLE_DOC_OPTS)` but that's separate.

Thanks!

**Pull request merged**
