### PR TITLE
Posix threads

### PR DESCRIPTION
**Pull request by tehnick**
See: https://github.com/mxe/mxe/issues/2258#issuecomment-450441252

### CODE REVIEW

**Comment by tonytheodore** [comment]
Looks good to me, there's a couple other tidy ups (llvm, qtifw) that I'll do shortly.

Thanks!

**Comment by tonytheodore** [comment]
> couple other tidy ups (llvm, qtifw)

also boost, see https://github.com/mxe/mxe/commit/7f22c4dca90f9ca032c39087c249542569db066b

**Comment by tehnick** [comment]
> also boost, see `7f22c4d`

I am using boost 1.67.0 in my fork now and have used version 1.65.0 before. Sorry for not tested boost from master branch.

**Comment by tehnick** [comment]
> I am using boost 1.67.0 in my fork

The [diff](http://susepaste.org/view/raw/94379185) is quite small in fact.

**Comment by tonytheodore** [comment]
Boost is an ongoing issue #2043. Any given version can be made to work, but not for dependent packages and all variants.

**Comment by tehnick** [comment]
Yep, I am aware of it. Almost each update of major version of boost requires an enormous amount of time for updating of all affected packages. That's why I have not tried to push such changes to upstream.

**Pull request merged**
