### PR TITLE
Refactor MXE configuration and cmake toolchain

### PR DESCRIPTION
**Pull request by tonytheodore**
See #823

### CODE REVIEW

**Comment by tonytheodore** [comment]
This is working nicely on the cmake side of things - wrapper script and toolchain includes from `.../mxe-conf.d/*.cmake` work as expected.

I'd like some feedback on the [implied dependency on mxe-conf](https://github.com/tonytheodore/mxe/commit/98d2138c1637594843313e7e77b3b35e1e5ae694). It has the benefit of guaranteed early execution without causing rebuilds, and I'm curious if there are any unforeseen pitfalls to this (@vog)?

**Comment by vog** [comment]
I think this is a very good way to handle the mxe-requirements more gracefully! Make's order-only dependencies are the right tool for that.

So far I don't see any pitfalls on that, but don't take my word on that. Although I wrote the initial (macro-heavy) core Makefile of MXE, I'm not a GNU Make expert.

So more opinions on possible pitfalls are welcome!

**Comment by starius** [comment]
To make sure that nothing was broken, I am building your pull request as well as its parent commit in master 0d8f76e8586e408e7067211ace94ea1586a37175 with build-pkg.lua. I'll test cross-build of NPG-explorer with static targets of these two builds. I am going to report results tomorrow.

**Comment by tonytheodore** [comment]
> I am building your pull request ... with build-pkg.lua.

Thanks. Off the top of your head, is there a way I can run just the mxe steps (on OSX) in `build-pkg.lua` without building the deb packages?

**Comment by starius** [comment]
> is there a way I can run just the mxe steps (on OSX) in build-pkg.lua without building the deb packages?

1. Set [MXE_DIR](https://github.com/mxe/mxe/blob/2435d7b58fb6fd1e65c1b227fb48db856e6777e6/tools/build-pkg.lua#L18) to current mxe dir.
2. Comment out [makeDebs](https://github.com/mxe/mxe/blob/2435d7b58fb6fd1e65c1b227fb48db856e6777e6/tools/build-pkg.lua#L508). You would not get tarballs. If you still want tarballs, then comment out [this line](https://github.com/mxe/mxe/blob/2435d7b58fb6fd1e65c1b227fb48db856e6777e6/tools/build-pkg.lua#L389) instead.
3. Comment out [makeMxeRequirementsDeb](https://github.com/mxe/mxe/blob/2435d7b58fb6fd1e65c1b227fb48db856e6777e6/tools/build-pkg.lua#L578)

In Lua commenting symbol is `--`.

```lua
-- example of commented line
```

**Comment by vog** [comment]
@starius Maybe it is a good idea to add one (or two) command line options to `build-pkg.lua`, such that these things are possible without editing the LUA code?

**Comment by starius** [comment]
Builds finished.

| this pullrequest | commit          | main log | all logs |
| ---------------- | ----------------| ----------- | ----------- |
| no               | 0d8f76e8586e408 | [link][1]   | [link][2]   |
| yes              | e0fadbb696d8eca | [link][3]   | [link][4]   |

[1]: https://gist.githubusercontent.com/starius/2a60589ae3fccc7a9306/raw/dc7efb5d78f42a6a7db4a5d4e98a0d8f6272d182/build-09Sep2015.log
[2]: http://redjohn.tk/mxe/0d8f76e8586e408e7067211ace94ea1586a37175/log/
[3]: https://gist.githubusercontent.com/starius/2a60589ae3fccc7a9306/raw/dc7efb5d78f42a6a7db4a5d4e98a0d8f6272d182/build-mxe-conf-cmake-09Sep2015.log
[4]: http://elric.ga/mxe/e0fadbb696d8eca564f62531ad1db463da51f359/log/

To find problems in logs, type `grep build-pkg name-of.log`.

These commits were built on different machines (Debian Wheezy and Debian Jessie), so some unrelated problems can be detected.

**Comment by starius** [comment]
> Maybe it is a good idea to add one (or two) command line options to build-pkg.lua, such that these things are possible without editing the LUA code?

Done in 7124ea1c8cbef16e9acceb1a1948e8e725aa31a5 and 53baed5d87ad3850709e5e1a7334df6f4d136f16
I'll make a pull request after testing it.

**Comment by starius** [comment]
Overwriting CMake configuration is fixed:
```
$ grep changes build-09Sep2015.log | grep cmake | wc -l
16
$ grep changes build-mxe-conf-cmake-09Sep2015.log | grep cmake | wc -l
0
```

Number of broken packages decreased:
```
$ grep 'The package is broken' build-09Sep2015.log | wc -l
12
$ grep 'The package is broken' build-mxe-conf-cmake-09Sep2015.log | wc -l
9
```
(Package `gdal` was broken in all 4 targets, but now it is broken in `x86_64-w64-mingw32.static` only. This may be unrelated to CMake configuration, the investigation is needed.)

I think, this pull request is OK.

**Comment by tonytheodore** [comment]
> Package gdal was broken in all 4 targets, but now it is broken in x86_64-w64-mingw32.static only

Should be fixed in https://github.com/mxe/mxe/commit/8afc49f77d2e483a3b23642a4625afa4fde54fef - that was the last broken package (for me on Jessie). All the other "easy" file conflicts should also be fixed, but I'll open a new issue with the remainders.

> I think, this pull request is OK.

I have another set of changes related to the wrapper script, but I'll open a new request for that.

**Comment by TimothyGu** [comment]
No complaints from me.

**Comment by tonytheodore** [comment]
Okay, rebased and merged.

**Pull request merged**
