### PR TITLE
[WIP] qbittorrent: fix qmake config for win32-g++

### PR DESCRIPTION
**Pull request by tonytheodore**
May only be an OSX issue or something to do with my setup.

See https://github.com/tonytheodore/mxe/pull/7#issuecomment-222419989

### CODE REVIEW

**Comment by starius** [comment]
The issue with configuration name was discussed in https://github.com/qbittorrent/qBittorrent/pull/4824#discussion-diff-54474098

Can you check it with the following patch, please?

```diff
diff --git a/winconf.pri b/winconf.pri
index 8e1343d..efd0f63 100644
--- a/winconf.pri
+++ b/winconf.pri
@@ -52,7 +52,7 @@ CONFIG(debug, debug|release) {
 # Enable backtrace support
 CONFIG += strace_win
 
-win32-g++* {
+*g++* {
     include(winconf-mingw.pri)
 }
 else {
```

**Comment by tonytheodore** [comment]
Unfortunately, that doesn't work either. I suspect there's something else wrong as the simplest *.pro file:
```
*g++* {
    message(g++)
    }
else {
    message(not g++)
    }
```
returns:
```
$ i686-w64-mingw32.static-qmake-qt4
Project MESSAGE: not g++
Project MESSAGE: not g++
Project MESSAGE: not g++
```

**Comment by tonytheodore** [comment]
Both `win32-g++*` and `*g++*` work with `qmake-qt5`.

**Comment by starius** [comment]
I created issue https://github.com/mxe/mxe/issues/1379 not to forget to fix this problem.

**Pull request closed without merging**
