### PR TITLE
Attempt 2 at creating a pull request branch for enabling TCL/Tk

### PR DESCRIPTION
**Pull request by highperformancecoder**

### CODE REVIEW

**Comment by starius** [comment]
Files produces by `make tk`: https://gist.github.com/starius/cfaccd3bd5cea514bbb5

There are exe files produced: `tclsh86.exe` and `wish86.exe`. MXE normally doesn't install tools. See #881.

It produces file `zlib1.dll`. Is it zlib? Zlib is available in MXE. Can it use external zlib?

Static libraries `lib/libtcl86.a`, `lib/libtclstub86.a`, `lib/libtk86.a` and `lib/libtkstub86.a` are produced on both static and shared builds. They shouldn't be produced on shared builds.

What are `lib/dde1.4`, `lib/itcl4.0.3`, `lib/reg1.3`, `lib/sqlite3.8.8.3` for? They contain both shared and static libraries on all builds.

Avoid installing docs if possible: directories `man`, `share/man`.

**Comment by highperformancecoder** [comment]
Looks like I will need to write a custom install command, rather than fart around with make install.

Re other questions, yes, the regular zlib1.dll can be used. TCL, for some bizarre reason, assumes there is no valid zlib around.

Not sure what the dde and reg directories are. itcl is an OO-based extension to TCL, so presumably we want that (although I don't personally use it). We will probably need to include sqllite, or not build TCL to use it, as the regular sqllite package does not build on MXE IIUC.

**Comment by starius** [comment]
> Looks like I will need to write a custom install command, rather than fart around with make install.

Try to exclude executables from `Makefile.in`. For `tcl` try the following patch:

```diff
diff --git a/win/Makefile.in b/win/Makefile.in
index 325b365..451a2b6 100644
--- a/win/Makefile.in
+++ b/win/Makefile.in
@@ -570,7 +570,7 @@ install-binaries: binaries
                else true; \
                fi; \
            done;
-       @for i in $(TCL_DLL_FILE) $(ZLIB_DLL_FILE) $(TCLSH); \
+       @for i in $(TCL_DLL_FILE) $(ZLIB_DLL_FILE); \
            do \
            if [ -f $$i ]; then \
                echo "Installing $$i to $(BIN_INSTALL_DIR)/"; \
```



> yes, the regular zlib1.dll can be used. TCL, for some bizarre reason, assumes there is no valid zlib around

File `Makefile.in` has variable `ZLIB_DIR`. I think, it can be provided to `make` command. You have provided `zlib` as a dependency. Either use it or remove the dependency :)




> We will probably need to include sqllite, or not build TCL to use it, as the regular sqllite package does not build on MXE IIUC.

MXE [has](https://github.com/mxe/mxe/blob/master/src/sqlite.mk) `sqlite` package.

One more note: do `make install` in a separate command and provide `-j '$(JOBS)'` to `make`, `-j 1` to `make install`. This should speed up build.

**Comment by highperformancecoder** [comment]
Wouldn't it be easier to pick and choose what we want to install, and more maintainable, rather than patch someone else's code?

**Comment by highperformancecoder** [comment]
The zlib dependency is required for the shared build. I'm not sure the ZLIB_DIR will work in the way you think, but I'll give it a try.

**Comment by starius** [comment]
> Wouldn't it be easier to pick and choose what we want to install, and more maintainable, rather than patch someone else's code?

An own code is less maintainable than a one word patch. An own code would work as a white-list while a patch would work as a blacklist (which is actually needed here). Consider upstream adding some new directories. An own code would fail to install them in contrast to a patch (maybe rebased).

**Comment by tonytheodore** [comment]
@highperformancecoder, take a look at what @starius has done with [`luarocks`](https://github.com/mxe/mxe/tree/master/plugins/luarocks). A similar repository for TCL/Tk would be a welcome addition!

While `lua` is clean and small enough to be in MXE core, I think modifying this too much is probably not the best use of anyone's time and may reduce it's general usefulness or maintainability (e.g. `ocaml`). Past attempts with [`python`](https://github.com/schloegl/mxe) and [`octave`](http://hg.octave.org/mxe-octave) end up diverging and spreading resources thinly.

I've [merged this and moved it to plugins/tcl.tk](https://github.com/mxe/mxe/compare/6ebda0e...0ce7656).

To build:
```
make tk MXE_PLUGIN_DIRS=plugins/tcl.tk
```

Note you can use `MXE_PLUGIN_DIRS` to point to any local directory where you keep custom modifications - it should take less mental housekeeping than long-lived branches with `git`.
  
Thanks!

**Comment by highperformancecoder** [comment]
I haven't found the necessary few hours to do this yet.

**Pull request closed without merging**
